### ISSUE TITLE
Add PodPresetBinding as a distinct API resource to integrate OSB bindings with PodPreset

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1032]
Specific action item for #994 

There should a resource distinct from `Binding` (or `ServiceBinding`, or whatever it's called next week) that integrates the OSB binding results with a PodPreset according to the lifecycle of the binding.  Rough sketch of this resource:

```go
type PodPresetBinding struct {
	metav1.TypeMeta
	metav1.ObjectMeta

	Spec   PodPresetBindingSpec
	Status PodPresetBindingStatus
}

type PodPresetBindingSpec struct {
	BindingRef metav1.LocalObjectReference

	// other information about the PodPreset to create goes here
}

type PodPresetBindingStatus struct {
	// looks like the status type we are used to
}
```

This should be in a separate API group from the `servicecatalog` API group.  Other integrations that we choose to build in this repo (if any; I expect that there may be at least one or two more) should be in their own API groups.

There should be a controller backing this resource that hooks into the lifecycle of the `Binding` referenced in the spec:

1.  When the `Binding` is ready, the controller should create the `PodPreset`
2.  When the `Binding` is deleted, the `PodPresetBinding` should be deleted by the garbage collector and finalized by the controller

After this change is made, we should remove the `AlphaPodPresetTemplate` field in the `Binding` resource after a couple releases (or whatever timeframe we agree to; definitely should be removed before beta).

**Comment by arschles** [comment]
@pmorie looks reasonable. 3 questions:

1. Why put these resources into a new API group?
2. Follow-on from (1), why create a new controller to manage these?
3. Will these resources still be serviced by the same svc-catalog API server?

**Comment by pmorie** [comment]
I'm removing the 0.1.0 label because all of our discussion so far has indicated that the initial beta release will not have any PodPreset integration.

**Comment by nilebox** [comment]
`PodPresetBinding` resource (or similar) could provide a mapping between raw JSON credentials object and a secret with injectable environment variables. Credentials object is not necessarily a flat `map[string]string`, and thus could require data transformation. See https://github.com/kubernetes-incubator/service-catalog/issues/1109 for the details.
