### ISSUE TITLE
Proposal: Implement PodPreset in Service Catalog using Initializers

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/service-catalog#1041]
While discussing the roadmap for [PodPreset for Beta](https://docs.google.com/document/d/1bUsO1Sj8K4LlR9lykWtY5kQxd1ovKtZ2LKKtLL7yM5w/edit#), it was suggested that PodPreset should be implemented outside the core Kubernetes.

When PodPreset was introduced in k8s 1.6, it was primarily to fulfill the use case for Service Catalog because there was no other mechanism available to manipulate PodSpec during admission control. But with the introduction of "[extensible admission control](https://kubernetes.io/docs/admin/extensible-admission-controllers/)" and [aggregator](https://kubernetes.io/docs/concepts/api-extension/apiserver-aggregation/) in K8s in 1.7, one can implement PodPreset functionality outside Kubernetes core using an API server and initializer.

So I propose that we should implement PodPreset in Service Catalog itself. It has many advantages:

- It decouples PodPresets from core K8s release, so PodPreset can evolve independently with service catalog releases. 
- PodPreset exists primarily for Service Catalog use case, so they can be iterated to perfect that specific use case without worrying about generic use cases.
- PodPreset being part of Service Catalog also streamlines install/upgrade/release workflows for enduser.

**Comment by duglin** [comment]
Not sure yet if this is a good move or not, but it does make me wonder about something... if we do end up doing this, do we need PodPreset at all? If I have the flow of things right:
- we register an initializer that will call back into the svc-cat during the POSTing of a Pod
- once in our code we could look for LabelSelectors (or whatever) in just about anything - including Paul's PodPresetBinding (of course it would just be PodBinding at that point).

So, I'm not sure we need another level of indirection via PodPresets.

This doesn't mean that someone else might not need PodPresets logic, I still think the idea of auto-injecting some env var (or label if we add that feature) has some nice benefits, but for svc-cat I'm not sure we need it.

**Comment by droot** [comment]
Now that I think more about it, if we are introducing another resource to establish PodPreset Binding, then that can serve the purpose of PodPreset itself. You are right, we don't need another resource in that case. However, I need more details of this new resource to confirm.

A few more clarification:
 * Kubernetes core will not be POSTing a Pod to our initializer. Our controller will have to watch for uninitialized Pods to trigger initialing logic. (But on a high level, the experience is very similar to call back).

**Comment by droot** [comment]
cc @pwittrock @bgrant0607 @pmorie

**Comment by pmorie** [comment]
> Now that I think more about it, if we are introducing another resource to establish PodPreset Binding, then that can serve the purpose of PodPreset itself.

I don't think that's necessarily true.  I don't want to couple the PodPreset functionality to having a binding.  If we move it to the service-catalog API server, I think that it's best to move it intact and have another resource that ties PodPreset to the lifecycle of a binding.

**Comment by pmorie** [comment]
> This doesn't mean that someone else might not need PodPresets logic, I still think the idea of auto-injecting some env var (or label if we add that feature) has some nice benefits, but for svc-cat I'm not sure we need it.

It's been part of the service catalog story from the beginning.  Users need a way to wire information about bindings into their pods without manually mutating every Pod or PodSpec.  They need a mechanism that manages this information along the lifecycle of the binding.  That implies that we need a PodPreset mechanism **and** a resource that manages the lifecycle of PP with the lifecycle of the binding.

**Comment by duglin** [comment]
I think a lot of this will come down to the question of whether PodPreset is a generic thing or a svc-cat thing.  If we think its a generic thing then it shouldn't be done via an initializer that calls into svc-cat. It can still be rewritten as an init, but just not a svc-cat one.  And if so, then yes I agree svc-cat can then make use of it instead of reinventing the wheel.  My only point was that if the exists just for svc-cat and (lives in the svc-cat code) then I begin to question the separation.

**Comment by droot** [comment]
> I don't think that's necessarily true. I don't want to couple the PodPreset functionality to having a binding. If we move it to the service-catalog API server, I think that it's best to move it intact and have another resource that ties PodPreset to the lifecycle of a binding.
@pmorie fair point, having a separate PodPreset API resource sounds good to me.

**Comment by pwittrock** [comment]
@duglin I am thinking we want this in srv-cat code and to be targeted at the srv-cat use case.  Implementing it in the k/k repo as part of *nucleus* will widen the scope of what we need to support and reduce our flexibility to target the srv-cat use case.

**Comment by duglin** [comment]
@pwittrock so there are no usecases outside of svc-cat?  If there is general agreement on that then yea we should move it here but then that leave open the possibility of it being morphed into a svc-cat-specific thing.

**Comment by bgrant0607** [comment]
@pmorie @duglin @droot 

Original request for PodPreset: https://github.com/kubernetes/kubernetes/issues/17097

And I still see it as playing a role in template-free, composable configuration customization:
https://docs.google.com/document/d/1Nxnl7O_q_3WLStxiTdxVPz2IqLGvJRxfFSMeMIf44ms/edit#heading=h.gh6cf96u8mlr

However, Service Catalog is the primary driving use case currently. Istio can continue to use initializers for now.

PodPreset falls outside the Nucleus and Application Layer in the architecture proposal:

https://docs.google.com/presentation/d/1oPZ4rznkBe86O4rPwD2CWgqgMuaSXguIBHIE7Y0TKVc/edit#slide=id.g21b1f16809_5_51

And, we agreed at the leadership summit to stabilize those layers:

https://speakerdeck.com/thockin/kubernetes-state-of-the-project

And to move code out of the kubernetes repo, or at least forestall its growth.

The main reason PodPreset wasn't built in service-catalog originally was the lack of admission control extension. That is being addressed. However, there is little point to building the feature using extension mechanisms (API aggregation, initializers) while the code remains in the kubernetes repo.

While the API might logically be independent of service catalog, I think it makes sense to iterate on it there. I imagine it could simplify co-evolution of the 2 mechanisms.

While someone might want to use PodPreset without service catalog, I don't think it's an excessive burden to run something that provides both, where either could be disabled if desired. Running 2 additional API servers and controllers would be excessive complexity for no gain. Once we have more experience with the API we can consider moving it, though probably not into the kubernetes repo. It's more likely we'd move other APIs out. In general, we're going to be moving APIs and API groups around as we evolve towards the desired architecture.

**Comment by pmorie** [comment]
cc @smarterclayton @derekwaynecarr

**Comment by pmorie** [comment]
We discussed this in SIG architecture on July 24 and reached a decision to move forward with moving the settings API group to our API server intact and without renaming.

**Comment by duglin** [comment]
Note, this implies chaning podpreset to use initializers

**Comment by smarterclayton** [comment]
Note that it is not possible in master or 1.7 to write a pod preset initializer (you cannot mutate spec once it has been laid down).  That work is assumed (but not yet scheduled) for 1.8 in sig-api-machinery.

**Comment by smarterclayton** [comment]
xref https://github.com/kubernetes/kubernetes/issues/47837

**Comment by droot** [comment]
Thanks @smarterclayton for pointing that out.

Discussed this with @caesarxuchao as well. He will take it up with the team.

**Comment by MHBauer** [comment]
current proposed solution is CRD plus webhooks
https://github.com/jpeeler/podpreset-crd
