### ISSUE TITLE
Consider a mode where Binding stores the entire broker payload in a single secret key

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1045]
The current implementation of binding always breaks the `credentials` payload from the broker in the bind response into different keys when it creates a secret.  This is in line with how existing applications in Kubernetes use secrets.

Persisting the entire unmodified payload into a secret is also a valid use case.  For example, it would be easier for someone to build a VCAP_SERVICES-like injection resource if this more were to exist.

We should consider adding a field to `Binding` that controls whether the credentials are persisted as individual keys or as a blob.  Sketch:

```go
type Binding struct {
  // other fields omitted
  SecretMode SecretMode
}

type SecretMode string

const (
  // indicates that individual keys should be persisted
  SecretModeKeys SecretMode = "Keys"
  // indicates that the raw payload from the broker should be persisted
  SecretModeRaw  SecretMode = "Raw"
)
```

**Comment by duglin** [comment]
yep - I was pondering a Mode/Policy kind of flag too. The part that I was stuck on was whether it should be a flag vs something else because people may want both.  Meaning, "give me the properties that can be mapped to env vars, but if I need the rest I'll parse the json myself".

**Comment by pmorie** [comment]
The only challenge I see with the 'both' mode is a collision between one of the credential keys in the payload and the reserved key for the raw payload.  Any ideas?

**Comment by duglin** [comment]
perhaps giving it a kube svc-cat name would make it fairly unique?  e.g.  `K8S_SVC_CAT_CREDENTIALS` ?
