### ISSUE TITLE
Default values of parameters for a specific broker on a namespace level

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1059]
Not all parameter values are suitable for users to set on every provision / bind.  For example, some brokers will require that an API key or other secret key (not to be confused with a Kubernetes secret) be passed to every service/plan.  There should be a way for users to avoid setting these parameters themselves:

1.  The UX of having to enter these parameters is not desireable
2.  It is repetitive and there's a risk of transcription error
3.  Ideally, ordinary users will not have to even be aware of these parameters

Specific example:

1.  Say there is a service broker whose services/plans all accept an API_KEY parameter
2.  Users do not want to have to enter this manually for provision/bind for (what I think are) obvious reasons
3.  It should be possible to set up a default value in the user's namespace for the API_KEY parameter for this particular broker that will apply to all operations to the broker that accept parameters

Note that I am not sure that I have a silver-bullet solution to this problem.  Right now I'm more looking for consensus on the use-case than I am agreement on a particular technical solution.

**Comment by pmorie** [comment]
I think this is an important use-case for dealing with multi-tenant brokers, and I would prefer that it be tackled for beta, but I'm going to avoid setting a milestone on it for now.

**Comment by duglin** [comment]
Is this fundamentally different from people using a configMap to populate parameters?

**Comment by duglin** [comment]
(configMap or secret if the data is sensitive)

**Comment by ash2k** [comment]
1. IMHO beta should enable as many use cases as possible and stabilise the API surface, keeping it as minimal as possible (for obvious reasons). Basically enabled use cases to exposed api surface ratio should be really high for beta. As long as a use case is not blocked completely, it should be good enough for beta quality. Polishing UX is probably not as important as unblocking people (i.e. there are probably more urgent things to implement).
2. IMHO stability and reliability is much more important than UX. Nice things in UX is cool, but system should work reliably first, be spec compliant and then we can add bells and whistles :)
3. In my mind Kubernetes is not a PaaS, it is a platform to build one on top. Features like this one should live in a PaaS IMHO. Kubernetes and svc-cat should provide building blocks that enable PaaS builders to build nice UX. Basically API should be designed for machines, not for humans. This is similar how Kubernetes defines [Nucleus](https://docs.google.com/presentation/d/1oPZ4rznkBe86O4rPwD2CWgqgMuaSXguIBHIE7Y0TKVc/edit#slide=id.g21b1f16809_5_51) and then builds on top.

This is my opinion as an end user, who is building a PaaS.

**Comment by pmorie** [comment]
@ash2k if our API server had initializers, we could build controllers that implement this behavior but that lived outside the 'core of the catalog'.

I definitely appreciate the sentiment of keeping the catalog simple.  With that said, I think this is a pretty fundamental use case that would have widespread appeal - it matters a lot if you work with multi-tenant brokers that service users with different sets of credentials / keys, so we should consider as a group whether we think it belongs in the catalog.

I'm adding this to the agenda for the next SIG meeting to discuss.
