### ISSUE TITLE
Be able to handle a smoking-crater broker

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1063]
It's inevitable that we will need to be able to handle the case of a broker that suddenly goes away (ie, smoking crater situation).  If a broker suddenly disappears, we should be able to do the following:

1.  Keep the active instances and bindings around (provided that they still work) but prevent new instances and bindings (which will not work anyway, if the broker is no longer around)
2.  Be able to delete instances and bindings _without_ having to contact the broker, but still leveraging finalization
3.  Disable further broker re-lists (I think #705 should handle this)

I have some ideas about how to do this, but wanted to get what I think the requirements are out first.

**Comment by vaikas-google** [comment]
do you foresee this requiring a manual step to say that I know this broker has gone away, or being able to detect it? Former is a bit easier :)

**Comment by duglin** [comment]
IMO its manual because it'll be hard to know when its just temporarily on vacation vs dead-and-buried.  :-)

**Comment by pmorie** [comment]
I could see this being a manual step that would set a condition on the broker.
