### ISSUE TITLE
Add plumbing to turn on TLS verification between controller-manager and API server

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#1068]
As discussed by @nilebox in the design meeting today (7/26/2017), we currently skip TLS verification in the controller manager's catalog API client (by passing the `--service-catalog-insecure-skip-verify` flag to the controller manager [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/controller-manager-deployment.yaml#L58)).

We already have the option to generate a [request header CA](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiserver-cert-secret.yaml#L14-L16) that the API server will [use](https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiserver-deployment.yaml#L55-L57), so based on my understanding (h/t to @nilebox for thinking through this with me), we could pass that CA (or a new one, if we don't want to reuse the request header CA) to both the API server and controller manager so that they generate certs in the same chain of trust.

What are your thoughts @pmorie @nilebox @MHBauer?

**Comment by nilebox** [comment]
> so that they generate certs in the same chain of trust

not just that, but we also need to alter the API server client configuration in controller manager to add a trusted CA to it ([controller_manager.go](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/controller-manager/app/controller_manager.go#L146)). Or is the CA some kind of global context shared for all http request? I don't believe so.
