### ISSUE TITLE
Proposal: support different modes of addressing service classes and names with union type

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1081]
The fact that the OSB API does not provide a stable, human-readable coordinate for services and plans presents some special challenges to solve with regard to what the kubernetes names of those entities should be, and how we should address them from the instance resource.

Special challenges:

- Kubernetes API resources do not currently and are unlikely to ever support name changes
- Since there are not stable, human-readable coordinates for service and plan, the human readable names are not a good fit for kubernetes names of these resources
- Users identify more with human-readable names than non-human-readable names, so in the end we should allow users to think in terms of the human-readable name to the greatest possible extent
- There is no precedent in the system for what the Kubernetes names of resources should be when there is no stable, human-readable name

I propose the following solution to this problem:

- Use the OSB API ID of services and plans as the names of the corresponding resources
- Use a union type in the instance resource spec to allow different modes of addressing services and plans based on user preference; initially with the following options:
  - Reference using the kubernetes names
  - Reference using the human-readable names

We should be careful to explain the using human-readable names may not result in the expected behavior since there is a chance that the human-readable coordinate may have changed after the user created the resource.

Specific API changes proposed:

(Note: names below are suggestions for discussion only; the goal here is to illustrate the idea )

```go
type InstanceSpec struct {
  InstanceOrigin `json:",inline"`
}

// InstanceOrigin encapsulates the different ways a user can express what an
// instance is created from.
type InstanceOrigin struct {
  ServiceAndPlanID    *ServiceAndPlanID    `json:"serviceAndPlanID,omitempty"`
  HumanReadableNames  *HumanReadableNames  `json:"humanReadableNames,omitempty"`
}

// ServiceAndPlanID references a service class and plan by their OSB IDs.
type ServiceAndPlanID struct {
  // ServiceClassID is the OSB ID of the service class to create the instance from.
  ServiceClassID string `json:"serviceClassID"`
  // ServicePlanID is the OSB ID of the service plan to create the instance from.
  ServicePlanID  string `json:"servicePlanID"`
}

// HumanReadableNames allows users to specify the human readable names of a
// service class and plan instead of the kubernetes names.
type HumanReadableNames struct {
  // ServiceClassHumanReadableName is the human-readable name of the service
  // class the instance should be created from.
  ServiceClassHumanReadableName string `json:"serviceClassHumanReadableName"`

  // ServiceClassID is the OSB ID of the service class to create the instance from.
  // ServiceClassID is set during admission to be the OSB ID of
  // the service class addressed by its human-readable name in the
  // ServiceClassHumanReadableName field.  This field is read-only to the user.
  ServiceClassID string `json:"serviceClassID"`

  // ServicePlanHumanReadableName is the human-readable name of the service
  // plan the instance should be created from.
  ServicePlanHumanReadableName  string `json:"servicePlanHumanReadableName"`

  // ServicePlanID is the OSB ID of the service plan to create the instance from.
  // ServicePlanID is set during admission to be the OSB ID of
  // the service plan addressed by its human-readable name in the
  // ServicePlanHumanReadableName field.  This field is read-only to the user.
  ServicePlanID  string `json:"servicePlanID"`
}
```

When using the human readable names, an admission controller will set the ServiceClassID and ServicePlanID fields when the resource is created.  Plan updates will thus be possible by changing the human readable plan name.  The controller will _only_ use the the fields of HumanReadableNames that hold the OSB IDs when doing work.

There should be a validations for:

- Ensuring that only a single field of `InstanceOrigin` is set
- Ensuring that a user does not change from one field of `InstanceOrigin` to another during an update
- Ensuring that appropriate fields are set on the fields of `InstanceOrigin`
- Ensuring that the service class name does not change during an update

This API would allow us to do the following:

- Support multiple modes of addressing the service and plan an instance is created from, allowing us to proceed without finding a one-size-fits-all approach
- Allows users to use human readable names in YAMLs if they want to
- Makes it explicit in the instance spec which mode of addressing the user wants
- Allows us to add new methods in a backward compatible way in the future

**Comment by pmorie** [comment]
cc @liggitt @deads2k

**Comment by MHBauer** [comment]
InstanceOrigin is the union type?  One of `ServiceAndPlanID` or `HumanReadableNames`? 

Have we resolved what happens when plans go away? 

Have we resolved what happens on an ‘update’ where the names change but the ID does not? 

HumanReadableNames contains a superset of ServiceAndPlanID. Why do we need both?

ServiceClassID and ServicePlanID is the ExternalID (OSB ID) on each of those objects.
Is ServiceClassHumanReadableName and ServicePlanHumanReadableName the OSB Name?

Does this replace the current ‘ServiceClassName and PlanName fields? (They go away?)

Looking at the existing InstanceSpec, Why not change ServiceClassName and PlanName to be local refs to the real objects. The Status could contain the resolved "human name", thus it can’t be changed by the user.

1. I concur with `Use the OSB API ID of services and plans as the (kubernetes) names of the corresponding resources` because I think usage is mainly programmatic and yaml driven. We can work on shell completion support in kubectl.
1. I do not see the need for the union type.

This seems to the same database questions we keep asking ourselves. We have no indexes, so we have to store the table name(type) + primary keys(kubernetes name) every time we want to have a reference to anything. 
The kubectl plugin is the correct end state from a user experience perspective.

**Comment by pmorie** [comment]
> Have we resolved what happens when plans go away?

We have not - see issue #801

> Have we resolved what happens on an ‘update’ where the names change but the ID does not?

I thought of that while we were talking about this, and i think the human-readable name fields should be write-once due to this.  I will make an adjustment to account for this.  In my original idea, the human-readable names would have been recorded and just become out of date when this happned.  I think that could be really confusing for a user, so it is probably best to have write-once fields.

> Does this replace the current ‘ServiceClassName and PlanName fields? (They go away?)

Correct - I think they would be deprecated and just not carried forward into the beta API.

>  Is ServiceClassHumanReadableName and ServicePlanHumanReadableName the OSB Name?

Correct

> Looking at the existing InstanceSpec, Why not change ServiceClassName and PlanName to be local refs to the real objects. 

I get where you're going with this (I think).  I had used names because that's how we deal with references to global resources in kube.  LocalObjectReference has the structure we would want, but the wrong intent.

> The Status could contain the resolved "human name", thus it can’t be changed by the user.

This means that something has to maintain the status, which might be out of date by the time you read it.  I don't think it buys us much.

> I do not see the need for the union type.

That's fair.  Let me try to prove to you why I think we need it.  Say that we add write-only fields for the human-readable names like I mentioned above within this comment.  I still think that we should have a union type as insurance that if we need to add some additional modes (I can imagine modeling [certain](https://github.com/kubernetes-incubator/service-catalog/issues/805) [use-cases](https://github.com/kubernetes-incubator/service-catalog/issues/1010) that have been mentioned as a sibling within the union type to the strategy we've been discussing here) to the resource, that we can do it in a way that explicitly differentiates the new mode.  As I said before, there have been extremely similar API decisions I've been involved with in k8s that would have been a lot easier if we had strategically used union types from the get-go.  I wrote a little in [this comment](https://github.com/kubernetes-incubator/service-catalog/issues/1010#issuecomment-318960677) about that; relevant bit:

> One parallel to this design problem is the PersistentVolumeClaim resource, where we initially had name-based coordinates and later tacked on service class names and label selectors. I really really wish we had used a union type on that resource to make a clear distinction between the different strategies and I think doing so will pay off here.

I'm totally happy to go into all the gory details about this if you're interested.  Wear clothes you can get dirty if you want to talk about it.

> This seems to the same database questions we keep asking ourselves. We have no indexes, so we have to store the table name(type) + primary keys(kubernetes name) every time we want to have a reference to anything.

Yeah - RDBMSs are just a different beast.  Fundamentally the issue here is that we do not have a well-developed pattern in k8s APIs that we can refer to for precedent about how to handle this situation (no human-readable stable name for a thing represented by a resource).  All names in the system are expected to have meaning (at least, to the maximum extent that a user is willing to or capable of imparting meaning to them), and our API patterns reflect that to a great degree.

I am really, sincerely hoping that what we do to solve this problem can be useful (in the form of a PR to the community API conventions) to make it easier for the next person.  This is the price of being out in front.

>  The kubectl plugin is the correct end state from a user experience perspective.

Ack, glad we agree on that

**Comment by duglin** [comment]
Can we please defer this discussion until Friday when we can discuss this and my proposal: https://github.com/kubernetes-incubator/service-catalog/issues/802#issuecomment-317299121

As to this proposal - I need to review it more but my initial comments are:
- I'm not keen on the idea of having multiple ways in which a person can reference an object - that seems overly complicated.
- if the human name changes, that's the name that the user should see and use from that point forward, regardless of what name was used in the past - otherwise we'll end up in a situation where the same resource can have multiple human names and that's really going to confuse people.
- this doesn't address how people see the list of servicesClasses - which should be by the human name not GUIDs.

I think the proposal in 802 might actually be (kind of) similar but solves it w/o the added complexity.

**Comment by pmorie** [comment]
> Can we please defer this discussion until Friday when we can discuss this and my proposal: #802 (comment)

My point in opening this was to crystallize my ideas, not to try to shut yours out :)  I have no plans to try to force a decision before we get a chance to have a group discussion, but the github discussion on this issue has been extremely useful for me.

> I'm not keen on the idea of having multiple ways in which a person can reference an object - that seems overly complicated.

I'm afraid that I have some terrible news about where I see this problem headed :)

The API problem which is nearest in shape to the one we're solving here is the PVC <-> (PV, storage class) one.  There are exactly 3 different ways to reference a PV from a PVC, with a fourth one on the way.  These ways all have legitimate use-cases, and it's definitely an area where I wish we had employed union types to make the API easier to understand.

I think we have a similar (but not identical) set of use-cases that will make us wish we had used a union type:

- Reference by human readable name / ID to a specific serviceclass/plan
- Reference by trait (ie, the trait-based provisioning we have discussed as a future use-case)
- User provided services
- Reference to a possible 'private' serviceclass/plan

> If the human name changes, that's the name that the user should see and use from that point forward, regardless of what name was used in the past - otherwise we'll end up in a situation where the same resource can have multiple human names and that's really going to confuse people.

I totally understand your motivation here, and I know you want to do the right thing.  However, I just don't think that is going to be possible to implement within the confines of how we treat names in kubernetes.  I suggest that we engage SIG architecture for a call on this matter - how does that sound to you?

> this doesn't address how people see the list of servicesClasses - which should be by the human name not GUIDs.

I don't think that's going to be possible to support natively because it's not how names work in kubernetes - same reasons as above.  I get why you want to do this, I just don't think it's possible to do in a way that is going to work well.

> I think the proposal in 802 might actually be (kind of) similar but solves it w/o the added complexity.

I think within the confines of what I see as the problem space we have to work in, we're probably pretty close.  I think one difference that we have is that I view the union type as a way of decreasing and limiting complexity in time, due to my prior experience adding behavioral modes to k8s resources - obviously you don't share that viewpoint :)

I _am_ going to refine my idea here based on discussions in design meeting yesterday and on github, which might bring things closer to something that will please you, but I suspect we will fundamentally disagree on the particulars until we get a call from sig arch about whether the kind of name transformation you want to do is possible.

**Comment by duglin** [comment]
Related but slightly tangential question... in kube there's a mapping from the unversioned flavor of a resource to the versioned one - is it possible to write custom code to populate one of the versioned properties?  meaning its calculated based on other bits of data?

**Comment by vaikas-google** [comment]
@pmorie - Could you please elaborate on the problem statement little more? You start with:
The fact that the OSB API does not provide a stable, human-readable coordinate for services and plans presents some special challenges to solve with regard to what the kubernetes names of those entities should be, and how we should address them from the instance resource.

Could you enumerate the 'special challenges' before describing the solution, pretty please?

**Comment by pmorie** [comment]
@vaikas-google updated the description of this issue with the following:


Special challenges:

- Kubernetes API resources do not currently and are unlikely to ever support name changes
- Since there are not stable, human-readable coordinates for service and plan, the human readable names are not a good fit for kubernetes names of these resources
- Users identify more with human-readable names than non-human-readable names, so in the end we should allow users to think in terms of the human-readable name to the greatest possible extent
- There is no precedent in the system for what the Kubernetes names of resources should be when there is no stable, human-readable name

**Comment by bgrant0607** [comment]
Portability and declarative configuration require stable, human-readable names.
