### ISSUE TITLE
Complete Documentation 

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-sigs/service-catalog#1133]
Our current design document is woefully out of date with bunch of TODOs
https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/design.md#creating-a-service-instance

And the V1 are not adequate.
https://github.com/kubernetes-incubator/service-catalog/tree/master/docs/v1

**Comment by MHBauer** [comment]
I was always curious what docs people were talking about. Okay, THOSE documents. Agree. Needs improvement.

**Comment by n3wscott** [comment]
This needs to happen. The feature is awesome...
