### ISSUE TITLE
Show number of instances of ServiceClass in ServiceClass.Status

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1215]
Depends on #1214

Similar to how the replicaset controller shows the number of replicas in status, I think it would be useful to have a status field in ServieClass that shows the number of ServiceInstances of that ServiceClass.

**Comment by MHBauer** [comment]
Do you have a link to that part of the controller? Is it in the main line of the updates of the controller or in a sort of side controller?

I ask because I already think our controllers are too complicated.
