### ISSUE TITLE
Allow service brokers to specify labels that are applied to the binding secret

### ISSUE THREAD

**Issue by maleck13** [kubernetes-sigs/service-catalog#1222]
Use case:

I have an application that wants to use the secrets created from certain services in order to generate a configuration  object / file that can be consumed by external clients for those services, for example a mobile application. Currently in order to do this, the application needs to maintain a list of distinct services that it knows about. It would be preferable if I could have the secrets created from the broker have a label, something like "mobile-enabled" that it could use to discover the secrets it could work with.

**Comment by jhalliday** [comment]
It would additionally be useful if the created bind secret could inherit the "template" and "template.openshift.io/template-instance" labels which the platform adds to the Secret/Service/DeploymentConfig that are created when the template is instantiated. Perhaps also ownerReferences.

**Comment by duglin** [comment]
in your workflow, after you create the binding, could you not add the labels to the secrets yourself?

**Comment by jhalliday** [comment]
I'm not the one creating the binding. I have a process that watches deployment changes and reacts to them, but can't influence them.

**Comment by maleck13** [comment]
@pmorie @duglin 
Thinking more about this, I think my general use case is closer to 2. I think it would be useful to allow brokers to return a set of labels (maybe as part of the catalog response that they want applying to objects created based on that ClusterServiceClass.

Example:
The broker adds a set of labels as part of the catalog response.
These labels are then applied to any ServiceInstance, ServiceBinding and Secret created by the catalog based on that ServiceClass.
This would be broker specific meta data, that would be consumed by a UI client for example or a CLI client.
This information could be added from within the broker, but  it means the broker must be aware of and be able to interact with the k8s API
It could also be added by the client, but then it means you need to ensure that each client adds the same metadata.
Implementing something like this in the catalog would mean that no matter which client created the ServiceInstance etc the labels would be present.

If the use case makes sense. I am happy to start putting a  proposal together but want to be sure this is the right place for it.

**Comment by maleck13** [comment]
@pmorie  @duglin  Had no response on this for sometime so just following up after thinking more on it.
Would a reasonable approach here be to allow a set of labels to be specified as part of the ServiceBinding object with the default being none. The name of the secret is allowed to be specified https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/types.go#L1056 so perhaps this would be a reasonable place to allow specifying metadata to be applied to that secret?
Currently we have to create a second secret with the same credentials in it with the labels we need which seems counter productive. 
As mentioned I am happy to put together a proposal and follow up with implementation if accepted.

**Comment by maleck13** [comment]
This would be an approach that works, perhaps it would just be 

```
"platform":{
      "labels":{
              "mylabel":"myval"
      }
  }
```

And then the platform could decide what should be done with that information? In k8s case it would add those labels to the secret. 
Let me know if I am taking that up wrong.
This would be a change to the OSB API spec right so I would need to open up an issue there?

**Comment by carolynvs** [comment]
@maleck13 Can you help me understand why you prefer that the broker add those labels instead of specifying the label say, on the binding?

I'm curious because I am working on a proposal to support adding defaults for service classes and plans, and thought that default labels could be useful as well. So that you could configure a single time at the cluster level "when resources are created for this plan, add this label".

I'm just wondering if you picked #2 (broker supplied labels) because that seemed like less repetition or because the broker is actually in a better position to know what labels are appropriate.

Thanks!

**Comment by maleck13** [comment]
> I'm curious because I am working on a proposal to support adding defaults for service classes and plans, and thought that default labels could be useful as well. So that you could configure a single time at the cluster level "when resources are created for this plan, add this label".

I don't have strong preference here. I was looking for something that would gain traction as I have been struggling with getting engagement on the issue. So delighted to hear I am not alone and you are working towards something similar. 
I actually really like the idea of being able to specify some meta data (annotations and labels ) that are then added to any child resources created from the ClusterServiceClass in particular service instances and service bindings.
If you are thinking of incorporating this kind of change into your proposal I would love to take a look once you have it ready!

**Comment by maleck13** [comment]
@carolynvs how is the proposal coming along?
