### ISSUE TITLE
Non-spec compliant error fields from broker cause extra errors

### ISSUE THREAD

**Issue by bmelville** [kubernetes-sigs/service-catalog#1290]
According to the spec, errors from the broker should have a single string field `description`, and any other fields should be ignored. It seems like the broker client does not ignore other fields, but fails to unmarshal them and results in an odd error in the API object.

Is it possible instead of failing to unmarshal like this to either surface a more sane error, or even surface the non-conformant JSON? It would also be good on errors like this to log the non-conformant response to help in debugging.

```
Error creating ServiceInstanceCredential "xxxx"
      for ServiceInstance "xxxx" of ServiceClass "xxxx"
      at ServiceBroker "xxxx", Status: 500; ErrorMessage: <nil>; Description:
      <nil>; ResponseError: json: cannot unmarshal object into Go struct field failureResponseBody.error
      of type string
```

**Comment by kibbles-n-bytes** [comment]
I believe in this case it may be an issue with my particular fork's changes. I'm closing this until I can verify it's a general SC error.

**Comment by kibbles-n-bytes** [comment]
Looking into this, it seems it wasn't just an issue on my fork. The pmorie/go-open-service-broker-client will attempt to unmarshal errors into the following struct:

```go
type failureResponseBody struct {
        Err         *string `json:"error,omitempty"`
        Description *string `json:"description,omitempty"`
}
```

In most cases, it will just drop the fields that are non-spec compliant. However, it will have issues unmarshalling nested resources that use "error" or "description" as the key.

I think we should make it just not print the unmarshal error into the ResponseErr field, and we should get rid of the `Err` field here (as a field named "error" is not explicitly defined in the spec, and I assume just an attempt to help out the user).

I don't think we can surface the non-conformant JSON, as it might contain sensitive information (for instance, if a credentials payload came back malformed). There is a `Verbose` flag on the OSB client meant for debugging that dumps it into the controller-manager's logs. That can be enabled by adding `c.Verbose = true` before the return statement of `func NewClient` in `vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go` as a band-aid. We may want to surface the verbose option into a command-line flag on the controller.

**Comment by pmorie** [comment]
Seems like there should be an issue in go-osb-client for this

**Comment by bmelville** [comment]
Hey Kibbe, any update on this?

B.

**Comment by kibbles-n-bytes** [comment]
Will get a PR out for this today.

**Comment by kibbles-n-bytes** [comment]
Need to do a bit more design discussion on this, but will be soon.
