### ISSUE TITLE
Make purge-generated make target friendly to expansions

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1309]
Currently the `make purge-generated` target will blast the entire generated clientset directory.  This is not friendly to the client expansion added in #1305 so it should be rewritten or eliminated.

Does anyone actually use this particular target?

**Comment by pmorie** [comment]
0.1.1 candidate

**Comment by MHBauer** [comment]
@pmorie I don't use this, it isn't called by any of the automated tooling. I would expect bitrot if anything.

git history makes it look like your target, I think you get full priority on nuking or rewriting.

**Comment by MHBauer** [comment]
@pmorie I feel like we discussed this, but I do not know why we did not write any notes here.

Still not sure anyone actively uses this target. We do have a note in the devguide to clean up if we decide to remove this.

**Comment by duglin** [comment]
@pmorie I've used this in the past to erase all generated files. If we get rid of this what would be the recommended way to do it?

**Comment by duglin** [comment]
@pmorie I see things like `// Code generated by lister-gen. DO NOT EDIT.` in those files. It seems it is generated but I don't see it as part of our build process - when/where/how did that happen?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
