### ISSUE TITLE
Interacting with the service catalog API extension in third party application

### ISSUE THREAD

**Issue by maleck13** [kubernetes-sigs/service-catalog#1367]
When writing applications that interact with the kubernetes API we have the client-go. I am wondering what is the plan with api extensions such as the service catalog? 
If I wanted to interact with the service catalog API what would be the best way to do this currently?Can I consume the client package in this repo independently?

**Comment by pmorie** [comment]
I think we will have to publish a service-catalog-client-go project with just the client so that you don't have to pull the entire project in.  It's worth thinking about what strategy we should have for releasing such a library so that it will work in the same GOPATH as a contemporary client-go.

**Comment by maleck13** [comment]
Yes a client-go would be good, I think it is an interesting question for all extension API servers. I haven't had to extract a client before, but given that there is a generated clientset, it would be nice if there were tooling (I am not aware of any) that would allow extracting the generated client into a lib as this could be used by all API servers.

**Comment by nilebox** [comment]
> I think we will have to publish a service-catalog-client-go project with just the client so that you don't have to pull the entire project in

While this has been done for Kubernetes core server (with `client-go` project), the other API servers still provide their clients as part of their server repo, for example CRD server: [apiextensions-apiserver](https://github.com/kubernetes/apiextensions-apiserver/tree/master/pkg/client), and the usage example: https://github.com/kubernetes/apiextensions-apiserver/blob/master/examples/client-go/main.go#L26

So I don't think there is an established best practice strategy for providing Go-clients.

**Comment by surajnarwade** [comment]
@pmorie , any progress on this ? I am confused how to use `service-catalog` as a library.

**Comment by maleck13** [comment]
We are currently generating the client based on the api definitions. Using the kubernetes client-gen tool

**Comment by surajnarwade** [comment]
@maleck13 , any blog post or document link will help a lot. I want list down and consume services from my project. here is reference issue https://github.com/redhat-developer/odo/issues/266

**Comment by maleck13** [comment]
@surajnarwade This may be useful https://github.com/aerogear/mobile-cli/blob/master/scripts/generate.sh

Shows how we are using the generate tool. The side effect here is it is up to us to keep the definitions upto date. Although there may be a way around that.
Example usage of the client
https://github.com/aerogear/mobile-cli/blob/master/pkg/cmd/services.go#L62

**Comment by maleck13** [comment]
Would a proposal for this be a way forward? Happy to take this on

**Comment by carolynvs** [comment]
Using dep, I was able to write a third party app that used service catalog's client, and not end up pulling in all of the rest of their code too.

**Gopkg.toml**
```
[[constraint]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "v0.1.18"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
```

It works just like the regular k8s client. I'd like to see this better documented but I don't believe we need a proposal or anything. @maleck13 Would you be interested in writing a new page for our docs that explains how to import, initialize and use the client? I have examples if you think that would help.

**Comment by maleck13** [comment]
@carolynvs awesome this is great. I would be happy to contribute a docs update for this!

**Comment by carolynvs** [comment]
@maleck13 Sweet! Let me know if you have any questions, otherwise feel free to open a WIP PR and we can collaborate there. Feel free to ping me on the k8s slack if that helps.
