### ISSUE TITLE
Enhance integration testing for scenarios where services/plans change or are removed

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1391]
We need to improve the integration tests for changes related to services/plans being updated to removed in the broker's catalog.

Specific scenarios that need to be covered:

- [ ] Service change
- [x] Service removal
- [x] Plan change
- [x] Plan removal

**Comment by MHBauer** [comment]
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.23/test/integration/deleted_services_and_plans_test.go looks to cover removal of services and plans.

https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.23/test/integration/controller_instance_test.go#L557-L749 looks to cover updating plans.

I think service changing is the only thing left.
