### ISSUE TITLE
Use `OwnerReference` controller refs for parent/child relationships

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#1432]
While looking at https://github.com/kubernetes-incubator/service-catalog/issues/1430 I have noticed that we use controller ("parent") `OwnerReference`s only for secrets owned by bindings.

We can use them for many other cases too:
- `ClusterServiceBroker` -> `ClusterServiceClass` -> `ClusterServicePlan`
- `ServiceInstance` -> `ServiceBinding`
- `ServiceInstance`/`ServiceBinding` -> `Secret` with parameters - not sure about this one, since the same secret with parameters can potentially be used by multiple instances/bindings
- `ClusterServiceClass` -> `ServiceInstance` - not sure about this one

It can help us detect conflicts with multiple parents referencing the same children (because of clashing names etc) easier and safer.

**Comment by nilebox** [comment]
After thinking a bit more, we probably want to mark only server-created objects with controller `OwnerReference`. It's probably only the case for `ClusterServiceBroker` -> `ClusterServiceClass` -> `ClusterServicePlan`.

@ash2k WDYT?

**Comment by ash2k** [comment]
@nilebox Is this a dup of #1001? :)

**Comment by nilebox** [comment]
@ash2k I don't think it's dupe since #1001 is very broad and out of date (and I'm not even sure how to address it). @pmorie we should probably close it and create more concrete issues for the things which are still relevant if needed?

This one is solely focused on owner references and uses already merged #979 as an example.

**Comment by nilebox** [comment]
Assigning to myself.

**Comment by ash2k** [comment]
#1001 is about figuring out what is the ideal desired behaviour and documenting it. It is about understanding the "big picture". It is helpful to think about the "big picture", not just individual pieces (they can have individual issues) to achieve consistency of behaviour across svc-cat types and with built in types. That is my $.02 :)

**Comment by MHBauer** [comment]
OwnerReference is ObjectMeta, so this isn't a type change and should be relatively easy to assign on create.

**Comment by carolynvs** [comment]
#dibs I accidentally already started this as part of the user defined plans work in #2095
