### ISSUE TITLE
Handling Broker with "partially" invalid classes/plans

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#1460]
Currently, in case anything goes wrong with class/plan create/update, we give up and abandon classes and plans in a partially synced state.
For example, see [plans for loop](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_broker.go#L320) and [classes for loop](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_broker.go#L369).

Let's say we have P valid plans, C-1 valid classes and 1 service class with a conflicting name. In that case we have a number of possible outcomes (depending on the order of the services returned by the broker):
- 0 classes and 0 plans created
- X classes and P plans created (`0 < x < C`)

We will also have a broker with error condition.

In that case, if `X > 0`, we will be able to create instances and bindings for service classes with plans which were synced before the corresponding `for` loop has encountered a conflicting class. But for the valid classes and plans which were listed after the conflicting class in the broker result, there will be no registered classes and plans.

Shouldn't we skip invalid classes and plans (or mark them with error state) and continue processing valid ones, instead of stopping processing the catalog immediately? In the end of processing, we can collect all encountered errors and report about them in the broker status.

**Comment by nilebox** [comment]
Note that in https://github.com/kubernetes-incubator/service-catalog/pull/1459 I've fixed the order (create classes first, and plans after that), but the issue remains: currently the outcome of syncing a partially valid catalog is non-deteministic, and the user can't create instance for valid plans if there is just one conflicting plan/class in the broker.

**Comment by pmorie** [comment]
I have wondered to myself about the same thing.  It's arguable that we should just skip invalid services/plans and set the error condition on the broker (which is basically just used to communicate to the user that something went wrong).

**Comment by pmorie** [comment]
I don't think this has to block 0.1.0, though.

**Comment by nilebox** [comment]
The alternative option (easy to implement for now) is to prevent usage of classes and plans for the broker without `Ready: true` status. At least it will make a behavior consistent: you need to fix the entire catalog to use any offerings provided by the broker.

**Comment by pmorie** [comment]
@nilebox yeah, i have also thought of that one as well.  I do wonder what CF does.

It's worth thinking about what different scenarios are here.  For example, it probably makes sense to treat a situation where the broker sends invalid json differently from one where the broker has 5 services and one of those services has no plans (which is an error).
