### ISSUE TITLE
Do we still need the troubleshooting firewall rules section of the walkthrough?

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#1617]
It looks like this was from the pre-api-aggregation era?

**Comment by MHBauer** [comment]
@arschles the [bit at the end?](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#troubleshooting) 

@mengqiy do you think there is still likely to be trouble with the firewall? I don't think we're expecting anyone to reach through directly to the APIServer.

I think I agree that this can be removed if this is to enable external access to the running APIServer and not for some internal firewall that needs to be configured.

**Comment by mengqiy** [comment]
If we don't want to support talking to SC apiserver directly, we can remove that section.
