### ISSUE TITLE
Removed service class should not show up in service catalog

### ISSUE THREAD

**Issue by mihnjong** [kubernetes-sigs/service-catalog#1641]
I added a new service class "foo", and removed it in order to add it back with a new description.

The issue is the deleted service class still shows up in `kubectl get clusterserviceclasses` with "removedFromBrokerCatalog: true" status.

Other than display issue, it's annoying when I create an instance (or binding) via `externalName`.

Can somebody investigate why it's not GC'ed? And, how can we make it disappear?

Here's what happened in my cluster:
```
$ kubectl get clusterserviceclasses
NAME                                   AGE                                                                            
96a06adc-302c-4123-9ba8-b8d5130ac83e   1d 
62153072-d076-4167-8014-596d1d2f7d28   1d 
```
The deleted service class shows up along with a new service class.

```
$ kubectl get clusterserviceclass 96a06adc-302c-4123-9ba8-b8d5130ac83e -o yaml

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceClass
metadata:
  creationTimestamp: 2017-12-14T08:35:55Z
  name: 96a06adc-302c-4123-9ba8-b8d5130ac83e
  resourceVersion: "3965"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/clusterserviceclasses/96a06adc-302c-4123-9ba8-b8d5130ac83e
  uid: cd5909af-e0a9-11e7-96aa-0a580a180255
spec:
  bindable: true
  clusterServiceBrokerName: gcp-broker
  description: [[old description]]
  externalID: 96a06adc-302c-4123-9ba8-b8d5130ac83e
  externalName: foo
  planUpdatable: false
status:
  removedFromBrokerCatalog: true
```

**Comment by dmetzler** [comment]
It seems that the same kind of problem appears for instance when an APB is updated and bindable property changes. Then the bindable property is not updated accordingly.
