### ISSUE TITLE
Separate binding injection into configmap, secret, and service

### ISSUE THREAD

**Issue by bmelville** [kubernetes-sigs/service-catalog#165]
Binding injection needs to separate the binding credential into three groups of data:

1. Secret information to be stored in a Secret resource
2. Non-secret information to be stored in a ConfigMap resource
3. Endpoint information to be stored in a Service resource

Because binding credentials are an unstructured data map, there are some key questions to address to solve this properly:

* How to determine whether a piece of data is secret
* How to determine whether a piece of data is endpoint information

It may be fine for the short term to hard code known field names to be deemed secrets or endpoints, e.g.,

* host, hostname, ip, address, and port are endpoint fields
* username, uname, user, and password are secret fields

Depends on #146

**Comment by bmelville** [comment]
This is blocked by features in the Open Service Broker API.

General schematization of credential data: https://github.com/openservicebrokerapi/servicebroker/issues/116
Secret vs. non-secret data: https://github.com/openservicebrokerapi/servicebroker/issues/117
Endpoint information: https://github.com/openservicebrokerapi/servicebroker/issues/121

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632

/close
