### ISSUE TITLE
Consider removing the requirement to use sudo in travis build

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1667]
According to https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments, the container based build environment boots in 1-6s compared to 20-50s for the GCE VM env we currently use in travis.  Might be worth thinking about.

**Comment by kibbles-n-bytes** [comment]
Word of warning: in the past I had a lot of trouble getting Docker-in-Docker tests working for Jenkins, and eventually gave up in favor of a VM-based architecture.
