### ISSUE TITLE
Add sorting to svcat get commands 

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes-sigs/service-catalog#1703]
When using `svcat get classes` or `svcat get plans`, it would be nice if you could optionally sort on columns when there are a large number of classes or plans.

**Comment by carolynvs** [comment]
What do you think about using the same flag name and format as kubectl? e.g. 

```
svcat get plans --sort-by='{.metadata.name}`
```

**Comment by jeremyrickard** [comment]
#dibs 

Yeah, that seems reasonable. I'll work on a PR for this.
