### ISSUE TITLE
Docs: Create better documentation on cluster setup for svc-cat

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes-sigs/service-catalog#1798]
Part of #1678 

We should create better documentation on what is required for installing svc-cat in your cluster. We currently just say to use the helm chart, but it would be good if the documentation explained what was required and done in the helm chart.

**Comment by jberkhahn** [comment]
this is still in the works

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/30645

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
