### ISSUE TITLE
Change svcat tests to be integration tests

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#1810]
Right now the svcat cli tests hit a test http server and return recorded responses. This is both difficult to maintain, and doesn't adequately test the full user experience with our cli.

Let's change the tests to instead be integration tests where we execute the binary from the shell (instead of calling essentially the main function from the test), and have it hit a live service catalog api.

**Comment by n3wscott** [comment]
I agree that there should be integration tests, but I don't think that is all you should use, there should be more go style unit tests on a per method basis to test the details of each thing.

**Comment by carolynvs** [comment]
> I don't think that is all you should use, there should be more go style unit tests

Agreed! 👍   Sorry that wasn't clear, I was only referring to a subset of tests that use the fake http server.

**Comment by carolynvs** [comment]
#dibs
