### ISSUE TITLE
Support refreshing credentials on a deployment

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#1815]
When the credentials in the broker have changed for a service, it would be nice to have a straightforward way to refresh any bound secrets.

When @arschles first suggested this in the original svcat repo, he approached this from the cli. For example:

```
svcat rebind --name BINDING_NAME
```

The above command would create a new binding and then update the original secret with the new values, and then restart anything that was using it.

That would work but I do wonder if perhaps it would be best to have service catalog support this scenario at the API level, instead of filling in functionality gaps through the cli.

___
This issue was migrated from the original svcat repo: https://github.com/Azure/service-catalog-cli/issues/17

**Comment by n3wscott** [comment]
Does this unbind the original binding?

Does rebinding a service instance make the binding count n+1?

**Comment by carolynvs** [comment]
@arschles This was originally your suggestion (I just copied it over from the original svcat repo before archiving it). Maybe we can back up a bit off the implementation and go back to understanding when someone would need to refresh credentials and how we'd like that interaction to look? Can you provide some more context around the original idea?

**Comment by EronWright** [comment]
Imagine that the service broker wished to rotate the credential that is encapsulated within a binding.  Ideally the service catalog would poll the binding information and update the Secret resource accordingly.  When a Secret is updated, Kubernetes automatically updates the secret data in the pod (volume-based secrets only AFAIK).  For example, given a binding that includes a private key file, the file would automatically be updated in all associated pods whenever the broker updated the binding info, without human intervention.

**Comment by n3wscott** [comment]
I think a key rotation feature is something that works with service catalog rather being a service catalog feature directly. It depends on where you want to draw the line, is service catalog enabling building blocks or is it an application? I lean towards building blocks.

**Comment by EronWright** [comment]
@n3wscott the 'building block' that the catalog provides is that it manages a Secret resource that represents the binding info.   Key rotation is application-specific, yes, but what I described is appropriate given the functionality that is intrinsic to the catalog.  I do wonder whether OSBA specifies the updatability of binding information.

**Comment by n3wscott** [comment]
Bindings are not updatable in the current spec.
