### ISSUE TITLE
[svcat] Explode given parameters with dot syntax

### ISSUE THREAD

**Issue by n3wscott** [kubernetes-sigs/service-catalog#1853]
Given, `svcat yada --param foo.bar=baz` it would be neat if that turned into an object like:

```
{
  foo: {
    bar: "baz"
  }
}
```

**Comment by carolynvs** [comment]
🤯 I LOVE IT

**Comment by kikisdeliveryservice** [comment]
#dibs

**Comment by kikisdeliveryservice** [comment]
@n3wscott, @carolynvs  
In my last PR, I updated --params to accept lists. So the new format is:
-p colors=red -p colors=blue -p somethingelse=banana -->
map{colors: [red, blue], somethingelse:banana}

So for our new dot syntax:
--param foo.bar=baz --param foo.fighters=everlong
you want:
map{foo: {bar: "baz", fighters: "everlong"}}

but what if: 
--param foo.bar=baz --param foo.fighters=everlong **--param foo = pretender** 
this is the result, yes?:
map{foo:[{bar: "baz", fighters: "everlong"}, "pretender"]}

**Comment by MHBauer** [comment]
I like this foo-fighters related video: https://www.youtube.com/watch?v=xsg1RPnwH8g
