### ISSUE TITLE
refactor NewController to take the configuration struct directly

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#1884]
currently we piece apart the struct to give it to the constructor, just give it to the constructor and let it take what it wants.

**Comment by MHBauer** [comment]
The arguments to 
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.14/pkg/controller/controller.go#L71 
come from 
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.14/cmd/controller-manager/app/controller_manager.go#L352
and that's filled in using multiple fields from 
`cmd/controller-manager/app/options.ControllerManagerServer`.
I'm thinking we can just pass that in directly, unless there's some circular dependency created.

**Comment by ggriffiths** [comment]
@MHBauer looks like this creates a circular dependency:
```
import cycle not allowed
package github.com/kubernetes-incubator/service-catalog/cmd/controller-manager/app
	imports github.com/kubernetes-incubator/service-catalog/cmd/controller-manager/app/options
	imports github.com/kubernetes-incubator/service-catalog/pkg/controller
	imports github.com/kubernetes-incubator/service-catalog/cmd/controller-manager/app/options
```

**Comment by MHBauer** [comment]
@ggriffiths thanks for taking a look at this.

Needs a bigger refactor.
