### ISSUE TITLE
Add integration tests for credential remapping

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1892]
@n3wscott and I both missed this in #1868

**Comment by n3wscott** [comment]
Shame is on our houses.

**Comment by n3wscott** [comment]
@luksa to fixity fix?

**Comment by luksa** [comment]
There, I fixity fixeded it.

**Comment by sgandon** [comment]
is there anywhere I can find a documentation on the credentials remapping ?
thanks.
