### ISSUE TITLE
[svcat] Allow svcat bind to be given a blob, store it in a given secret, and then use that secret for the binding.

### ISSUE THREAD

**Issue by n3wscott** [kubernetes-sigs/service-catalog#1898]
See https://github.com/kubernetes-incubator/service-catalog/pull/1889#discussion_r178322653

**Comment by carolynvs** [comment]
I'm taking off the help-wanted label until we have laid out what this would look like in this issue first.

**Comment by n3wscott** [comment]
@pmorie halp
