### ISSUE TITLE
Fix usage of`brokerRelistInterval` configurable parameter

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#1905]
The field `brokerRelistInterval` is present in controller, and configurable, but actually not being used at all: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller.go#L80

There is a `relistDuration` field in the broker spec, that is 15 mins by default, and can be overriden by user: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/defaults.go#L45

**Comment by n3wscott** [comment]
seems like the serviceBrokerRelistInterval / brokerRelistInterval should be used to default the brokers relistDuration spec field but it never got wired up or it got unwired and does not have a test :D

I think it seems good to have and it is a little work to wire it in

**Comment by jichenjc** [comment]
so we should use brokerRelistInterval  to set as default value of relistDuration  ? and 15 min can be used if no brokerRelistInterval   given?
