### ISSUE TITLE
no icon in the svc catalog chart

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-sigs/service-catalog#1938]
Hi, would it be possible to add an icon in the svc catalog chart

**Comment by MHBauer** [comment]
This issue came up during the F2F last week.

We need to have a logo at all, first. Then we can use it.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
