### ISSUE TITLE
Implement a naming strategy that gives service classes and plans human readable names

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1950]
When we were trying to deal with name mutability in https://github.com/kubernetes-incubator/service-catalog/issues/802, we decided to use the OSB IDs of services and plans as the k8s names to deal with mutability. This results in a very clunky (basically unusable) kubectl experience because the k8s names are not easily distinguishable. The svcat tool makes this easier to manage, but not every user wants to download and use another tool.

Luckily, we also left ourselves space to implement alternate naming strategies for service classes and plans. I think we should implement an (optional, opt-in) naming strategy that:

- Uses the human readable names of service and plan as the k8s names of associated resources
- Handles name changes by adding new resources with the changed name and updating the status of the existing resource to reflect that it has been renamed

To be super-clear, we will have to maintain the existing behavior of the system. We should allow administrators to decide on this behavior by adding a field to the broker resources that controls the naming strategy, and which defaults to the existing behavior.  For example:

```yaml
metadata:
  name: my-broker
spec:
  url: http://my.broker.to
  namingStrategy: HumanReadable
```

We discussed this as something people were interested in for 1.0.0 at the april f2f.

**Comment by n3wscott** [comment]
This is related: https://github.com/openservicebrokerapi/servicebroker/pull/504

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
