### ISSUE TITLE
svcat does not support multiple files in $KUBECONFIG

### ISSUE THREAD

**Issue by dotchev** [kubernetes-sigs/service-catalog#2009]
I work with multiple clusters. I have a separate config file for each cluster. I have listed them in $KUBECONFIG like this
```
export KUBECONFIG=~/.kube/config:~/.kube/gardener-serviceman
```
This works with kubectl but not with svcat
```
$ svcat version
Error: could not determine the namespace for the current context "": stat /Users/dotchev/.kube/config:/Users/dotchev/.kube/gardener-serviceman: no such file or directory
```
If I set only one config file in $KUBECONFIG, it works
```
$ KUBECONFIG=~/.kube/gardener-serviceman svcat version
client: v0.1.15
server: v1.10.2
```

**Comment by MHBauer** [comment]
@jberkhahn is this something we have in svcat directly or provided by upstream kubectl library?

**Comment by MHBauer** [comment]
/assign @jberkhahn 
Sounds like, works in plugin mode, but not in standalone mode.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
