### ISSUE TITLE
Allow user specified labels to be applied to k8s resources a Broker creates on behalf of a Provision call

### ISSUE THREAD

**Issue by jwmatthews** [kubernetes-sigs/service-catalog#2017]
We'd like the ability for a User at time of provision to be able to pass in a list of labels to be applied to k8s resources a Broker creates during a provision call.

For background, this request was surfaced from work on the Template Service Broker.
Below is original Trello Card
https://trello.com/c/7upa8IX4

A simple approach of injecting a new parameter for labels was added to each of the templates being processed.  During the work the team realized this ability might be desired by other brokers creating resources on k8s and it'd be worth discussing in broader community to come up with a cleaner solution.

**Comment by maleck13** [comment]
@jwmatthews We also discovered something similar. More info in the following issue
https://github.com/kubernetes-incubator/service-catalog/issues/1222
There is a proposal under way I believe
