### ISSUE TITLE
Access to the service catalog types

### ISSUE THREAD

**Issue by shawn-hurley** [kubernetes-sigs/service-catalog#2039]
As a user of the service catalog, I would like to have access to the service catalog types in my go program without having to vendor in the entire service catalog

**Comment by maleck13** [comment]
This would be really great. I have an issue open around this also https://github.com/kubernetes-incubator/service-catalog/issues/1367

I wonder if a proposal to break out the client into a separate package would help move this further?

**Comment by carolynvs** [comment]
@shawn-hurley See my comment on the other issue for an example of how to vendor just the client types that you need:

https://github.com/kubernetes-incubator/service-catalog/issues/1367#issuecomment-389589332

Basically dep will keep in vendor only the packages that you are using (like our typed client) and will prune the other stuff in the service catalog repo.

Let me know if that works for you. Hopefully we can build out doc to explain this better, if you would be interested in helping with that, let me know.

**Comment by MHBauer** [comment]
I like `dep`, but I think eventually we might need to do a repo split.

**Comment by MHBauer** [comment]
Maybe we do syncs when we do a tagged push?

**Comment by carolynvs** [comment]
Ah, you are suggesting a mirrored repo just for the client. I didn't quite understand that when I read through it the first time. 😀

**Comment by MHBauer** [comment]
/assign @jberkhahn 
Does go modules solve this? Maybe this can be part of the movement to a new repo home?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
