### ISSUE TITLE
we should provide a service-catalog-operator (Cluster)Role for users

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2061]
Right now we provide roles for the running of apiserver and controller-manager and their access to the resources, but not for any users of the resources that are created. This somewhat presumes that anyone touching service-catalog resources has super-user access like `ClusterRole cluster-admin`.

We should provide an additional role as appropriate for people to access the service-catalog resources.

 - [ ] service-catalog operator, everything but brokers?
 - [ ] service-catalog user, namespaced? instances and bindings only?

**Comment by pmorie** [comment]
Good idea

**Comment by carolynvs** [comment]
For a second I thought you were proposing that we write an operator (like etcd-operator) to make it easier to install and manage namespaces service brokers or something and was like 🤔 ...

Less privileged RBAC roles is just what we need. 👍

**Comment by nilebox** [comment]
To clarify: this is just a "default RBAC setup" as part of the helm chart, correct?

> This somewhat presumes that anyone touching service-catalog resources has super-user access like ClusterRole cluster-admin

No? It just presumes that the admin user with `cluster-admin` permissions will need to manually create a role and binding for the unpriviliged users.
We don't use Service Catalog helm charts at all, for example, and create our own roles with minimal necessary permissions via our own automation tooling.

**Comment by MHBauer** [comment]
https://github.com/kubernetes-incubator/service-catalog/issues/2061#issuecomment-391101506
> Less privileged RBAC roles 

Yes.

https://github.com/kubernetes-incubator/service-catalog/issues/2061#issuecomment-391952044
> presumes that the admin user with cluster-admin permissions will need to manually create a role and binding for the unpriviliged users.

That's the same thing. Cluster-admin accessing or providing access. We don't currently have a role for an admin to provide access.

> We don't use Service Catalog helm charts at all, for example, and create our own roles with minimal necessary permissions via our own automation tooling.

Your roles if you could share them could be a good starting point for this issue. Minimum necessary permissions is key, whether for automation or a person user.

**Comment by MHBauer** [comment]
@jboyd01 I think it would be good to get a gist or google doc for us to collaborate in on the contents of these user-type rbac rules.
