### ISSUE TITLE
Travis build - why's it take so long?  Can we fix the timeouts?

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-sigs/service-catalog#2062]
This was brought up in the May 21st SIG meeting:  Travis job keeps timing out on various PRs.  Why?  Where is all the time being spent?  What can we do to improve it?  Jay took the action item to gather some basic info on where time is being spent.

Morgan provided some ideas for improvements:
1.  https://github.com/kubernetes-incubator/service-catalog/pull/2034 should help reduce overall time of the run, let's see how much it helps.

2.  modularize the build into more stages.  Currently we have test & deploy.  Additional stages could be used to set up the image, do the build, run the unit tests, integration tests, jekyll stuff (are we switching to hugo as well?), etc

3.  fix https://github.com/kubernetes-incubator/service-catalog/issues/1848 and re-enable parallel tests.  Or, don't fix it, but separate out tests that mutate into a specific class (or vice versa)

**Comment by MHBauer** [comment]
for 3, I think ginkgo might have a feature able to help.

**Comment by MHBauer** [comment]
2 might need some of https://docs.travis-ci.com/user/build-stages/#Sharing-a-Docker-image

**Comment by carolynvs** [comment]
I've created two issues for the doc site:
* #2085 - Move to Hugo
* #2086 - Split out doc site build into separate travis job

**Comment by MHBauer** [comment]
there are some less than optimal things we're doing in the build with the makefile and go install, and the various contortions it would take to get it working better are better spent on waiting for k8s 1.11 to release and then doing #2127

**Comment by MHBauer** [comment]
@carolynvs now XBUILD is timing out. go build and test is down to under 40minutes, anything we can move back to that?

**Comment by MHBauer** [comment]
during integration tests, we should reuse the generated certs, or check in some dummy copy to use (being careful to regenerate them periodically if we put a time limit on them). it's a very expensive operation.

**Comment by MHBauer** [comment]
we generate a new encryption key for each apiserver invocation during the integration tests. We should reuse the same key once we've generated it the first time.
