### ISSUE TITLE
Multiple ServiceInstance conditions with the same reason & message

### ISSUE THREAD

**Issue by luksa** [kubernetes-sigs/service-catalog#2063]
Did we really intend to have a resource have multiple conditions with the same reason and message (but different type), such as in this case:
```
  Conditions:
    Last Transition Time:  2018-05-23T05:55:21Z
    Message:               ClusterServiceBroker returned a failure for update call; update will not be retried: Status: 400; ErrorMessage: <nil>; Description: parameter not updatable; ResponseError: <nil>
    Reason:                UpdateInstanceCallFailed
    Status:                False
    Type:                  Ready
    Last Transition Time:  2018-05-23T05:55:21Z
    Message:               ClusterServiceBroker returned a failure for update call; update will not be retried: Status: 400; ErrorMessage: <nil>; Description: parameter not updatable; ResponseError: <nil>
    Reason:                UpdateInstanceCallFailed
    Status:                True
    Type:                  Failed
```

This might look confusing and unnecessary to the average user.

Note that `svcat` only prints the last condition in the array (it prints its type if the condition is true, otherwise it prints the reason). Not sure how safe that is when there are multiple conditions.

**Comment by zihantang-rh** [comment]
It's reasonable and usefull to add one more `important` conditions, such as `provisionSucceed` ,`updateInstanceSucceed` etc.
But it's very confusing to add the 1 more conditions for the same `Message` and `Reason`,  it looks more like a bug to users.
