### ISSUE TITLE
on travis, apt update disabled, do we to handle?

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2073]
I've started seeing the following message at the start of travis builds. I do not know if we need to do anything. Since we run everything in docker and do no apt installs in the base travis, I do not think there is any work here. 

```
Running apt-get update by default has been disabled.
You can opt into running apt-get update by setting this in your .travis.yml file:
  addons:
    apt:
      update: true
```

**Comment by carolynvs** [comment]
I don't think any changes are required for this due to how we run everything in our own build image. It's just a friendly message in the travis logs to help people out.
