### ISSUE TITLE
apiVersion not set when deploying on Kubernetes 1.10.1

### ISSUE THREAD

**Issue by anderssoder** [kubernetes-sigs/service-catalog#2081]
Hi, 

I've tried to install service catalog but got stuck because it fails with: "Kubectl apply failed. Error: error: error validating \"/tmp/app-template493729124\": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false\n: exit status 1"

Catalog template version 0.1.20
Kubernetes 1.10.1 
Deployed through Rancher 2 using Helm (from custom catalog https://svc-catalog-charts.storage.googleapis.com)

What is the problem here? 

Got this from Rancher slack "I think this has something to do with that API exiting beta in 1.10, and the templates not being updated to support that, so neither case is true and it has no version. "

    #catalog/templates/apiregistration.yaml
     ...
     {{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" }}
     apiVersion: apiregistration.k8s.io/v1beta1
     {{- else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" }}
     apiVersion: apiregistration.k8s.io/v1alpha1
     {{- end }}
      ...

**Comment by MHBauer** [comment]
@anderssoder can you run `kubectl api-versions` to confirm which APIs exist?

It would be very surprising to me if it the beta API was gone.

**Comment by anderssoder** [comment]
@MHBauer Here's the output:

    > kubectl api-versions 
    admissionregistration.k8s.io/v1beta1
    apiextensions.k8s.io/v1beta1
    apiregistration.k8s.io/v1
    apiregistration.k8s.io/v1beta1
    apps/v1
    apps/v1beta1
    apps/v1beta2
    authentication.k8s.io/v1
    authentication.k8s.io/v1beta1
    authorization.k8s.io/v1
    authorization.k8s.io/v1beta1
    autoscaling/v1
    autoscaling/v2beta1
    batch/v1
    batch/v1beta1
    certificates.k8s.io/v1beta1
    crd.projectcalico.org/v1
    events.k8s.io/v1beta1
    extensions/v1beta1
    networking.k8s.io/v1
    policy/v1beta1
    rbac.authorization.k8s.io/v1
    rbac.authorization.k8s.io/v1beta1
    storage.k8s.io/v1
    storage.k8s.io/v1beta1
    v1

**Comment by MHBauer** [comment]
Wrote a comment and forgot to post it, sorry.

I see the correct API in your output, so I do not think your proposed problem is the case here.

Nonetheless, we should add explicit support to the helm chart for the stable version of the API.

**Comment by MHBauer** [comment]
Can you post the intermediate contents of the template here?

I see `apiregistration.k8s.io/v1beta1`, so that is what should be used. I think it could be validation of some other type.

**Comment by anderssoder** [comment]
catalog/templates/apiregistration.yaml:

    {{- $ca := genCA "svc-cat-ca" 3650 }}
    {{- $cn := printf "%s-catalog-apiserver" .Release.Name }}
    {{- $altName1 := printf "%s-catalog-apiserver.%s" .Release.Name .Release.Namespace }}
    {{- $altName2 := printf "%s-catalog-apiserver.%s.svc" .Release.Name .Release.Namespace }}
    {{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
    {{- if .Values.useAggregator }}
    {{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" }}
    apiVersion: apiregistration.k8s.io/v1beta1
    {{- else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" }}
    apiVersion: apiregistration.k8s.io/v1alpha1
    {{- end }}
    kind: APIService
    metadata:
      name: v1beta1.servicecatalog.k8s.io
    spec:
      group: servicecatalog.k8s.io
      version: v1beta1
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "fullname" . }}-apiserver
      caBundle: {{ b64enc $ca.Cert }}
      {{ if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" -}}
      priority: {{ .Values.apiserver.aggregator.priority }}
      {{ else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" -}}
      groupPriorityMinimum: {{ .Values.apiserver.aggregator.groupPriorityMinimum }}
      versionPriority: {{ .Values.apiserver.aggregator.versionPriority }}
      {{- end }}
    {{ end }}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ template "fullname" . }}-apiserver-cert
      labels:
        app: {{ template "fullname" . }}-apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    type: Opaque
    data:
      tls.crt: {{ b64enc $cert.Cert }}
      tls.key: {{ b64enc $cert.Key }}
      {{- if .Values.apiserver.tls.requestHeaderCA }}
      requestheader-ca.crt: {{ .Values.apiserver.tls.requestHeaderCA }}
      {{- end }}

catalog/templates/apiserver-service.yaml:

    kind: Service
    apiVersion: v1
    metadata:
      name: {{ template "fullname" . }}-apiserver
      labels:
        app: {{ template "fullname" . }}-apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      type: {{ .Values.apiserver.service.type }}
      selector:
        app: {{ template "fullname" . }}-apiserver
      ports:
      - name: secure
        protocol: TCP
        port: 443
        targetPort: 8443
        {{- if eq .Values.apiserver.service.type "NodePort" }}
        nodePort: {{ .Values.apiserver.service.nodePort.securePort }}
        {{- end }}

catalog/templates/apiserver-deployment.yaml:

    kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: {{ template "fullname" . }}-apiserver
      labels:
        app: {{ template "fullname" . }}-apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ template "fullname" . }}-apiserver
      template:
        metadata:
          labels:
            app: {{ template "fullname" . }}-apiserver
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: "{{ .Release.Name }}"
            releaseRevision: "{{ .Release.Revision }}"
            heritage: "{{ .Release.Service }}"
        spec:
          serviceAccountName: "{{ .Values.apiserver.serviceAccount }}"
          containers:
          - name: apiserver
            image: {{ .Values.image }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            resources:
              requests:
                cpu: 100m
                memory: 20Mi
              limits:
                cpu: 100m
                memory: 30Mi
            args:
            - apiserver
            {{ if .Values.apiserver.audit.activated -}}
            - --audit-log-path
            - {{ .Values.apiserver.audit.logPath }}
            {{- end}}
            - --enable-admission-plugins
            - "KubernetesNamespaceLifecycle,DefaultServicePlan,ServiceBindingsLifecycle,ServicePlanChangeValidator,BrokerAuthSarCheck"
            - --secure-port
            - "8443"
            - --storage-type
            - {{ .Values.apiserver.storage.type }}
            {{- if eq .Values.apiserver.storage.type "etcd" }}
            - --etcd-servers
            - {{ .Values.apiserver.storage.etcd.servers }}
            {{- end }}
            - -v
            - "{{ .Values.apiserver.verbosity }}"
            {{- if .Values.apiserver.tls.requestHeaderCA }}
            - --requestheader-client-ca-file=/var/run/kubernetes-service-catalog/requestheader-ca.crt
            {{- end }}
            {{- if not .Values.apiserver.auth.enabled }}
            - --disable-auth
            {{- end }}
            {{- if .Values.originatingIdentityEnabled }}
            - --feature-gates
            - OriginatingIdentity=true
            {{- end }}
            {{- if .Values.namespacedServiceBrokerEnabled }}
            - --feature-gates
            - NamespacedServiceBroker=true
            {{- end }}
            {{- if .Values.apiserver.serveOpenAPISpec }}
            - --serve-openapi-spec
            {{- end }}
            ports:
            - containerPort: 8443
            volumeMounts:
            - name: apiserver-cert
              mountPath: /var/run/kubernetes-service-catalog
              readOnly: true
            readinessProbe:
              httpGet:
                port: 8443
                path: /healthz
                scheme: HTTPS
              failureThreshold: 1
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              httpGet:
                port: 8443
                path: /healthz
                scheme: HTTPS
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
          {{- if and (eq .Values.apiserver.storage.type "etcd") .Values.apiserver.storage.etcd.useEmbedded }}
          - name: etcd
            image: quay.io/coreos/etcd:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 100m
                memory: 30Mi
              limits:
                cpu: 100m
                memory: 40Mi
            env:
            - name: ETCD_DATA_DIR
              value: /etcd-data-dir
            command:
            - /usr/local/bin/etcd
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://localhost:2379
            ports:
            - containerPort: 2379
            volumeMounts:
            - name: etcd-data-dir
              mountPath: /etcd-data-dir
            readinessProbe:
              httpGet:
                port: 2379
                path: /health
              failureThreshold: 1
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              httpGet:
                port: 2379
                path: /health
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
          {{- end }}
          volumes:
          - name: apiserver-cert
            secret:
              secretName: {{ template "fullname" . }}-apiserver-cert
              items:
              - key: tls.crt
                path: apiserver.crt
              - key: tls.key
                path: apiserver.key
              {{- if .Values.apiserver.tls.requestHeaderCA }}
              - key: requestheader-ca.crt
                path: requestheader-ca.crt
              {{- end }}
          {{- if and (eq .Values.apiserver.storage.type "etcd") .Values.apiserver.storage.etcd.useEmbedded }}
          - name: etcd-data-dir
          {{- if .Values.apiserver.storage.etcd.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ .Values.apiserver.storage.etcd.persistence.existingClaim | default (printf "%s-%s" (include "fullname" .) "etcd") }}
          {{- else }}
            emptyDir: {}
          {{- end }}
          {{- end }}
