### ISSUE TITLE
Create user-defined plans in svcat

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2112]
This command copies an existing plan into a new user-defined plan. See https://github.com/kubernetes-incubator/service-catalog/pull/2190 as an example of how to implement this, as it is very similar (creating classes instead of plans).

```
$ svcat create plan NAME --from EXISTING_NAME [--cluster|--namespace]
```

* `NAME` - Required. The new plan name.
* `--from EXISTING_NAME` - Required. Name of an existing plan to copy.
* `--cluster` - Optional. Specifies that a cluster-scoped plan should be created. By default namespace-scoped plans are created. When this flag is set, namespace is ignored.
* `--namespace` - Optional. Overrides the current namespace to specify the namespace of the namespace-scoped plan.

See [proposal](https://github.com/carolynvs/service-catalog/blob/e204e8b0ac4ce1dddbef5fc3f17493cf1c52e664/docs/proposals/default-service-plans.md#define-a-new-set-of-defaults) for additional context. There will be an issue later to add support for default parameters, etc, so for now this command isn't terribly exciting. 😀

**Comment by shubheksha** [comment]
I would like to work on this!

**Comment by shubheksha** [comment]
I would like to work on this!
@carolynvs, would it make to split this into two PRs - one for cluster scoped plans and another one for namespace scoped plans - the way it was done for classes?

**Comment by carolynvs** [comment]
We split the other one into 2 PRs for cluster scoped vs namespace scoped only because at the time, the namespaced broker feature was incomplete. Going forward, any PR that affects brokers, plans or classes should address both scopes in the same PR.
