### ISSUE TITLE
Make svcat's uuid flag easier to use

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2144]
Instead of specifying how to interpret the value passed to `svcat get class X` or `svcat describe plan X` based on the presense of the `--uuid` boolean flag, that it would be more clear if instead, `--uuid` was a string flag that could be specified in place of the positional argument for the name.

e.g.

```
svcat get class NAME

svcat get class --uuid UUID

svcat describe class NAME

svcat describe class --uuid UUID 
```

This applies to the following commands:

* `svcat get class`
* `svcat get plan`
* `svcat describe class`
* `svcat describe plan`

* When the `--uuid` flag is set, then we don't attempt to retrieve a name from the positional arguments and instead use the value passed in the flag.
* For the `svcat describe` commands we will need to modify the Validate function's check for if either NAME or UUID is set.
* It is invalid to specify both `--uuid` and a positional argument to these commands, e.g. `svcat describe class NAME --uuid UUID` or `svcat get plan NAME --uuid UUID` should return an error from the Validate function.
* Instead of relying on the boolean `lookupByUUID`, we would check if `c.Name` is empty when deciding how to use the two values.

https://github.com/kubernetes-incubator/service-catalog/blob/284cd7234edc08eb168132c993acd3909552c990/cmd/svcat/class/get_cmd.go#L64-L71

The validation and command output tests should be modified in:

https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/svcat/svcat_test.go

**Comment by A-Hilaly** [comment]
Hey, i'd like to work on this, if possible !

**Comment by carolynvs** [comment]
I recommend only picking up one thing at a time when starting out. Once your other PR is merged (or at least is ready for someone to merge and you are just waiting for us), then that's a good time to pick up more issues.

**Comment by carolynvs** [comment]
@A-Hilaly heh, sorry to be all like "noooooo", then your PR immediately was merged. 😊 This one is all yours if you'd still like to work on it!

**Comment by A-Hilaly** [comment]
@carolynvs No worries, my mistake posting too fast 😄  ! i'll open a PR soon !
