### ISSUE TITLE
refactor kubeconfig loader into `pkg/util/kube`

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2183]
See https://github.com/kubernetes-incubator/service-catalog/pull/2158 for some history of this code.

Right now code in `pkg/svcat/` is relied upon by the apiserver and the e2e tests. It's not hurting anything as it is, but it could be put into a better place. 

Tasks for completing this issue:
 - [x] Move the code from `pkg/svcat/kube/kube.go` to  `pkg/util/kube/kube.go` and fixup all the imports. 
 - [ ] Bonus points for finding other uses of `go-client/tools/clientcmd` and making them use this common kubeconfig loader.

This is probably 2 serial PRs worth of work.

/good-first-issue

**Comment by Bubblemelon** [comment]
@MHBauer Hello. I'm interested in getting this done :smile:  

And you mean [`client-go/tree/tools/clientcmd` ](https://github.com/kubernetes/client-go/tree/master/tools/clientcmd) instead of `go-client` ?

**Comment by MHBauer** [comment]
@Bubblemelon go for it. you can have it. the clientcmd thing looks correct. I just wrote this off the top of my head.
Good Luck We're here to help.

**Comment by Bubblemelon** [comment]
@MHBauer for item 2 on the to do list.

**Comment by Bubblemelon** [comment]
Hello @MHBauer :smile: 

For clarity on item 2 in the to do list, are you suggesting to find other projects that might want to utilize `go-client`? Could you elaborate on this task?

**Comment by Bubblemelon** [comment]
CC: @carolynvs

**Comment by carolynvs** [comment]
Sorry I'm not quite sure what @MHBauer was hinting at with the second point?
