### ISSUE TITLE
Make e2e run on prow (was: jenkins stuck for a week - who has perms?)

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2184]
Jenkins seems stuck processing https://github.com/kubernetes-incubator/service-catalog/pull/2177#issuecomment-403530453 for the last week. No newer PRs have been handled.

https://service-catalog-jenkins.appspot.com/job/service-catalog-master-testing/

Is @kibbles-n-bytes the only person with permissions? Is the only solution here moving towards prow?

**Comment by carolynvs** [comment]
Closing - We don't use jenkins anymore.

**Comment by carolynvs** [comment]
Thanks for clarifying. Do you happen to know if they were explicitly turned off or if I should be investigating when they stopped running and why?

**Comment by MHBauer** [comment]
Only run by jenkins and not yet running in prow. Never made the transition.

**Comment by carolynvs** [comment]
I don't think that Jenkins instance exists anymore... 🤦‍♀️

**Comment by MHBauer** [comment]
maybe a new issue for @jeremyrickard ?

**Comment by MHBauer** [comment]
AI for a Campbell in October 1, 2018 sig meeting? I haven't watched it.

**Comment by MHBauer** [comment]
@jberkhahn

I think this is better served by having a discussion in the weekly
meeting about whether anybody still cares about running these tests at
all, and opening a new issue without the baggage this one has.

/close
