### ISSUE TITLE
look through our unit tests for table driven tests with named test cases and convert to use go testing subtests

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2185]
The go testing feature is described https://blog.golang.org/subtests

This feature allows exactly specifying a test to run, and nice output that shows exactly which test case is failing.

We have some of these already, for example https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.23/pkg/controller/controller_instance_test.go#L559-L560

Easy way to find examples where this is **already implemented** is to search for `t.Run(tc.name, func(t *testing.T) {` in the codebase.

Looking at #2170 we can see that there are places where we have table driven tests, and each case has a name, but the tests aren't run as a subtest. 
In this case it requires creating the subtests as well as possibly changing the code in the checks being done (the `continue` wouldn't work anymore as the scope of the subtest function would not be in the outer for loop).

This is less a service-catalog issue than a code-quality or learning-golang issue, but I think this makes it a low-risk change for a new contributor to make.

/good-first-issue

**Comment by jichenjc** [comment]
I will try to work on that
