### ISSUE TITLE
Prototype Moving Service Catalog to CRD

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes-sigs/service-catalog#2191]
CRDs are at a point where it makes sense to prototype what it looks like to migrate Service Catalog from using an Aggregated API server toward using CRDs. We should do a prototype of this transition and review it with the larger SIG group. 

List of things missing from CRDs that are provided by aggregated APIServer Implementation: 
 - custom sub-resources
 - custom field selectors

**Comment by carolynvs** [comment]
/cc @n3wscott 

He already had a prototype a while back, k8s has revved since then but he may have some pointers or patches we can start off from.

**Comment by MHBauer** [comment]
#2059 handles this exact scenario

**Comment by jeremyrickard** [comment]
@MHBauer I was going to start prototyping:

>Native CRD model, would eliminate the need for the APIServer at all, and would mean that the Controller natively speaks CRD rather than our existing objects. 

I wasn't going to tackle doing a migration, just what an implementation using only CRD and related CRD-speaking controller(s) might look like. I'm happy to close this and use the other to track it. Ya'll can make the call :)

**Comment by MHBauer** [comment]
Ya, I would hook up with @n3wscott

**Comment by jeremyrickard** [comment]
@MHBauer @carolynvs I'll synch up with @n3wscott on the k8s slack! Thanks for the tip!

**Comment by MHBauer** [comment]
Further, my interpretation of conversation at the F2F is that this is the only thing we want to even try. 

No CRD backed storage in any way.

Included in this may be some necessary API changes if we do decide to drop APIServer.

**Comment by tamalsaha** [comment]
Is there any update on this issue?

**Comment by carolynvs** [comment]
Nope, I think this fell off the radar as people had other commitments. It is still something that we would like to do though.

**Comment by vlerenc** [comment]
CRD backend or completely switching to controller-only (dropping the api server extension), would be much appreciated as carrying around an additional etcd (if, like in many cases, you can't piggy-back on the main etcd of your cluster) is quite painful.

Has anybody tried to run the service catalog with CRDs and without the api server extension? Registry code like [usage of this non-`status`/`scale` sub resource](https://github.com/kubernetes-incubator/service-catalog/blob/c9c3dfa95d93f277394de1411fe4a16862a90082/pkg/registry/servicecatalog/rest/storage_servicecatalog.go#L174) seems to indicate that it would not work out of the box, right?

**Comment by MHBauer** [comment]
@vlerenc exactly so wrt to the subresource usage. We can move forward when such support exists, or when there is agreement on API changes that require V2.

**Comment by mvladev** [comment]
@MHBauer @vlerenc another thing I noticed is that custom [fieldSelectors](https://github.com/kubernetes-incubator/service-catalog/blob/c9c3dfa95d93f277394de1411fe4a16862a90082/pkg/registry/servicecatalog/instance/storage.go#L97) are used.

I often attend `api-machinery` meetings and so far there is no planned way to expose those custom `fieldSelectors` via `CRDs`.

**Comment by MHBauer** [comment]
I feel like we may have had a list at a face-to-face meeting of "features we use that are unsupported by CRD". Not sure if it's made it into an issue somewhere, but we should find it or start one.

 - custom sub-resources
 - custom field selectors

**Comment by luksa** [comment]
FYI: features that aren't supported by CRDs are just one part of the problem. Also be aware that the Service Catalog API server handles some things differently than the core k8s API server. 

For example, as a first step during provisioning, the Service Catalog controller updates the references in the ServiceInstance's spec. The Service Catalog API server does NOT increase the `metadata.generation` field, whereas the core API server will. This may affect the controller's operation further on, and it may affect some clients.

**Comment by tamalsaha** [comment]
cc: @sttts @nikhita

**Comment by baikai** [comment]
Hi guys, any progress about this issue?  Or still blocked by "custom sub-resources" and "custom field selectors"?
