### ISSUE TITLE
We should allow the helm chart to be "released" independently of the service catalog release

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes-sigs/service-catalog#2195]
We currently pin the version of the helm chart to the version of service catalog:

```
name: catalog
description: service-catalog API server and controller-manager helm chart
version: 0.1.24
```
The version string gets updated when the release happens.  When issues like #2193 occur, this means the Chart remains broken until we do a new release. 

Helm allows you to specify both a Chart version (`version`) and the version of the associated application (`appVersion`).

I propose that we introduce an `appVersion` property to the Chart.yaml that is pinned to the version of service catalog, and then use the Chart's `version` to enable us to release the chart in response to bugs like #2193.

**Comment by MHBauer** [comment]
right now the chart release is tied to creating a tag.

we'll have to adjust this logic for this to be possible.
