### ISSUE TITLE
Why do we send namespace.UID ? Consider changing directly to namespace.

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2221]
As part of https://github.com/kubernetes-incubator/service-catalog/pull/577 we send the `UID` of the kubernetes namespace. As far as I understand, UID is not meant to be interacted with in any external or user way. I believe it is for internal kube use only and possibly an artifact of etcd or storage for that layers use. 

For a user to use this they currently have to iterate through all of the namespaces and do a compare.
```
    namespaceList, _ := clientset.CoreV1().Namespaces().List(meta_v1.ListOptions{})

    for _, namespace := range namespaceList.Items {
        if string(namespace.ObjectMeta.UID) == namespaceID {
            return namespace.ObjectMeta.Name, nil
        }
    }
```
Not sure if UID is list selectorable or field selectorable, but in either case, it is not how a user should look up a namespace.

I think we should send something more directly useful for the user. I cannot think of a way to warn the user to use the context-profile object instead, so sending the namespace directly is what I propose.

**Comment by duglin** [comment]
The should be using org and space GUID they should be used the namespace in the context object. We even say so in the spec.  Putting a non GUID in a field called GUID will be kind of weird.

**Comment by carolynvs** [comment]
> The should be using org and space GUID they should be used the namespace in the context object. We even say so in the spec. Putting a non GUID in a field called GUID will be kind of weird.

@duglin I don't understand your comment above?

From a pure k8s perspective, people shouldn't be using the resource uid directly, and we should be giving them the name instead. So my vote is +1 for this issue.

**Comment by duglin** [comment]
@carolynvs Sorry -  I fixed the typos.  People should not be using the org/space fields from the normal message body, they should be using the values in the context property. The org/space fields are deprecated in favor of the context ones. 

As for what to put in these "deprecated" fields... for the most part it doesn't matter since people should not be looking at them, especially if they're a Kube broker, which means they're new.  However, since these fields are "GUIDs" (and not just strings) it would be really odd to not put some variant of a GUID in there (UUID is close enough).

**Comment by carolynvs** [comment]
OH! I'm glad you clarified that makes much more sense. 😀

**Comment by MHBauer** [comment]
The fields are specified as "MUST be a non-empty string". The name of the field implies guid, but nothing in the spec requires any particular format.

**Comment by MHBauer** [comment]
We should place a link to https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/profile.md#kubernetes-context-object in the source code where people may see the ns.id and think to do a lookup based upon it.

**Comment by MHBauer** [comment]
created https://github.com/pmorie/go-open-service-broker-client/issues/127 for users of that client

**Comment by MHBauer** [comment]
I think @carolynvs said someone had docs on this, and I think it was @jeremyrickard so
/assign @carolynvs @jeremyrickard 
to watch over that half of the process.

**Comment by carolynvs** [comment]
Yup! I have it on my plate to make a follow-on issue for the docs to create a section for people developing brokers that work well with k8s.
