### ISSUE TITLE
Add section to our site for people writing brokers

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2233]
We should add a section to the docs homepage with information for people writing brokers

* Best practices about what info we stuff into the context https://github.com/kubernetes-incubator/service-catalog/issues/2221.
* Pointers to the osb-starter-pack, and the server/client libs.
* Link to osbkit, and minibroker as examples

**Comment by jeremyrickard** [comment]
Should we limit this to osb-starter-pack and server/client libs? I think for Go these are probably the best. Should we include other languages (i.e. Pivotal has this via Spring https://github.com/spring-cloud/spring-cloud-open-service-broker)

**Comment by MHBauer** [comment]
#1678
