### ISSUE TITLE
charter should use a better voting method

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/service-catalog#2246]
Currently among maintainers it's 50% majority. This is fine for topics with only two choices. When there are multiple choices we should use a form of ranked voting. I propose the use of https://civs.cs.cornell.edu/ with the same configuration that core kubernetes uses.

**Comment by jboyd01** [comment]
Even with a majority vote, it would be beneficial to use a voting website.  There are a lot of free polling/survey apps out there that would make this easier and clearer.  I imagine we'd want to lock it down voting by email address, something that the SIG doesn't collect/expose AFAIK.
