### ISSUE TITLE
Don't try to create new objects in namespace that is being deleted

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#2249]
# Bug Report 

**What happened**:
When namespace containing ServiceInstance is deleted, there are errors of creating Event object:
> E0731  20:25:56.313318       1 event.go:200] Server rejected event  '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""},  ObjectMeta:v1.ObjectMeta{Name:"ups.15468de94c332c2b", GenerateName:"",  Namespace:"voyager-monitor", SelfLink:"", UID:"", ResourceVersion:"",  Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0,  loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil),  DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil),  Annotations:map[string]string(nil),  OwnerReferences:[]v1.OwnerReference(nil),  Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil),  ClusterName:""},  InvolvedObject:v1.ObjectReference{Kind:"ServiceInstance",  Namespace:"voyager-monitor", Name:"ups",  UID:"d2d16c1f-94ff-11e8-9259-76123ff8af63",  APIVersion:"servicecatalog.k8s.io", ResourceVersion:"17049524",  FieldPath:""}, Reason:"DeprovisionedSuccessfully", Message:"The instance  was deprovisioned successfully",  Source:v1.EventSource{Component:"service-catalog-controller-manager",  Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbed04f551291e42b,  ext:658615306114792, loc:(*time.Location)(0x34d9780)}},  LastTimestamp:v1.Time{Time:time.Time{wall:0xbed04f551291e42b,  ext:658615306114792, loc:(*time.Location)(0x34d9780)}}, Count:1,  Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0,  loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"",  Related:(*v1.ObjectReference)(nil), ReportingController:"",  ReportingInstance:""}': 'events "ups.15468de94c332c2b" is forbidden:  unable to create new content in namespace voyager-monitor because it is  being terminated' (will not retry!) 

**What you expected to happen**:
Namespace deletion should be handled with no errors. When namespace is marked for deletion, you cannot create any new objects in it.

**How to reproduce it (as minimally and precisely as possible)**:
Provision a UPS ServiceInstance, then delete the namespace. See the logs.

**Comment by MHBauer** [comment]
Where should we be creating these? It seems like if this fails, then we should be creating all events that are currently in a namespace somewhere else.

**Comment by nilebox** [comment]
Agreed, we may use some dedicated fallback namespace for events, e.g. namespace where Service Catalog itself is deployed.
