### ISSUE TITLE
Add support for safe migration (import/export)

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#2250]
We would like Service Catalog to support a "safe migration" (import/export) for `ServiceInstance` objects from other services (it could be another instance of Service Catalog, or Cloud Foundry, or any other implementation of OSB marketplace).

**What does "safe migration" mean?**
Ideally we would like to initially create a ServiceInstance with some `migrationMode: true` flag in its spec that guarantees that the `ServiceInstance` spec and its parameters are validated against actual OSB broker, but there are no side effects (mutations) to the actual provisioned resources as a result of sending OSB requests. In other words, it's a kind of "validation dry-run" mode.

**Problems with creation of ServiceInstance the normal way**
We can already create a ServiceInstance with existing `externalID` set and parameters that are in sync with the existing instance. In that case the provisioning should end with no-op provisioning on the broker side (which should simply return `200 OK`). While this works for "happy path", things could go wrong:
- Orphan mitigation is triggered in case of any 5xx error returned by broker, or even request timeout. See #2242
- If user decides to migrate back from Service Catalog to the previous system, the obvious step to do is delete a ServiceInstance. This will lead to deprovisioning
- If the instance was not found by broker, a new one will be provisioned instead

**Call for proposals**
We don't have a final design yet, only some initial ideas. We would be interested to learn if any other party is interested in solving similar use cases. If it is already solved, please share your story and suggestions.

---
**Example user story**

1. User (or a migration tool) creates a `ServiceInstance` object with user-provided `externalID` referring to existing instance, `migrationMode: true` and the spec and parameters in-sync with the provisioned instance.
2. Service Catalog performs a validation of the spec and parameters. Options are:
  **a.** Reusing current OSB spec endpoints (not exactly "safe")
- Service Catalog fetches information from the broker via `GET instance` request (if broker supports this optional endpoint), and compares it with the information provided in `ServiceInstance`
- Service Catalog sends a provisioning request that should result in `200 OK` if all information is in sync with the actual resource

  **b.** Extending OSB spec
- We introduce a new "validate instance" endpoint into OSB API; Service Catalog will send a request to this endpoint, which includes the same data as it would normally send in a provision request, but it is guaranteed to have no side effects ("dry run"), and broker responds whether parameters are in sync with the existing instance.
3. Once the validation succeeded (`ServiceInstance` status has `Ready: true` condition set), we can turn off the "safe migration" mode.
4. If `ServiceInstance` is marked for deletion and `migrationMode: true` is still set, no deprovisioning request will be sent by Service Catalog as part of deletion.

**Comment by duglin** [comment]
I've wondered what the usecases are for people setting `spec.externalID` - that ID really should just be for internal use. And if we did that, could we use that as the flag for migration instead of introducing a new one?

**Comment by nilebox** [comment]
@duglin yes, we only allow users to set `spec.externalID` (actually we've internally developed additional admission webhook that validates that another system does have an OSB instance with this ID, and that the user owns it, when custom `spec.externalID` is set by user).

We don't need a flag for migration forever though. Once the migration is done and we disabled or deleted the instance from the other system, we want to under the migration flag and operate on the imported instance the same way as on the new ones.

**Comment by ash2k** [comment]
Also related to controlling ability to set external id https://github.com/kubernetes-incubator/service-catalog/issues/1928
