### ISSUE TITLE
Add command to update parameters on an instance

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2321]
@NickyMateev suggested that we support updating the parameters on an instance, so that people don't need to fall back to kubectl.

> The way to do it right now is I have to derive the provisioned instance's .yml file manually and then update it's spec, apply the resource and then touch the instance.

I propose that we add a new command that is similar to a command from kubectl, [set](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#set). This will give us a way to update a particular value on the instance, without jump dumping them into the yaml (like with kubectl edit).

 ```
$ svcat set instance --help
Usage: svcat set instance NAME [flags]

-p, --param strings        Additional parameter to use when provisioning the service, format: NAME=VALUE. Cannot be combined with --params-json, Sensitive information should be placed in a secret and specified with --secret
      --params-json string   Additional parameters to use when provisioning the service, provided as a JSON object. Cannot be combined with --param
      --plan string          The plan name (Required)
  -s, --secret strings       Additional parameter, whose value is stored in a secret, to use when provisioning the service, format: SECRET[KEY]
```

* We can use the same parameter and secret flags from `svcat provision`.
* After the value are set on the instance, svcat should also perform the logic from [`svcat touch instance NAME`](https://github.com/kubernetes-incubator/service-catalog/blob/2976a28522b16413acb88051d6f8fd033f956a17/cmd/svcat/instance/touch_cmd.go#L60).
* See the [Service Plan Defaults Proposal](https://github.com/kubernetes-incubator/service-catalog/blob/e204e8b0ac4ce1dddbef5fc3f17493cf1c52e664/docs/proposals/default-service-plans.md#modify-existing-defaults) for an example of how I think we can tie this into other commands we plan on adding in the next few weeks.
* The logic for the command should live in pkg/svcat/servicecatalog, and the code in cmd/svcat/instance.
* This should have unit tests similar to the pattern from the [`svcat broker register` tests](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/svcat/service-catalog/broker_test.go).

**Comment by NickyMateev** [comment]
#dibs
