### ISSUE TITLE
Add DefaultBindParameters to classes

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2349]
This is a follow-up to https://github.com/kubernetes-incubator/service-catalog/issues/2348. Once that is completed, use it as an example of of how to implement and test this related feature. It should add DefaultBindParameters to classes, on the CommonServiceClassSpec, and combine the class level params with the plan level params and the binding params.

This allows an operator to define defaults at the class level, tweak it at the plan level, and then a developer can use them (or override them) when they create a ServiceBinding for that class+plan.

See the proposal for additional context and details: https://github.com/carolynvs/service-catalog/blob/default-service-plan-proposal/docs/proposals/default-service-plans.md#binding-with-defaults. The scope of this issue is only the changes to the resource definitions and the controller, not svcat.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
