### ISSUE TITLE
Umbrella issue to track issues in user-defined namespaced plans implementation

### ISSUE THREAD

**Issue by shubheksha** [kubernetes-sigs/service-catalog#2357]
- Update [command description](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/svcat/class/create_cmd.go#L44) to include support from namespaced class, not just cluster-scoped classes
- Use `WriteClassDetails` instead of `WriteClassList` for [writing the output](https://github.com/kubernetes-incubator/service-catalog/commit/395f5d42c39cfe851503bfe39655212c5fe5e9b8#diff-1301055dc198abae8cada6625b31a477R87)
- The [flags](https://github.com/kubernetes-incubator/service-catalog/commit/395f5d42c39cfe851503bfe39655212c5fe5e9b8#diff-1301055dc198abae8cada6625b31a477R57) passed to `AddNamespaceFlags()` and `AddScopeFlags()` need to be false instead of true. See https://github.com/kubernetes-incubator/service-catalog/pull/2353#discussion_r220364615
- Update tests if needed

**Comment by shubheksha** [comment]
Ref #2269

**Comment by jberkhahn** [comment]
taking this off the namespaced resources milestone as this is no longer a priority

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
