### ISSUE TITLE
svcat version returns the k8s version, not the Service Catalog API version

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2385]
```
$ svcat version
Client Version: UNKNOWN
Server Version: v1.9.6
```

`v1.9.6` is the version of k8s that I'm running, not the version of service catalog.

I've tried a few endpoints and can't figure out if our aggregated api even exposes a /version endpoint. So this fix may require more work on the server.

```
// example of how to manually hit any path you like
func (sdk *SDK) ServerVersion() (*version.Info, error) {
	body, err := sdk.ServiceCatalog().RESTClient().Get().AbsPath("/apis/servicecatalog.k8s.io/version").Do().Raw()
	if err != nil {
		return nil, err
	}
	var info version.Info
	err = json.Unmarshal(body, &info)
	if err != nil {
		return nil, fmt.Errorf("got '%s': %v", string(body), err)
	}
	return &info, nil
}

// example of how to retrieve a path under our aggregated api
func (sdk *SDK) ServerVersion() (*version.Info, error) {
	body, err := sdk.ServiceCatalog().RESTClient().Get().Name("version").Do().Raw()
	...
}

```

Here's the code in question:

https://github.com/kubernetes-incubator/service-catalog/blob/d297cedebd9b762598e569a797ad6b44b4e0ccb7/pkg/svcat/service-catalog/version.go#L26-L33

**Comment by jboyd01** [comment]
To my knowledge and looking I don't think we expose an endpoint with the catalog version.  I just tried adding one and it seems to work along with the RBAC changes...  Did you have thoughts on a good URL?  /version is taken/handled by the core apiserver framework we're using so I think we'll need something else.  /service-catalog-version or /svcat-version ?
