### ISSUE TITLE
Change default log level for informational messages

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#2415]
Our default log level for information messages (such as processing a service instance) is 4. Which unfortunately also then includes **all** HTTP request/response payloads (not just failed ones). It makes it very difficult to work through our logs and troubleshoot.

It would be much easier if we could put infrequent informational messages, such as when we create a binding, inject a secret, etc at a lower number, such as 2, so that an operator can opt into just our informational messages, and only see the failed HTTP responses. Anything that's happening in a spin loop (like waiting for a resource to not exist, continue to be at a higher log level).

* I recommend that be the default log level, instead of 10, which is a total firehose and incredibly chatty.
* I also recommend that we stop hard coding 2's, 4's and 5's etc when we use glog.V(X) and instead use a constant so that it's easier to change this in the future without touching every file in the codebase. 😀 

Here's an example of the type of code that I'd like to see improved. It's all through the codebase unfortunately.

https://github.com/kubernetes-incubator/service-catalog/blob/f9bd009439a5e6e44d988221ff9ee8ba3bb1806d/cmd/apiserver/app/server/run_server.go#L50

**Comment by jboyd01** [comment]
+1!
Logs are way to noisy for general use with the current default config.  I like the idea of moving to constants (INFO/WARN/ERROR/TRACE).  Initially this sounds like a large task, but doing some greps I don't think it's going to be that bad of a task and it has some pretty good bang for the buck in terms of serviceability.

**Comment by Zyqsempai** [comment]
I can take this one.

**Comment by Zyqsempai** [comment]
Do we have some kind of doc or guide for verbosity level?
Coz we have variosity from 1 to 10, and actually I don't see any logic in the way many of them are used.
here for example are log level from syslog:
0 - Emergency (emerg)
1 - Alerts (alert)
2 - Critical (crit)
3 - Errors (err)
4 - Warnings (warn)
5 - Notification (notice)
6 - Information (info)
7 - Debug (debug)

Dow we have something like this?

**Comment by carolynvs** [comment]
Sadly no, it's not standardized... For the most part, people have copied/pasted previous logs and reused levels that seemed similar. So if you want to do a couple PRs, one that just keeps all the levels the same, but puts in constants, then another that starts to make them more consistent, another to document the levels, then another that uses defaults or named functions , or something along those lines, that would be most welcome!

**Comment by Zyqsempai** [comment]
@carolynvs Sounds reasonable, I will be glad to work on it. But i suppose that we need to make some decission.
Which levels we will use(the range)
The scope for each range.
Thats important at least for constant naming;)

**Comment by jboyd01** [comment]
I am on board with making changes here, but I don't think changing from 
	`glog.V(4).Infoln("Preparing to run API server")`
to
	`glog.V(common.FourthLogLevel).Infoln("Preparing to run API server")`
is beneficial.

I'd like to see us use some constants such as DEBUG, TRACE, INFO, WARN, ERROR

I think we probably need to have some discussion on naming, I've posted it for Monday's SIG meeting https://docs.google.com/document/d/17xlpkoEbPR5M6P5VDzNx17q6-IPFxKyebEekCGYiIKM

Let's try to come up with some solid naming before moving this forward.
/hold

**Comment by jboyd01** [comment]
meant to put the old on the pr, not the issue.
/hold remove

**Comment by carolynvs** [comment]
Hey @Zyqsempai, in our SIG meeting today we learned that Kubernetes has moved to a better logging solution that glog. https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md

So instead of fixing our use of glog, we voted to move over to klog which should take care of the problems raised in this issue.

**Comment by Zyqsempai** [comment]
@carolynvs Glad to hear it, it looks like more appropriate solution. I would love to work on it, but as far as i can see, we should anyway provide constants for `klog.Infof()` five levels?

**Comment by carolynvs** [comment]
Yeah, constants for the info levels may be needed. Let's make sure that they are named after how to use them, e.g. "LevelTrace" or something like that.

**Comment by Zyqsempai** [comment]
Opened new PR.

**Comment by MHBauer** [comment]
lol the file already moved
https://git.k8s.io/community/contributors/devel/sig-instrumentation/logging.md

**Comment by MHBauer** [comment]
Upstream suggests a default level of 2. I know the chart is configured at a much higher number.
I do not know what log info level without a V() call is.
I do not know what the breakdown of our usage of V() is within this codebase.
Any constant package should link to the upstream guidance.
I disagree that the log levels need constants.
I agree that we could probably go through and consistence-ize our log levels as they are, but I have no guidance beyond the upstream logging guidance.
