### ISSUE TITLE
Enable to unregister service broker

### ISSUE THREAD

**Issue by sarlaccpit** [kubernetes-sigs/service-catalog#2466]
# Bug Report 

**What happened**:

After a service broker is successfully registered with the service catalog, with a related secret containing credentials needed to talk to the it, the following problem occurs after deleting the broker resource:  the broker resource is stuck in error state `ErrorFetchingCatalog` and cannot be cleaned up.

This happens when a chart, containing the clusterservicebroker and its related secret get deleted. Depending on timing, the secret gets deleted first; causing the broker to no longer be connectable because the secret resource is gone.   When in that state, nothing can remove the resource which stays stuck in `ErrorFetchingCatalog` state.

Attemped to manually delete the clusterservicebroker resource with kubectl, with -force and graceperiod flags, attempted with `svat deregister`.  Tried to force a sync with `svcat sync broker` but the resource remains.

Only workaround is to uninstall the service catalog completely and reinstall, which cleans up the resource since the service catalog is the finalizer for the clusterservicecluster resources.

Important note:  if care is taken such that the clusterservicecluster is removed first, THEN the secret it depends on, there are no problems and the resource gets cleaned up immediately.  So it is something related to the error condition that the resource is in when it is being deleted.

**What you expected to happen**:

I expected that the service catalog would eventually remove the clusterservicebroker resource I had created regardless of the sync error state it was in.

**How to reproduce it (as minimally and precisely as possible)**:

With a basic service broker deployment, a secret containing credentials to talk to it, a clusterservicebroker resource pointing to it.     Manually delete the secret.  Observe the expected sync error after an svcat sync.   Attempt to delete/unregister the clusterservicebroker resource.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

1.10.5.

- service-catalog version:

0.1.35.

- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?

Service catalog was installed with: `helm install svc-cat/catalog --name catalog --namespace catalog --version 0.1.35`

- Are you trying to use ALPHA features? Did you enable them?

**Comment by jboyd01** [comment]
That is a nasty problem.  I believe this is probably working as designed though - Service Catalog is attempting to prevent "orphaning" any resources that may have been allocated through the broker.  In some scenarios users are charged for Service Instances and/or Service Bindings that are created by the Broker.  If Service Catalog can't successfully de-register the Broker it can't be certain all associated resources will also be freed.

I believe that if you edit the the broker resource (ie  kubectl edit ClusterServiceBroker _broker-name_) and locate the finalizers:
```
  finalizers:
  - kubernetes-incubator/service-catalog
```
and delete the line that says kubernetes-incubator/service-catalog & then save the resource it will be cleanly deleted.  You may need to ensure you don't have other resources from the broker left around.    Although if you want to keep  any allocated resources and just delete and re-create the Broker, I believe you can do that and once the Broker is re-created everything will be happy.

We have a enhancement request that should help in this scenario: https://github.com/kubernetes-incubator/service-catalog/issues/2268

**Comment by sarlaccpit** [comment]
Thank you.  This makes sense.   Will track #2268.
