### ISSUE TITLE
Registering a broker requires a secret

### ISSUE THREAD

**Issue by duglin** [kubernetes-sigs/service-catalog#2478]
```
$ ./svcat register testbroker --url "http://192.168.59.147" 
  Name:     testbroker             
  URL:      http://192.168.59.147  
  Status:                          

$ ./svcat register testbroker1 --url "http://192.168.59.147" --scope cluster
Error: register request failed (ClusterServiceBroker.servicecatalog.k8s.io "testbroker1" is invalid: spec.authInfo: Required value: auth config is required)
```

Notice that I can register a broker in a namespace w/o a user/password (secret) but in the cluster scoped case I can not - it requires a secret.

We should at least be consistent between cluster and NS brokers, but registering a broker should not require a auth since there are some environment in which things are trusted and so that level of security is not needed. In short, let the broker decide if it wants security or not.

While I get this error while running svcat, I'm pretty sure this is a svc-cat issue, not an svcat one.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
