### ISSUE TITLE
svcat: support user/password on the cmd line

### ISSUE THREAD

**Issue by duglin** [kubernetes-sigs/service-catalog#2479]
IMO svcat is about making life easier for end users, and in many cases that means allowing them to skip being exposed to the kube resource model (and yaml) for as much as possible. Registering a broker should make life easier for them by allowing them to (optionally) specify a user and password on the cmd line. svcat can then create the secret for them before it lets the rest of svc-cat do its job.

It should still support a reference to a secret as well though.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
