### ISSUE TITLE
Multiple OSBAPI bind() calls for a single `svcat bind` call

### ISSUE THREAD

**Issue by duglin** [kubernetes-sigs/service-catalog#2481]
I'm seeing cases where a single call to `svcat bind` results in more than one OSBAPI call to the Bind() API. I can't tell for sure it they're all being done in parallel or one right after the other really quickly though.

So, first question... is this expected? I wouldn't think so. And to produce it all I do is:
```
svcat provision mydb --plan free --class demodb
svcat bind mydb
```
And then clean-up and try again. It doesn't happen all the time, but eventually it does do it for me.

Second thing, if the broker rejects the subsequent bind() calls with something like a `409 Conflict` error then everything is ok. Service-Catalog does appear to pick-up the one non-error response and uses those creds.

However, if the broker chooses to accept the 2nd+ bind() calls and returns an empty set of credentials (which it's allowed to do), then I've noticed that sometimes the resulting secret will be empty w.r.t its data/credentials.  I can't tell for sure if this is because the 2nd bind() response is received before the 1st response and 1st wins, or if the 2nd response is overriding the secret. Either way, I'm left in a state with a valid binding from svc-cat's POV, but no creds in the secret so its unusable.

**Comment by luksa** [comment]
I'm working on a fix that should solve these kinds of problems. I'll see if I can reproduce your scenario. 

Just one question: in your case, are the provision & bind operations asynchronous?

**Comment by duglin** [comment]
Nope - they're synchronous.
-Doug
