### ISSUE TITLE
Enable the Informer's cacheMutationDetector during tests

### ISSUE THREAD

**Issue by luksa** [kubernetes-sigs/service-catalog#2487]
We should enable the k8s client-go's cache mutation detector during tests. 

See https://github.com/kubernetes/kubernetes/blob/07ba609b50d6f00c52acbfd6eaa43e6b527c5c2d/staging/src/k8s.io/client-go/tools/cache/mutation_detector.go#L59-L74

**Comment by wayilau** [comment]
#dibs

**Comment by nzoueidi** [comment]
Hey @wayilau are you still working on this? If not, I would like to take it.
