### ISSUE TITLE
service catalog doesn't send 'previous_values' field in update service instance request body

### ISSUE THREAD

**Issue by jayeshjk** [kubernetes-sigs/service-catalog#2524]
# Bug Report 

**What happened**:
* According to OSB API Spec [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#updating-a-service-instance), update service instance request body can contain 'previous_values' field which is used by some brokers to validate the update request. For example, service-fabrik-broker uses this field as seen [here](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/rel-2018.T12a/api-controllers/ServiceBrokerApiController.js#L144).

* The 'previous_values' field is essential in the cases where plan upgrades need to be restricted.

**How to reproduce it (as minimally and precisely as possible)**:
* Update service plan for the existing service instance and check the patch request coming to broker.
 
**Environment**:
- Kubernetes version : 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
``` 
- service-catalog version: 
```
Client Version: v0.1.38
Server Version: v1.10.0
```

**Comment by ashishjain14** [comment]
Hi, Any updates on this?
