### ISSUE TITLE
FR: Can name of ServiceInstance be passed via ProvisionRequest context?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/service-catalog#2532]
We are implementing a service broker for our CRDs. We see that name of ServiceInstance is not passed to ProvisionRequest. xref:  https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L2251 .

Is it possible to pass the name of the ServiceInstance via request to the service broker so that we can use the same name for our CRD?

**Comment by jberkhahn** [comment]
this will soon become possible per [this PR is the OSB API](https://github.com/openservicebrokerapi/servicebroker/pull/671)
