### ISSUE TITLE
svcat param-json should support json file as an argument

### ISSUE THREAD

**Issue by prashant182** [kubernetes-sigs/service-catalog#2543]
# Feature request

**What happened**: 
`svcat provision id --plan default --class default --params-json file.json`

**What you expected to happen**:
we have a usecase where huge number of parameters needs to be passed for plan override and some other purpose, now we can accomodate that using `--params-json`, but quickly goes out of hand as the command size grows. Instead it would be nice to have a file support where we can pass the json argument from file rather than simply copy-pasting it in the terminal itself.

**How to reproduce it (as minimally and precisely as possible)**:
Just try to pass a file as `--params-json` value and command will complain saying 
``` 
Error: invalid --params-json value (invalid parameters (params.json))
``` 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version:
```
sc version 0.1.1 darwin/amd64
```
- Cloud provider or hardware configuration:
```
Kubernetes based on Docker for Desktop, Running on a MacOS.
```
- Did you use helm? What were the helm arguments? Did you `--set` any extra values?
```
Yes I did use helm to install my service broker, but no problems from that side
```

**Comment by baikai** [comment]
Hi @prashant182,  do you mean the --params-json need to accept both json string and json file?
I noticed that the description of  "--params-json" option is "--params-json string   Additional parameters to use when provisioning the service, provided as a JSON object.",  by design this option can only support json object/string.  So I think is not a bug, it's a feature enhancements or add a new option like "--params-string-file".

**Comment by prashant182** [comment]
Yes: I agree with you I think it should be more of a feature request than a bug. Is this something you guys be willing to work on? We deal with svcat daily and we want to pass a big chunk of params to the instance object. It would be great to have both Yaml and Json based file support to read params.

**Comment by baikai** [comment]
@prashant182  I'm working on this, and will support json format first.  We can continue to deal with the feature in this issue.
