### ISSUE TITLE
etcd connection test is testing cluster etcd urls not etcd specified by --etcd-servers

### ISSUE THREAD

**Issue by j00p34** [kubernetes-sigs/service-catalog#2554]
# Bug Report 

**What happened**:

health check failed due to etcd connection test failing

**What you expected to happen**:

Health check succeeds as etcd servers configured are available. Disabling the health check makes service catalog work. 

**How to reproduce it (as minimally and precisely as possible)**:

Run service catalog on EKS, where cluster etcd is not available on the nodes. Install etcd cluster on the nodes and configure service catalog to connect to this etcd cluster. Without health checks the catalog will become available. 

**Anything else we need to know?**:

https://github.com/kubernetes-incubator/service-catalog/blob/22232bd0a46e7c3e2762956defffda58efec6a4d/cmd/apiserver/app/server/run_server.go#L135

https://github.com/kubernetes-incubator/service-catalog/blob/22232bd0a46e7c3e2762956defffda58efec6a4d/cmd/apiserver/app/server/run_server.go#L103-L105

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- service-catalog version:
quay.io/kubernetes-service-catalog/service-catalog:v0.1.39
- Cloud provider or hardware configuration:
AWS EKS
- Do you have api aggregation enabled? yes
  - Do you see the configmap in kube-system? yes
  - Does it have all the necessary fields? yes
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?

```
  set {
    name  = "apiserver.storage.etcd.useEmbedded"
    value = "false"
  }

  set {
    name  = "apiserver.storage.etcd.servers"
    value = "etcd.aws-sb.svc.cluster.local:2379"
  }

  set {
    name  = "apiserver.replicas"
    value = "3"
  }

  set {
    name  = "apiserver.resources.limits.memory"
    value = "400Mi"
  }

  set {
    name  = "apiserver.resources.requests.memory"
    value = "80Mi"
  }

  set {
    name  = "apiserver.resources.limits.cpu"
    value = "200m"
  }

  set {
    name  = "apiserver.resources.requests.cpu"
    value = "100m"
  }
```

- Are you trying to use ALPHA features? Did you enable them? no

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
