### ISSUE TITLE
Rewrite controller tests

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes-sigs/service-catalog#2597]
Current integration tests cannot be used with the CRDs. This issue is created to track all integration test statuses:
PRs:
 - https://github.com/kubernetes-incubator/service-catalog/pull/2596 (merged)
 - https://github.com/kubernetes-incubator/service-catalog/pull/2580 (merged)
 - https://github.com/kubernetes-sigs/service-catalog/pull/2667

Existing integration test method |                  done                  | description
----|:-:|---
TestBasicFlows| Yes | all subtests migrated to TestBasicFlow #2580 
TestBasicFlowsWithOriginatingIdentity| No 
TestBindingFailure|Yes| migrated to TestServiceBindingFailure #2580 
TestServiceBindingOrphanMitigation|Yes| migrated to TestServiceBindingOrphanMitigation #2580 
TestServiceBindingDeleteWithAsyncBindInProgress|Yes | #2596
TestServiceInstanceDeleteWithAsyncProvisionInProgress|Yes | #2596
TestServiceInstanceDeleteWithAsyncUpdateInProgress|Yes | #2596
TestAsyncProvisionWithMultiplePolls|Yes|covered by `TestBasicFlow/async instances with multiple polls` #2580 
TestCreateServiceInstanceAsynchronous| Yes | it is simplified scenario tested in `TestBasicFlow/async instances with multiple polls` #2580 
TestCreateServiceInstanceFailsWithNonexistentPlan|  No | #2667
TestCreateServiceInstanceNonExistentClusterServiceBroker | No | #2667 
TestCreateServiceInstanceNonExistentClusterServiceClassOrPlan | No | #2667
TestCreateServiceInstanceWithInvalidParameters | No | #2667
TestCreateServiceInstanceWithParameters | No | #2667
TestCreateServiceInstanceWithProvisionFailure | No | #2667
TestCreateServiceInstanceWithRetries | Yes | migrated to TestProvisionInstanceWithRetries #2580 
TestDeleteServiceInstance | Yes | #2580, #2596
TestRetryAsyncDeprovision | Yes | #2596
TestUpdateServiceInstanceChangePlans | No | #2667
TestUpdateServiceInstanceChangePlansToNonexistentPlan | No | #2667
TestUpdateServiceInstanceNewDashboardResponse | No | #2667
TestUpdateServiceInstanceUpdateParameters | No | #2667
TestCreateServiceBindingInstanceNotReady | No
TestCreateServiceBindingInvalidInstance | Yes | migrated to TestServiceBindingRetryForNonExistingClass #2580 
TestCreateServiceBindingInvalidInstanceFailure | No
TestCreateServiceBindingNonBindable | No
TestCreateServiceBindingSuccess | Yes | TestBasicFlows #2580 
TestCreateServiceBindingWithParameters | No
TestCreateServiceBindingWithSecretTransform | No
TestDeleteServiceBindingFailureRetry | Yes | #2596
TestDeleteServiceBindingFailureRetryAsync | Yes | #2596
TestClusterServiceClassRemovedFromCatalogWithoutInstances | Yes | #2596
TestClusterServicePlanRemovedFromCatalogWithoutInstances | Yes | #2596    
TestClusterServiceClassRemovedFromCatalogAfterFiltering | Yes | #2596

**Comment by mszostok** [comment]
the last PR (https://github.com/kubernetes-sigs/service-catalog/pull/2667) needs to be merged and then issue can be closed 

/remove-lifecycle rotten

**Comment by mszostok** [comment]
/remove-lifecycle rotten

it's closed as all work is done
