### ISSUE TITLE
Kubernetes deprecating resource versions

### ISSUE THREAD

**Issue by kramvan1** [kubernetes-sigs/service-catalog#2599]
# Bug Report 

**What happened**:

Kubernetes is deprecating resource versions, need to move to the new levels
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecation

1.16: Deployment, DaemonSet, ReplicaSet resources from extensions/v1beta1, apps/v1beta1 and apps/v1beta2 APIs.
v1.16: PodSecurityPolicy and NetworkPolicy resources from extensions/v1beta1 API.
v1.17: PriorityClass resources from scheduling.k8s.io/v1beta1 and scheduling.k8s.io/v1alpha1 APIs.
v1.18: Ingress resources from extensions/v1beta1 API
For most of these, the API replacements have been available for a long time. Please see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations for full details.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by baikai** [comment]
Do you mean the output of “kubectl get cm -n kube-system extension-apiserver-authentication -o yaml” cmd should not include the resourceVersion?
In my env, kubernetes version is 1.13.4, sc version is 0.1.42 and helm version is 2.11.
Output of cmd "kubectl get cm -n kube-system extension-apiserver-authentication -o yaml" as below:
apiVersion: v1
data:
  client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTE5MDMxMjA2NTUxNloXDTI5MDMwOTA2NTUxNlowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOUu
    BzMr9agtS03oRAP1FQJAN6hl9DylRikurVU5Sy2h/ot4YaO7HwVUNuxKsRebCFr9
    +cC5MwIZQbyulJLssYr8xXjlqhHEf10YcZysY0LbQILoaWyajImT0tzzWoNEPosW
    2CCgifZIUQNN3ZyAvPRtm2kThZLt7hYITahysnPPSyALEhX3z6V52yrqxccDk+Oy
    FHziQBTfdhafYLxvObK7legI9q+YhJ01dDAIVosRoVt9Xm2TOCBE+RmYeekSY7Yd
    9E0uxY5OEIGi3fxp/SxT7PZpxSf4bTR4nEPqGudVtcDqQgBXqnGVKqOY+5DAGkZr
    WNadTQcvLqFdhdanQv0CAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIwTk5aBn7wCULU5UTQJskt6HLCf
    yKFwlsn72E9Y2OflROHr1OrasUrbea/L33YvbYDfzBTr6dob0MtcYVsPeD08DE3M
    evLKQk11L1Hj4xViUjfYWUiaXuXSORyawnahxbd44dt9QMnxGrvXyKxZ0tvF91XF
    od+1q7/KCkBHHYWO04SX0QbBYVeY1umWZv2YCpB/zl3vQDPouqtPSwCZI7e2K9zE
    vxyL934L3YY/6ts2fH1YZbTXVLE6evEKc23IXiG68jj+FyXhu0rXvPqcUBejTQ6A
    CV6/+9fkwPQmu/tclcBUv6K8YJAMXMFKb18/4XUpqFGTY8eutu9N//HdAHg=
    -----END CERTIFICATE-----
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIC0DCCAbigAwIBAgIBADANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5mcm9u
    dC1wcm94eS1jYTAeFw0xOTAzMTIwNjU1MTdaFw0yOTAzMDkwNjU1MTdaMBkxFzAV
    BgNVBAMTDmZyb250LXByb3h5LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAnHqvHgHHMpm68hE7VKxS2h8c/pIa/H+VS7jYCQ1Nu0nI3RpAYguhVDCE
    Kyq7MohRRHjfhpcpGdVkOJjPKvo/rmNviaMqVzlpiyH64N2Rraol1l8WsWJYQQa+
    GJ7Rt39GapVrppgprOBiPc6a6t6bDOiW3Ur8tbYAKZ542xKWGPXgueXi49pIhoUj
    9q55Uf2gM8T5gT6eyXbL+TSjlL7PKrTDKSVyszG+GmQUHo/yt87qttEl4w0GVtyU
    bPpGoBGHhqted5VVfOx4ZImbkGfhfIaEZ2PLql/d34N0/mBZtHOGSKk2MRWFq+Hj
    xQcSkkw2VIX8jt9lPhgb4dL0N+Vj5wIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQw
    DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAb2aO+EfVZHR3dM4B
    LBtOtmZEwOGnOLL5TqA6W4T+Q3N4KaSOA9jTLQCLvw0HiDuMlgIHaMN+8wGXVEQd
    kjTRcH5/m5ocWJ1SxzTtIVcK6v706QKir6jvpncOGfzkUkxNrOSybxJtoKcpx7MV
    SyXbm6iwwULn5x7ptbYmbQhMbqd4FaDAhb/74ecW18MprZMiIq4ozg0ZuIuoyh8L
    ah/h1UYYRHD1Ny/X9gXYRNL3GzAO6WFVw8OS6zBFv47rgXy80R5rjhacvpYEoKc5
    fjwWyd7md4hCljmmtnXWic8UzquWt8cFQ88qgGCPhn401LTxrVo2kpu4ZEWoGLRp
    GYxyIQ==
    -----END CERTIFICATE-----
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-12T06:55:44Z"
  name: extension-apiserver-authentication
  namespace: kube-system
  resourceVersion: "56"
  selfLink: /api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication
  uid: db8832ce-4493-11e9-bc1d-fa163ef390aa

**Comment by kramvan1** [comment]
Noticed these apiVersion's are out of date:
https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiserver-deployment.yaml#L2
https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/controller-manager-deployment.yaml#L2
 
 
Mark VanderwielIBM Watson and Cloud Platform - IBM Cloud Kubernetes ServiceRochester, MN==================================================================Internet Address: vanderwl@us.ibm.com
 
 
----- Original message -----From: Bai Kai <notifications@github.com>To: kubernetes-incubator/service-catalog <service-catalog@noreply.github.com>Cc: Mark Vanderwiel <vanderwl@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [kubernetes-incubator/service-catalog] Kubernetes deprecating resource versions (#2599)Date: Tue, Apr 9, 2019 2:43 AM 
Do you mean the output of “kubectl get cm -n kube-system extension-apiserver-authentication -o yaml” cmd should not include the resourceVersion?In my env, kubernetes version is 1.13.4, sc version is 0.1.42 and helm version is 2.11.Output of cmd "kubectl get cm -n kube-system extension-apiserver-authentication -o yaml" as below:apiVersion: v1data:client-ca-file: |-----BEGIN CERTIFICATE-----MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMB4XDTE5MDMxMjA2NTUxNloXDTI5MDMwOTA2NTUxNlowFTETMBEGA1UEAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOUuBzMr9agtS03oRAP1FQJAN6hl9DylRikurVU5Sy2h/ot4YaO7HwVUNuxKsRebCFr9+cC5MwIZQbyulJLssYr8xXjlqhHEf10YcZysY0LbQILoaWyajImT0tzzWoNEPosW2CCgifZIUQNN3ZyAvPRtm2kThZLt7hYITahysnPPSyALEhX3z6V52yrqxccDk+OyFHziQBTfdhafYLxvObK7legI9q+YhJ01dDAIVosRoVt9Xm2TOCBE+RmYeekSY7Yd9E0uxY5OEIGi3fxp/SxT7PZpxSf4bTR4nEPqGudVtcDqQgBXqnGVKqOY+5DAGkZrWNadTQcvLqFdhdanQv0CAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIwTk5aBn7wCULU5UTQJskt6HLCfyKFwlsn72E9Y2OflROHr1OrasUrbea/L33YvbYDfzBTr6dob0MtcYVsPeD08DE3MevLKQk11L1Hj4xViUjfYWUiaXuXSORyawnahxbd44dt9QMnxGrvXyKxZ0tvF91XFod+1q7/KCkBHHYWO04SX0QbBYVeY1umWZv2YCpB/zl3vQDPouqtPSwCZI7e2K9zEvxyL934L3YY/6ts2fH1YZbTXVLE6evEKc23IXiG68jj+FyXhu0rXvPqcUBejTQ6ACV6/+9fkwPQmu/tclcBUv6K8YJAMXMFKb18/4XUpqFGTY8eutu9N//HdAHg=-----END CERTIFICATE-----requestheader-allowed-names: '["front-proxy-client"]'requestheader-client-ca-file: |-----BEGIN CERTIFICATE-----MIIC0DCCAbigAwIBAgIBADANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTAeFw0xOTAzMTIwNjU1MTdaFw0yOTAzMDkwNjU1MTdaMBkxFzAVBgNVBAMTDmZyb250LXByb3h5LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHqvHgHHMpm68hE7VKxS2h8c/pIa/H+VS7jYCQ1Nu0nI3RpAYguhVDCEKyq7MohRRHjfhpcpGdVkOJjPKvo/rmNviaMqVzlpiyH64N2Rraol1l8WsWJYQQa+GJ7Rt39GapVrppgprOBiPc6a6t6bDOiW3Ur8tbYAKZ542xKWGPXgueXi49pIhoUj9q55Uf2gM8T5gT6eyXbL+TSjlL7PKrTDKSVyszG+GmQUHo/yt87qttEl4w0GVtyUbPpGoBGHhqted5VVfOx4ZImbkGfhfIaEZ2PLql/d34N0/mBZtHOGSKk2MRWFq+HjxQcSkkw2VIX8jt9lPhgb4dL0N+Vj5wIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAb2aO+EfVZHR3dM4BLBtOtmZEwOGnOLL5TqA6W4T+Q3N4KaSOA9jTLQCLvw0HiDuMlgIHaMN+8wGXVEQdkjTRcH5/m5ocWJ1SxzTtIVcK6v706QKir6jvpncOGfzkUkxNrOSybxJtoKcpx7MVSyXbm6iwwULn5x7ptbYmbQhMbqd4FaDAhb/74ecW18MprZMiIq4ozg0ZuIuoyh8Lah/h1UYYRHD1Ny/X9gXYRNL3GzAO6WFVw8OS6zBFv47rgXy80R5rjhacvpYEoKc5fjwWyd7md4hCljmmtnXWic8UzquWt8cFQ88qgGCPhn401LTxrVo2kpu4ZEWoGLRpGYxyIQ==-----END CERTIFICATE-----requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'requestheader-group-headers: '["X-Remote-Group"]'requestheader-username-headers: '["X-Remote-User"]'kind: ConfigMapmetadata:creationTimestamp: "2019-03-12T06:55:44Z"name: extension-apiserver-authenticationnamespace: kube-systemresourceVersion: "56"selfLink: /api/v1/namespaces/kube-system/configmaps/extension-apiserver-authenticationuid: db8832ce-4493-11e9-bc1d-fa163ef390aa

**Comment by MHBauer** [comment]
email has mangled this beyond fixing 

```
Mark VanderwielIBM Watson and Cloud Platform - IBM Cloud Kubernetes ServiceRochester, MN==================================================================Internet Address: vanderwl@us.ibm.com
 
 
----- Original message -----From: Bai Kai <notifications@github.com>To: kubernetes-incubator/service-catalog <service-catalog@noreply.github.com>Cc: Mark Vanderwiel <vanderwl@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [kubernetes-incubator/service-catalog] Kubernetes deprecating resource versions (#2599)Date: Tue, Apr 9, 2019 2:43 AM 
Do you mean the output of “kubectl get cm -n kube-system extension-apiserver-authentication -o yaml” cmd should not include the resourceVersion?In my env, kubernetes version is 1.13.4, sc version is 0.1.42 and helm version is 2.11.Output of cmd "kubectl get cm -n kube-system extension-apiserver-authentication -o yaml" as below:apiVersion: v1data:client-ca-file: |-----BEGIN CERTIFICATE-----MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMB4XDTE5MDMxMjA2NTUxNloXDTI5MDMwOTA2NTUxNlowFTETMBEGA1UEAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOUuBzMr9agtS03oRAP1FQJAN6hl9DylRikurVU5Sy2h/ot4YaO7HwVUNuxKsRebCFr9+cC5MwIZQbyulJLssYr8xXjlqhHEf10YcZysY0LbQILoaWyajImT0tzzWoNEPosW2CCgifZIUQNN3ZyAvPRtm2kThZLt7hYITahysnPPSyALEhX3z6V52yrqxccDk+OyFHziQBTfdhafYLxvObK7legI9q+YhJ01dDAIVosRoVt9Xm2TOCBE+RmYeekSY7Yd9E0uxY5OEIGi3fxp/SxT7PZpxSf4bTR4nEPqGudVtcDqQgBXqnGVKqOY+5DAGkZrWNadTQcvLqFdhdanQv0CAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIwTk5aBn7wCULU5UTQJskt6HLCfyKFwlsn72E9Y2OflROHr1OrasUrbea/L33YvbYDfzBTr6dob0MtcYVsPeD08DE3MevLKQk11L1Hj4xViUjfYWUiaXuXSORyawnahxbd44dt9QMnxGrvXyKxZ0tvF91XFod+1q7/KCkBHHYWO04SX0QbBYVeY1umWZv2YCpB/zl3vQDPouqtPSwCZI7e2K9zEvxyL934L3YY/6ts2fH1YZbTXVLE6evEKc23IXiG68jj+FyXhu0rXvPqcUBejTQ6ACV6/+9fkwPQmu/tclcBUv6K8YJAMXMFKb18/4XUpqFGTY8eutu9N//HdAHg=-----END CERTIFICATE-----requestheader-allowed-names: '["front-proxy-client"]'requestheader-client-ca-file: |-----BEGIN CERTIFICATE-----MIIC0DCCAbigAwIBAgIBADANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTAeFw0xOTAzMTIwNjU1MTdaFw0yOTAzMDkwNjU1MTdaMBkxFzAVBgNVBAMTDmZyb250LXByb3h5LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHqvHgHHMpm68hE7VKxS2h8c/pIa/H+VS7jYCQ1Nu0nI3RpAYguhVDCEKyq7MohRRHjfhpcpGdVkOJjPKvo/rmNviaMqVzlpiyH64N2Rraol1l8WsWJYQQa+GJ7Rt39GapVrppgprOBiPc6a6t6bDOiW3Ur8tbYAKZ542xKWGPXgueXi49pIhoUj9q55Uf2gM8T5gT6eyXbL+TSjlL7PKrTDKSVyszG+GmQUHo/yt87qttEl4w0GVtyUbPpGoBGHhqted5VVfOx4ZImbkGfhfIaEZ2PLql/d34N0/mBZtHOGSKk2MRWFq+HjxQcSkkw2VIX8jt9lPhgb4dL0N+Vj5wIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAb2aO+EfVZHR3dM4BLBtOtmZEwOGnOLL5TqA6W4T+Q3N4KaSOA9jTLQCLvw0HiDuMlgIHaMN+8wGXVEQdkjTRcH5/m5ocWJ1SxzTtIVcK6v706QKir6jvpncOGfzkUkxNrOSybxJtoKcpx7MVSyXbm6iwwULn5x7ptbYmbQhMbqd4FaDAhb/74ecW18MprZMiIq4ozg0ZuIuoyh8Lah/h1UYYRHD1Ny/X9gXYRNL3GzAO6WFVw8OS6zBFv47rgXy80R5rjhacvpYEoKc5fjwWyd7md4hCljmmtnXWic8UzquWt8cFQ88qgGCPhn401LTxrVo2kpu4ZEWoGLRpGYxyIQ==-----END CERTIFICATE-----requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'requestheader-group-headers: '["X-Remote-Group"]'requestheader-username-headers: '["X-Remote-User"]'kind: ConfigMapmetadata:creationTimestamp: "2019-03-12T06:55:44Z"name: extension-apiserver-authenticationnamespace: kube-systemresourceVersion: "56"selfLink: /api/v1/namespaces/kube-system/configmaps/extension-apiserver-authenticationuid: db8832ce-4493-11e9-bc1d-fa163ef390aa
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 

```

**Comment by MHBauer** [comment]
we should do something like in 
https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/_helpers.tpl#L11-L21
to address this.

**Comment by kramvan1** [comment]
@MHBauer In relation to this, should service catalog have a min required Kube version,  1.12?  Having that in place would make it very easy to address this issue of what apiVersion to use/hardcode in.

**Comment by MHBauer** [comment]
authorization stuff is v1 since 1.12 at least, https://kubernetes.io/docs/reference/

**Comment by kramvan1** [comment]
@MHBauer sure `1.12` would be a good place to start, then it's just a matter of Doc'ing that and updating the templates directly that have deprecated  apiVersions.

**Comment by kramvan1** [comment]
/remove-lifecycle stale

Still valid

**Comment by MHBauer** [comment]
@mszostok @jberkhahn 
This should be something done periodically. At the very least on every update of kubernetes libraries.

**Comment by MHBauer** [comment]
#2753 looks related.
