### ISSUE TITLE
service catalog api crash

### ISSUE THREAD

**Issue by obeyler** [kubernetes-sigs/service-catalog#2626]
# Bug Report 

**What happened**:
service catalog api always crash
the last log of the container is :

 `Error: open /tmp/client-ca-file502348919: permission denied`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
just install 

**Anything else we need to know?**:
I use etcd server in the master with tls activated
PodSecurityPolicy admission is activated

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- service-catalog version: 0.2.0
- Cloud provider or hardware configuration: openstack
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? yes
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields

```
apiVersion: v1
data:
  client-ca-file: |+
    -----BEGIN CERTIFICATE-----
    MIIDJ...
    -----END CERTIFICATE-----

  requestheader-allowed-names: '["aggregator"]'
  requestheader-client-ca-file: |+
    -----BEGIN CERTIFICATE-----
    MIID...
    -----END CERTIFICATE-----

  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
kind: ConfigMap
metadata:
  creationTimestamp: 2019-05-15T20:35:37Z
  name: extension-apiserver-authentication
  namespace: kube-system
  resourceVersion: "38"
  selfLink: /api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication
  uid: ff7893f9-7750-11e9-8c68-fa163ecc8811

```

- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
yes to pupulate the config map
Same result with only :
helm install -n catalog --namespace kube-system 

- Are you trying to use ALPHA features? Did you enable them? no

**Comment by jberkhahn** [comment]
i'm not able to reproduce this myself. How are you running your kubernetes cluster?
