### ISSUE TITLE
Switch from api-server to CRDs approach

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2633]
Description

When the Service Catalog project was started, Kubernetes didn’t have the concept of Custom Resource Definitions (CRDs), which is a way to extend the Kubernetes API without having to write your own API server.

The Service Catalog, instead, implements an aggregated API server, which requires writing an API server from scratch and maintaining its code. Using CRDs would allow the Service Catalog to only own the Controller implementation and to benefit from the implementation improvements of the general API machinery and the CRDs tools.

As the service catalog roadmap towards 1.0.0 includes a point about using CRDs instead of api-server we'd like to implement that change and remove custom api-server and etcd.

Reasons

    We and other entities using Service Catalog facing issues with crashing often api-server, controller components also caused by etcd default configuration which doesn't fit a requested usage from controller. When etcd is down, api-server is down, all service catalog CRD and CR instances disappear. Then for example, we are able to delete a given namespace and when api-server is back we see have a state where for example service instances are assigned to not existing namespace (previously deleted)
    As the k8s community going towards CRDs only as a way to expose k8s APIs

- cut a release branch of the current apiserver code
- hook the release branch up to a separate testing/release pipeline
- merge CRDs into master / eliminate apiserver code
- update Docs

**Comment by k** [comment]
Whats the status of this?

**Comment by jberkhahn** [comment]
the actual CRD's have been merged and are in beta release. we're still fixing bugs and such before we cut an actual release.

**Comment by k** [comment]
What's the eta on the final release? The last release candidate was over 6 months ago...

**Comment by mszostok** [comment]
Hi @k

Please take a look on this message :) 
https://kubernetes.slack.com/archives/C232SF3TK/p1589536387010900

In general, once I will merge support for [k8s 1.18](https://github.com/kubernetes-sigs/service-catalog/pull/2796) I will cut the 0.3.0 release. Adding the beta prefix (v0.3.0-beta.3) does not make sense anymore. It’s already been half a year since we merge CRDs and since then we didn’t have any major issues with this implementation.

_The rest of the issues from the 0.3.0 milestone will be addressed later and released with 0.3.x versions._

**Comment by mszostok** [comment]
We still need to update docs on k8s website: https://github.com/kubernetes/website/pull/15496

**Comment by mszostok** [comment]
Hi @k 
ICYMI: The 0.3.0 is officially released: https://github.com/kubernetes-sigs/service-catalog/releases/tag/v0.3.0

Please let me know if you run into any issues 🙂

**Comment by MHBauer** [comment]
I think we can close this, yes?
/close
