### ISSUE TITLE
Provide Migration Path for Apiserver -> CRDs

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2634]
**Description**

We need to create a migration guide/scripts which will allow clients to do easily migraton from api-server to CRD approach.

**Raw scenario**
- **pre-upgrade hook**
  - replace the api-server deployment with the api-server that has a read-only mode
  - backup the Service Catalog resources to the persistent volume (consider backuping etcd and second with new format that will be used for restore)
- **upgrade**
  - remove the api-server
  - remove the etcd storage
  - adjust secrets, RBAC etc.
  - upgrade controller manager
  - install webhook server
- **post-upgrade**
  - scale down the controller manager to 0  
  - restore the Service Catalog resources - Spec and Status (status is important because we do not want to trigger provisioning for already process items)
  - scale up controller manager

**AC**
- upgrade with migration only if previous SC version has api-server, and explicitely flag with migration is set to true
- migration from the Aggregated API Server to CRD approach is doable and well documented

**Comment by mszostok** [comment]
The migration tool and documentation are already created:
- docs: https://github.com/kyma-incubator/service-catalog/blob/crds-migration/docs/migration-apiserver-to-crds.md
- tool: https://github.com/kyma-incubator/service-catalog/tree/crds-migration/cmd/migration

**Comment by mszostok** [comment]
the story was mainly resolved by https://github.com/kubernetes-sigs/service-catalog/pull/2710
