### ISSUE TITLE
Update Service Catalog / broker client to OSB 2.15

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2635]
- make needed code changes
- add docs about what version we support/ what features we're missing

**Comment by jberkhahn** [comment]
OSB 2.15 should be forthcoming as well

**Comment by jberkhahn** [comment]
I think 2.15 just went green

**Comment by jberkhahn** [comment]
#2673
#2674 
#2675 
#2676 
#2677

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
