### ISSUE TITLE
Get rid of pod preset junk in chart

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2637]
these flags don't do anything and should be removed

**Comment by jberkhahn** [comment]
also the charts probably have a bunch of other stuff that could stand to be cleaned up, maybe take a look at that as well?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
