### ISSUE TITLE
Catalog Controller Manager Pod Crashing

### ISSUE THREAD

**Issue by RamanPndy** [kubernetes-sigs/service-catalog#2648]
# Bug Report 

**What happened**:
Service Catalog Controller Manager Pod is keep crashing also APIService Object is not able to contact catalog-api-server service using it's ClusterIP.

**What you expected to happen**:
Service Catalog Controller Manager Pod should work in running status.

**How to reproduce it (as minimally and precisely as possible)**:
helm . install --name catalog --namespace catalog

**Anything else we need to know?**:
I'm running behind a corporate proxy and proxy settings are present in /etc/environment.
here are the logs of crashing controller-manager pod:
I0604 10:42:11.926868       1 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0604 10:42:11.926872       1 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0604 10:42:11.926876       1 round_trippers.go:447]     Content-Length: 20
I0604 10:42:11.926880       1 round_trippers.go:447]     Date: Tue, 04 Jun 2019 10:40:14 GMT
I0604 10:42:11.926883       1 round_trippers.go:447]     Audit-Id: 7cf120be-d357-457b-bff8-94718d1a1606
I0604 10:42:11.926913       1 request.go:942] Response Body: service unavailable
I0604 10:42:11.927023       1 request.go:1145] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0604 10:42:11.927036       1 controller_manager.go:311] Failed to get supported resources from server: the server is currently unable to handle the request
I0604 10:42:12.838073       1 controller_manager.go:306] Created client for API discovery
I0604 10:42:12.838178       1 round_trippers.go:419] curl -k -v -XGET  -H "User-Agent: service-catalog/v0.2.1 (linux/amd64) kubernetes/6c6a49d/service-catalog-controller-discovery" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXItdG9rZW4tZmdidDciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWNvbnRyb2xsZXItbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2ZGMyMTA3LTg2YTktMTFlOS04NTcwLTAwNTA1NmE1OTFkZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXIifQ.u1d2OyqSSKlD7leL-Czbr62vNOeyO9jlEW2lbnkmsD9LIIpXegEeB3mDX64PCKzxpb9ltK4PQ7yK8apF4JndCf-qrORJjMoO8OmhfxDA1ki-WOJ3ZjIXYJMC9piz9YJujSaT8M718W9Zw86AT6OJ_yLvH5P1PLYaFNWJhL4e0KnzjxEYcybDY2kjwNIP7nDYjvZ7XR6NSkLS--aehaZBThSfMNPRKkFQHOxaU0_33HALHD_iBwnyj2dmTKg3HOkn8mwi_DOBUbgwqhvKJ4ojXjLz6vUCNp1v2-Bc4tz0Yi94cIqjvOY2xRHCTMXf9jeeLY5GgNxAB43iHmCFTq0vnQ" -H "Accept: application/json, */*" 'https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I0604 10:42:12.925130       1 round_trippers.go:438] GET https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 86 milliseconds
I0604 10:42:12.925152       1 round_trippers.go:444] Response Headers:
I0604 10:42:12.925156       1 round_trippers.go:447]     Audit-Id: c51e3a10-8904-4f9e-9cbb-10dbc82665d7
I0604 10:42:12.925159       1 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0604 10:42:12.925161       1 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0604 10:42:12.925163       1 round_trippers.go:447]     Content-Length: 20
I0604 10:42:12.925166       1 round_trippers.go:447]     Date: Tue, 04 Jun 2019 10:40:15 GMT
I0604 10:42:12.925202       1 request.go:942] Response Body: service unavailable
I0604 10:42:12.925275       1 request.go:1145] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0604 10:42:12.925285       1 controller_manager.go:311] Failed to get supported resources from server: the server is currently unable to handle the request
I0604 10:42:13.838102       1 controller_manager.go:306] Created client for API discovery
I0604 10:42:13.838193       1 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.2.1 (linux/amd64) kubernetes/6c6a49d/service-catalog-controller-discovery" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXItdG9rZW4tZmdidDciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWNvbnRyb2xsZXItbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2ZGMyMTA3LTg2YTktMTFlOS04NTcwLTAwNTA1NmE1OTFkZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXIifQ.u1d2OyqSSKlD7leL-Czbr62vNOeyO9jlEW2lbnkmsD9LIIpXegEeB3mDX64PCKzxpb9ltK4PQ7yK8apF4JndCf-qrORJjMoO8OmhfxDA1ki-WOJ3ZjIXYJMC9piz9YJujSaT8M718W9Zw86AT6OJ_yLvH5P1PLYaFNWJhL4e0KnzjxEYcybDY2kjwNIP7nDYjvZ7XR6NSkLS--aehaZBThSfMNPRKkFQHOxaU0_33HALHD_iBwnyj2dmTKg3HOkn8mwi_DOBUbgwqhvKJ4ojXjLz6vUCNp1v2-Bc4tz0Yi94cIqjvOY2xRHCTMXf9jeeLY5GgNxAB43iHmCFTq0vnQ" 'https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I0604 10:42:13.839517       1 round_trippers.go:438] GET https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 1 milliseconds
I0604 10:42:13.839538       1 round_trippers.go:444] Response Headers:
I0604 10:42:13.839542       1 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0604 10:42:13.839546       1 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0604 10:42:13.839550       1 round_trippers.go:447]     Content-Length: 20
I0604 10:42:13.839553       1 round_trippers.go:447]     Date: Tue, 04 Jun 2019 10:40:16 GMT
I0604 10:42:13.839556       1 round_trippers.go:447]     Audit-Id: 4768bdd2-a93d-40d1-bc91-3e8278f19219
I0604 10:42:13.839606       1 request.go:942] Response Body: service unavailable
I0604 10:42:13.839729       1 request.go:1145] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0604 10:42:13.839744       1 controller_manager.go:311] Failed to get supported resources from server: the server is currently unable to handle the request
I0604 10:42:14.838072       1 controller_manager.go:306] Created client for API discovery
I0604 10:42:14.838162       1 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.2.1 (linux/amd64) kubernetes/6c6a49d/service-catalog-controller-discovery" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXItdG9rZW4tZmdidDciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWNvbnRyb2xsZXItbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2ZGMyMTA3LTg2YTktMTFlOS04NTcwLTAwNTA1NmE1OTFkZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXIifQ.u1d2OyqSSKlD7leL-Czbr62vNOeyO9jlEW2lbnkmsD9LIIpXegEeB3mDX64PCKzxpb9ltK4PQ7yK8apF4JndCf-qrORJjMoO8OmhfxDA1ki-WOJ3ZjIXYJMC9piz9YJujSaT8M718W9Zw86AT6OJ_yLvH5P1PLYaFNWJhL4e0KnzjxEYcybDY2kjwNIP7nDYjvZ7XR6NSkLS--aehaZBThSfMNPRKkFQHOxaU0_33HALHD_iBwnyj2dmTKg3HOkn8mwi_DOBUbgwqhvKJ4ojXjLz6vUCNp1v2-Bc4tz0Yi94cIqjvOY2xRHCTMXf9jeeLY5GgNxAB43iHmCFTq0vnQ" 'https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I0604 10:42:14.839329       1 round_trippers.go:438] GET https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 1 milliseconds
I0604 10:42:14.839468       1 round_trippers.go:444] Response Headers:
I0604 10:42:14.839487       1 round_trippers.go:447]     Audit-Id: 029d40ed-6f04-46c3-bffb-1f4b63537f7b
I0604 10:42:14.839493       1 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0604 10:42:14.839497       1 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0604 10:42:14.839501       1 round_trippers.go:447]     Content-Length: 20
I0604 10:42:14.839505       1 round_trippers.go:447]     Date: Tue, 04 Jun 2019 10:40:17 GMT
I0604 10:42:14.839547       1 request.go:942] Response Body: service unavailable
I0604 10:42:14.839691       1 request.go:1145] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0604 10:42:14.839711       1 controller_manager.go:311] Failed to get supported resources from server: the server is currently unable to handle the request
I0604 10:42:14.839854       1 controller_manager.go:306] Created client for API discovery
I0604 10:42:14.839955       1 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.2.1 (linux/amd64) kubernetes/6c6a49d/service-catalog-controller-discovery" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXItdG9rZW4tZmdidDciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWNvbnRyb2xsZXItbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2ZGMyMTA3LTg2YTktMTFlOS04NTcwLTAwNTA1NmE1OTFkZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXIifQ.u1d2OyqSSKlD7leL-Czbr62vNOeyO9jlEW2lbnkmsD9LIIpXegEeB3mDX64PCKzxpb9ltK4PQ7yK8apF4JndCf-qrORJjMoO8OmhfxDA1ki-WOJ3ZjIXYJMC9piz9YJujSaT8M718W9Zw86AT6OJ_yLvH5P1PLYaFNWJhL4e0KnzjxEYcybDY2kjwNIP7nDYjvZ7XR6NSkLS--aehaZBThSfMNPRKkFQHOxaU0_33HALHD_iBwnyj2dmTKg3HOkn8mwi_DOBUbgwqhvKJ4ojXjLz6vUCNp1v2-Bc4tz0Yi94cIqjvOY2xRHCTMXf9jeeLY5GgNxAB43iHmCFTq0vnQ" 'https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I0604 10:42:14.840688       1 round_trippers.go:438] GET https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 0 milliseconds
I0604 10:42:14.840707       1 round_trippers.go:444] Response Headers:
I0604 10:42:14.840710       1 round_trippers.go:447]     Audit-Id: 256718f9-99b2-4468-ad8d-1090d37df216
I0604 10:42:14.840713       1 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0604 10:42:14.840715       1 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0604 10:42:14.840717       1 round_trippers.go:447]     Content-Length: 20
I0604 10:42:14.840720       1 round_trippers.go:447]     Date: Tue, 04 Jun 2019 10:40:17 GMT
I0604 10:42:14.840733       1 request.go:942] Response Body: service unavailable
I0604 10:42:14.840780       1 request.go:1145] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0604 10:42:14.840786       1 controller_manager.go:311] Failed to get supported resources from server: the server is currently unable to handle the request
F0604 10:42:14.840795       1 controller_manager.go:236] error running controllers: failed to get api versions from server: "timed out waiting for the condition", "the server is currently unable to handle the request"

here 10.233.0.1 is the kubernetes service IP. when catalog controller manager is trying to contact kubernetes service it's getting 503 response. Please suggest any possible solution of this.
also APIService object v1beta1.servicecatalog.k8s.io is in FailedDiscoveryStatus. is it related to this ??
APIService object throwing the error  no response from https://10.233.55.255:443: Get https://10.233.55.255:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) where 10.233.55.255 is the catalog-apiserver service IP.

root@master-1:~# kubectl get svc -n catalog
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
catalog-catalog-apiserver            NodePort    10.233.55.255   <none>        443:30443/TCP   6m20s
catalog-catalog-controller-manager   ClusterIP   10.233.6.17     <none>        443/TCP         6m20s

Please help me resolve this issue.

**Environment**: Bare Metal
- Kubernetes version (use `kubectl version`): 1.13.5
- service-catalog version: 0.2.1
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? Yes
  - Do you see the configmap in kube-system?  Yes
  - Does it have all the necessary fields? Yes
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
apiVersion: v1
data:
  client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTE5MDUzMTA2MzE0MVoXDTI5MDUyODA2MzE0MVowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALMx
    Gwioh8/4trckNgGYwieQNjUQCahkxHYhKDhSolAjBSZQI6Ezh1HUypPVblt54oey
    HipT8k7n7pOBEgVwfZxrET86vtKR9E1juPwnYMkQ/5Mlc/YfWnxoK9/irFBG4GIy
    6ehY2OrT3h7B6+aZ4zGQ9pSJI8MbjlIkiR79YRJFe9u/1wHHbMfLO7Ysj5KyTvqb
    YajM+Q6xx4IuCkClXIkwodv8O+j9d0yoB3S9DZdgIcAxpQJHpvewAHxCST0PL0dk
    +UO6AvPlE11rX/3IKeUA976fkAOb2SfmoiLsgalx2/8DQaPAprorjpVyPOA4tze+
    FiIyIFKCweNFGnBxcP8CAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFCIZlUfn7PLE530HkzHyybkLmBE
    FLecdkEBKjXdv0AuLUVwXIDY7VSLqADSgqdL68lCVJc64TKIcIjRsrms4mC9yYfB
    P4/TxZ5mOiYBfzP3BdaK23zdTGIFN86BGFYbV7bZnUwAu/RAQaK6E8GWCR9Vx45k
    qLQ/pfV6NKbXwtKwOkspVq1bxNfyTaxzlIJPaqXDs6zUapCnaxl6zhpYrtKkKvYf
    /VUmrhItTFLgPnBWBJgWjopxtMhIc054+2kqIS4Yl/UnLXkgdqtgftxq9pwqpjYa
    MRRYh61UjLp5SJmaZuvJXrG5cg9vHjENs4MUXMdq927irXAGmrsuaNt5Ta0=
    -----END CERTIFICATE-----
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIC0DCCAbigAwIBAgIBADANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5mcm9u
    dC1wcm94eS1jYTAeFw0xOTA1MzEwNjMxNDFaFw0yOTA1MjgwNjMxNDFaMBkxFzAV
    BgNVBAMTDmZyb250LXByb3h5LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEA2S/5A3IrhG/E7ratz4LTxuBkD79b18E8kpOIwX8/ynxNOJgA+bxhxtyh
    xSMWVqylVXhG8Chh2DoLhEMUH+6e7TSeysVu9AedDKZwDhQAu3GkrEUPvUKi0w7m
    k3CGxFTYDyQTA0PjfimDTQ96p3M0rg8TWDBfd2rlRkOeHYWN04cLJjI/7mfehbjf
    sap1HkpBalbQI3RDqzwQQzxL6EEdmZSjhpkMgk69nKEGAZxyWc4M3VxE7W28y+T4
    tMdyOtVTrl7ihqb5LJiVc0X/h3aZiBYR0MbsLiWHoLMqrq/wz2AF7niveWRiJoGT
    yhJImJMCiSFB3A4SiyVf+tShqXaJBQIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQw
    DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEADcdyUNgqaR55rjJQ
    JG3OTZkBDAjnRNebSmYzdKvCeAZN5ieN2/KGPOZd0Z17HdjHkKhQxPuQPbyAaLGo
    PJfNBVIUxBCCqwMPMz95QzsEEFJDwrCEDt+uR5gisIYJs+05qOwYKWzBxZGHtTmD
    IQ5hQmeI09Y22sdkfrPzVnPGb8ZSSWRN86VrgmafMOect42ZlGnP8tYuCCj6TxNa
    fsz5k+BOsajsqeBSiAGibDjrZR97JQiGZvh4WII/fUJnGU9TvHBtZHM1ywS//v1I
    g3j4sJq6zBZh2LyBUZEsNmPvgc1k4qFPNNpdepKuN8KDNVs+JksuYkAMr4EY9271
    H/3JPw==
    -----END CERTIFICATE-----
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-31T06:32:00Z"
  name: extension-apiserver-authentication
  namespace: kube-system
  resourceVersion: "58"
  selfLink: /api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication
  uid: cbd869ca-836d-11e9-bdd8-005056a591de
- Install tools:
  - Did you use helm? Yes
What were the helm arguments? Did you `--set` any extra values? No
- Are you trying to use ALPHA features? Did you enable them? No

**Comment by mszostok** [comment]
Hi @RamanPndy 

The controller-manager has the check which ensures that the Service Catalog APIs are available. They are required by controller, without them the clients cannot be initialized. 

source: https://github.com/kubernetes-sigs/service-catalog/blob/master/cmd/controller-manager/app/controller_manager.go#L342-L345 

**so this is expected behaviour**
