### ISSUE TITLE
Service Broker timeout is not configurable

### ISSUE THREAD

**Issue by fmui** [kubernetes-sigs/service-catalog#2657]
# Bug Report 

**What happened**:

The OSB spec states in the "Orphans" section:

> "Orphans can result if the Service Broker does not return a response before a request from the Platform times out (typically 60 seconds)."

The Service Catalog does not allow the configuration of this timeout, but always waits for 60 seconds. The spec would also allow a different (longer) timeout. 
In some scenarios, brokers may need slightly more than 60 seconds to wake up and execute the request.

**What you expected to happen**:

There should be a way to set the timeout globally and per broker.

**Comment by jberkhahn** [comment]
making this globally configurable wouldn't be too difficult. making it configurable per-broker would require a bit of plumbing, but is still doable.

in either case, this will likely have to wait until repo migration of [our OSB client](https://github.com/pmorie/go-open-service-broker-client) is complete, as we currently don't have access to the repo.

**Comment by mszostok** [comment]
The global timeout will be added in this PR: https://github.com/kubernetes-sigs/service-catalog/pull/2622

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
