### ISSUE TITLE
Replace use of UPS broker in docs walkthrough with minibroker

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2658]
Currently, we make extensive use of the [ups broker](https://github.com/kubernetes-sigs/service-catalog/tree/master/charts/ups-broker) in our documentation. The UPS broker is a dummy-broker that doesn't actually do anything, and it's name is often confusing for users.

Replace all use of the ups broker with [minibroker](https://github.com/osbkit/minibroker) a broker that deploys helm charts for various databases as OSB services. This is a much better example broker to use as it deploys actual services.

Known things that need to be rewritten:
[The walkthrough on the docsite](https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/walkthrough.md) - this is the basic walkthrough of installing a broker, provisioning a service, and binding that service. Now might also be a good time to replace all the use of raw kubectl with svcat.
[the resources used by the wallthrough](https://github.com/kubernetes-sigs/service-catalog/tree/master/contrib/examples/walkthrough) - this is all the yaml files used by the walkthrough kubectl commands. These may go away entirely if we switch to svcat.

**Comment by zulandar** [comment]
/dibs

Reviewing and will begin to update the docs.
