### ISSUE TITLE
Add upgrade test to pipeline

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2660]
This would deploy the current version of service catalog, a broker, provision a service and binding, and then deploy the new version on top and make sure everything survives the transition.

Much of the groundwork that needs to be down for #2659 will probably be useful here.

**Comment by mszostok** [comment]
The migration tool and documentation are already created:
- https://github.com/kyma-incubator/service-catalog/blob/crds-migration/contrib/hack/ci/run-migration-tests.sh#L91-L108
- https://github.com/kyma-incubator/service-catalog/blob/crds-migration/docs/migration-apiserver-to-crds.md

The bash script for executing the migration is also created: 
- https://github.com/kyma-incubator/service-catalog/blob/crds-migration/contrib/hack/ci/run-migration-tests.sh#L91-L108


Pull request to kubernetes/test-infra: (will be created after merging CRDs):
- https://github.com/kubernetes/test-infra/compare/master...mszostok:add-sc-upgrade-pipeline?expand=1

Test executed on prow:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-upgrade-job/1162329278755377152

**Comment by mszostok** [comment]
the story was successfully finished
