### ISSUE TITLE
Migrate pipeline resources to somewhere under SIG control

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2661]
Due to legacy reasons, some components of our pipeline were hosted on a hodge-podge of resources donated by various contributors to the project. We need to migrate these resources to somewhere under control of the current and future contributors of the project, which means using resources provided as part of the kubernetes org.

The only active resource that we still use that I'm currently aware of is  the svcat CLI binaries which are hosted in a Microsoft Azure bucket. We still have @carolynvs as an active contact, but I'd like them to be hosted on quay with everything else.

**Comment by carolynvs** [comment]
Cool, can quay host binaries? 👍

**Comment by carolynvs** [comment]
Oh we also have svc-cat.io that I think is still managed by my team. Not sure if k8's has a way to register and manage domains? I'm happy to keep that up and running but just wanted to call out that as another resource.

**Comment by jberkhahn** [comment]
Hmm, it can host 'application repositories' which I assume are binaries. I'll try to get in touch with someone from the steering committee to see about domains. Where is svcat.io actually hosted?

**Comment by mszostok** [comment]
[Here](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#requesting-a-subproject-domain) you can find doc about requesting domains for sigs project.

And about the CLI, it's not enough to add them as assets for each release? e.g. those projects are doing like that:

- https://github.com/kubernetes-sigs/kind/releases/tag/v0.3.0
- https://github.com/goreleaser/goreleaser/releases/tag/v0.110.0
- https://github.com/istio/istio/releases/tag/1.2.0
- https://github.com/knative/client/releases
- https://github.com/gohugoio/hugo/releases/tag/v0.55.6
- etc.


I'm only not sure if such thing will still work with `brew`

**Comment by carolynvs** [comment]
Just verified that I have a single azure resource group managing dns for svc-cat.io (our website) and svcat.sh (our downloads are backed by azure storage). Netlify is managing the hosting for svc-cat.io.

The reason why cli downloads aren't on github releases is because having a permalink like canary or latest is difficult (not impossible but more than I originally wanted to deal with when I setup storage).

As for brew, they rebuild from source and independently host binaries so they don't care about our storage at all. 😀

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
