### ISSUE TITLE
Stop running units in both Travis and Prow

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2662]
Currently we run units both in Travis and on Prow. This is unneeded, and we should switch to running everything in Prow if we can. I'm not sure exactly what is plugged into what, though, so cutting the travis job might have unintended consequences elsewhere in the pipeline.

**Comment by MHBauer** [comment]
I don't see the tests running in prow. Only building.

**Comment by MHBauer** [comment]
@mszostok I think this is done now.
/close
