### ISSUE TITLE
maximum_polling_duration field in Service Plan object is adhered to

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2676]
per osb spec 2.15

**Comment by guanxingfeng** [comment]
Is polling-interval-and-duration still not supported? I failed  test in version catalog-0.2.2
![image](https://user-images.githubusercontent.com/25924966/112448120-03e24e00-8d8d-11eb-954e-2513a55b892a.png)

https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-interval-and-duration
![image](https://user-images.githubusercontent.com/25924966/112447724-99311280-8d8c-11eb-9cd4-74da39818652.png)

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
