### ISSUE TITLE
No status field for service instance

### ISSUE THREAD

**Issue by ovod88** [kubernetes-sigs/service-catalog#2681]
# Bug Report 

**What happened**:
We have a k8s cluster with service catalog extension and our own service broker. This cluster  has been running for about 3 months without restarting catalog pods and the last request to broker was done 3 months ago. Recently we have tried to create again the service instance (another k8s cluster), but new instance showed no status:

```
~$ kubectl get serviceinstances 
NAME                  CLASS                                            PLAN                                   STATUS   AGE
test              ClusterServiceClass/xxx                            xxx                                      Ready    116d
test-new      ClusterServiceClass/xxx                             xxx                                                     6d
```
Such behavior crashed our GUI since catalog returned no status. All new requests end up with no status.

**What you expected to happen**:
Status field is expected to be filled as a normal behavior.

**How to reproduce it (as minimally and precisely as possible)**:
Basically nothing was done with catalog. It was running for a long time without interacting with it.

**Anything else we need to know?**:
It seems to be a bug. Logs from pods showed that during new request from GUI service broker received no requests for a new instance and contoller-manager sent no requests to broker. The catalog is left running as it is.

**Environment**:
- Kubernetes version (use `kubectl version`):
_Server side v1.13.7_
- service-catalog version:
_0.1.43_
- Cloud provider or hardware configuration:
_Configuration on openstack. Openstack is on physical machines._
- Do you have api aggregation enabled? 
_Yes_
  - Do you see the configmap in kube-system?
_Yes_ 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
_All fields are filled_
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
_Yes - via helm with:
--set apiserver.storage.etcd.persistence.enabled=false_
- Are you trying to use ALPHA features? Did you enable them?
_No_

**Comment by jberkhahn** [comment]
I can't really say what caused this problem without more information. What are you using as the backing store for your Service Catalog? Can you verify if the request made it through the Service Catalog apiserver to the backing store?

**Comment by jberkhahn** [comment]
Can't say for sure what went wrong without more info. Are you sure everything from your request is making it through the apiserver to the backing store? Have you looked through the logs of the Service Catalog controllers to see if they crashed or something? What happens if you restart the controller manager pods manually?

**Comment by ovod88** [comment]
Hello. It seems controller ran out of memory, rebooted itself and catalog was restored without intervention. So I believe if I rebooted it manually - i would restore...
