### ISSUE TITLE
Use the normal hyperkube image in integration tests

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2684]
It seems we're using an image Dug manually built with just kubectl in it for these tests, but it's a manually updated image and super out of date. Now that we're not running on Travis anymore it should be fine to just pull the latest hyperkube image and use that

**Comment by MHBauer** [comment]
```
docker run -it --rm duglin/kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.6-dirty", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"dirty", BuildDate:"2017-06-30T12:23:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Pretty good compatibility.

**Comment by mszostok** [comment]
all that code was related to the api-server which is not used anymore and it was removed by this PR: https://github.com/kubernetes-sigs/service-catalog/pull/2720
