### ISSUE TITLE
bump pmorie/go-open-service-broker-client

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2687]
this got bumped automatically when I was bumping the kube version. There was a validation added [here](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/fake/fake.go#L295) that is breaking a bunch of integration tests. I've split this out into it's own branch [here](https://github.com/jberkhahn/service-catalog/tree/bump_osb_client) so I can go ahead with the kube 1.15 bump

**Comment by mszostok** [comment]
related PR: https://github.com/kubernetes-sigs/service-catalog/pull/2689

**Comment by mszostok** [comment]
fixed
