### ISSUE TITLE
Can not running use helm deploy

### ISSUE THREAD

**Issue by jinjie2088** [kubernetes-sigs/service-catalog#2696]
[root@host-10-0-228-95 sbin]# kubectl -n kubeapps logs catalog-catalog-controller-manager-7c56db774-f7mvf
Error: unknown flag: --osb-api-request-timeout

**Comment by mszostok** [comment]
Hi @jinjie2088, could you tell me how you installed the Service Catalog? Which version did you use?

Yesterday we did the service catalog release. You can install it with commands:
```bash
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm install svc-cat/catalog-v0.2 \
    --name catalog --namespace catalog
```
---
the problem that you are mentioning occurs on the master branch when you will install Service Catalog from sources:
```bash
 helm install charts/catalog \
    --name catalog --namespace catalog
```

but in such situation, you are using the newest chart with the old image. **To make it work you should do:**
```bash
helm install charts/catalog \
    --name catalog --namespace catalog \
    --set image=quay.io/kubernetes-service-catalog/service-catalog:canary
```

it's mentioned here: https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/devguide.md#deploying-to-kubernetes

but remember that installing service catalog from the current master is only good for development(testing) purpose. In all other situation, you always should use the release versions.

Cheers :)

**Comment by jinjie2088** [comment]
thank you, I used v0.2.1, I upgrade to v0.2.2, it's ok.
