### ISSUE TITLE
incorporate kubernetes-sigs/go-open-service-broker-client into testing framework

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2701]
- add a thing to test infra to make it run the units
- get it working on prow
- redo the imports to have a proper vendor dir?

**Comment by jberkhahn** [comment]
got the travis stuff up and running, so at least we have the tests running for now

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
