### ISSUE TITLE
Inconsistent Helm Chart Name

### ISSUE THREAD

**Issue by adusumillipraveen** [kubernetes-sigs/service-catalog#2704]
# Bug Report 

**What happened**:

Latest chart is svc-catalog/catalog-v0.2 

<img width="921" alt="Screenshot 2019-09-10 at 13 23 54" src="https://user-images.githubusercontent.com/47391951/64613579-6273f100-d3ce-11e9-8712-a1be36e415e8.png">

**What you expected to happen**:

svc-catalog/catalog     	0.2.2 instead of -v0.2 prefix

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): NA
- service-catalog version: 0.2.2
- Cloud provider or hardware configuration: NA
- Do you have api aggregation enabled?  NA
  - Do you see the configmap in kube-system?  NA
  - Does it have all the necessary fields? NA
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by mszostok** [comment]
Currently, we are in the transition phase. You can see in release that we released from v0.2 branch
<img width="745" alt="Screen Shot 2019-09-10 at 15 43 36" src="https://user-images.githubusercontent.com/17568639/64625611-c86f7100-d3ec-11e9-9692-a54504b14470.png">

so here is the new way for installing Service Catalog from 0.2.x release:
<img width="817" alt="Screen Shot 2019-09-10 at 15 47 55" src="https://user-images.githubusercontent.com/17568639/64625663-dcb36e00-d3ec-11e9-8771-65a165f8f7de.png">

right now we are in 0.3.x phase and Service Catalog in this milestone will be switched to a new CRDs-based architecture. The old API Server-based implementation is available on the v0.2 branch. 
so repo will look like that:
<img width="818" alt="Screen Shot 2019-09-10 at 15 44 47" src="https://user-images.githubusercontent.com/17568639/64625842-2e5bf880-d3ed-11e9-9c5c-682c0cbb7dfa.png">

so this is a base work to allows us to support both approaches at the same time. 

Check also the community update recording: https://youtu.be/ECcUlatY64o?t=1393

**Comment by timja** [comment]
(I work with @adusumillipraveen )

```
 timja at Frankel in ~/projects/hmcts/cnp-module-palo-alto on fixes*
$ helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
"svc-cat" has been added to your repositories
 timja at Frankel in ~/projects/hmcts/cnp-module-palo-alto on fixes*
$ helm search service-catalog
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog     	0.2.1        	           	service-catalog API server and controller-manager helm chart
svc-cat/catalog-v0.2	0.2.2        	           	service-catalog API server and controller-manager helm chart
```

I don't see 0.3.x, only the previous version of that catalog published is 0.2.1

so we should use catalog-v0.2 for now?

**Comment by MHBauer** [comment]
I must say, I don't understand the rename either.

It's possile to get any version of a helm chart:
```
$ helm search --versions service-catalog
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                       
local/catalog       	0.1.26       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.2.1        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.2.0        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.43       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.42       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.41       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.40       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.39       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.38       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.37       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.36       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.35       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.34       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.33       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.32       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.31       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.30       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.29       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.28       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.27       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.26       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.25       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.24       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.23       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.22       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.21       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.20       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.19       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.18       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.17       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.16       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.15       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.14       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.13       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.12       	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.9        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.8        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.7        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.6        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.5        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.4        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.3        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.1.2        	           	service-catalog API server and controller-manag...
svc-cat/catalog     	0.0.1        	           	service-catalog API server and controller-manag...
svc-cat/catalog-v0.2	0.2.2        	           	service-catalog API server and controller-manag...
``

**Comment by mszostok** [comment]
Let me try to explain my point of view

@timja 
> I  don't see 0.3.x, only the previous version of that catalog published is 0.2.1

Currently, we are in the transition phase from the Aggregate API Server to CRD approach and PR https://github.com/kubernetes-sigs/service-catalog/pull/2630 is not yet merged so 0.3.x is not yet released. 

---

@MHBauer
> I must say, I don't understand the rename either.
> It's possile to get any version of a helm chart

yes, it is. You can also install a given version, using such command:
`helm install svc-cat/catalog --version 0.2.2`

**but If this is not specified, the latest version is installed**, so let me start from the beginning :)

#### Release: Previously 
In the previous approach, we never support two versions of the Service Catalog. You always released a new version and never patched the old one. We had only one branch: **master**

#### Release: Currently (desired state) 
Currently, we have two branches.

In the master branch, we will have the Service Catalog with the CRDs approach. We **fix bugs and add new features** there. New releases are created with the `0.3.x` version. 

In the v0.2 branch, we have the old API Server-based implementation. We support this implementation by providing **only bug fixes** until July 2020.


#### Installation 

In documentation we have info that you should just execute:
```console
helm install svc-cat/catalog \
    --name catalog --namespace catalog
```

and probably a lot of people doing sth like that in their installation scripts to just have the latest release installed on their clusters. Previously it was good because you always released a new version of Service Catalog and never patched the old one.

In new approach it could be error prone. Scenario:
1. We released the deprecated 0.2.2 version from v0.2 branch:
```
$ helm search service-catalog
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog     	0.2.2        	           	service-catalog API server and controller-manager helm chart
```
2. We released the newest 0.3.0 version from master:
```
$ helm search service-catalog
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog     	0.3.0        	           	service-catalog API server and controller-manager helm chart
```
3. We released the patched version (some bug fixing) from v0.2 branch (deprecated one):
  ```
  $ helm search service-catalog
  NAME                	CHART VERSION	APP VERSION	DESCRIPTION
  svc-cat/catalog     	0.2.3        	           	service-catalog API server and controller-manager helm chart
  ```

**Problem:**
Using `helm install/search svc-cat/catalog` is not deterministic. Sometimes it will install the latest version from v0.2 branch (deprecated) sometimes newest one from the master.
IMO contract should be like: With `helm install/search svc-cat/catalog` you will get/install **latest fully supported** version of Service Catalog (released from master). 

**Solution:**
If you want to install an older version of service catalog (for instance the  API-server based version from v0.2 branch) append branch name to the chart name:

```console
helm install svc-cat/catalog-v0.2 \
    --name catalog --namespace catalog
```

---

@MHBauer @jberkhahn Ok, I think that I've explained the whole story behind that, so under this issue, we need to decide if such approach is a bug or feature :)

**Comment by MHBauer** [comment]
In my opinion it's a misuse of the version. We have versions, use them. 

If the understanding is, that helm with no args, pulls a docker and always installs the "most recently uploaded helm chart" that's a failure of helm. 

if the chronological order is :

Earliest release 2018
0.2.1
0.2.2
0.3.0
0.2.3
Latest release 2019 

And I try to install the chart with no args, my presumption is this is sorted by version correctly and I get 0.3
If not, we need to file a helm defect, and be much more explicit with our version specifications in the documentation.

If it's a problem with developers getting a strange version, we need to document that and they can work around it. I am very much more concerned about final release artifacts and problems like this issue #2704.

For upgrade scenarios, I'm not sure we've ever tested them or claimed anything, so I don't have too much concern either way, but we should test it and make a scenario and document what happens.

**Comment by adusumillipraveen** [comment]
IMHO, Doesn't it make sense to release version 1.x.x when we are making a major breaking change and let this be 0.x.x ? That's what I have seen many helm/charts do.

**Comment by MHBauer** [comment]
SGTM.
