### ISSUE TITLE
Can't deploy service-catalog with many etcd IPs

### ISSUE THREAD

**Issue by Maellooou** [kubernetes-sigs/service-catalog#2709]
# Bug Report 

**What happened**:
I try to deploy with helm the service catalog with the etcd non embedded and a cluster of 3 etcd instances already existing

`export etcd_servers="http://IP1:2379,http://IP2:2379,http://IP3:2379"
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm install svc-cat/catalog --name catalog --namespace catalog \                                  
--set apiserver.storage.etcd.servers=$etcd_servers \
--set apiserver.storage.etcd.useEmbedded=false
Error: failed parsing --set data: key "<end of IP2>:2379" has no value (cannot end with ,)
`

I tried also without ""

```
export etcd_servers=http://IP1:2379,http://IP2:2379,http://IP3:2379 
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm install svc-cat/catalog --name catalog --namespace catalog \                                
--set apiserver.storage.etcd.servers=$etcd_servers \
--set apiserver.storage.etcd.useEmbedded=false
Error: failed parsing --set data: key "<end of IP2>:2379" has no value (cannot end with ,)
```

**What you expected to happen**:
Deploy the chart successfully

**How to reproduce it (as minimally and precisely as possible)**:
See before

**Anything else we need to know?**:
It works well with one IP 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- service-catalog version: catalog-0.2.1
- Cloud provider or hardware configuration: 
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by jfpucheu** [comment]
Same issue, an etcd cluster should be supported because it is written etcd-serverS !

**Comment by MHBauer** [comment]
This sounds like a helm or helm-chart issue. The underlying apiserver uses exactly the same code as upstream apiservers, so it is supported at that end.
