### ISSUE TITLE
Support imagePullSecrets

### ISSUE THREAD

**Issue by Samze** [kubernetes-sigs/service-catalog#2712]
**The problem**

Some users of service-catalog might be running k8s in an airgapped environment and so they will not have access to public docker registries and these private registries may also have authentication. This means that service-catalog deployments will not be able to pull images when you run helm install.

**The solution**

Along with allowing the image, we can template in an "imagePullSecrets" var into the deployments and allow it to be set in the helm chart values.yaml.

We have had a first pass at this https://github.com/Samze/service-catalog/commit/e1cd1cd550546babfe4b3f3c3de6b609e85fa258 happy to make a PR. 

We think we will change the structure to be more like some bitnami helm charts such as  https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L55.

Cheers,
Sam & @albertoleal

**Comment by mszostok** [comment]
Hi @Samze 

I agree with your proposition about the structure. Would you like to submit a pull-request with those changes?

Cheers

**Comment by Samze** [comment]
Great, yes we will submit a PR 👍

**Comment by mszostok** [comment]
nice, thanks 🙇
