### ISSUE TITLE
svcat provision command enhancement for service parameters via config file or config map

### ISSUE THREAD

**Issue by ElectronicWizzard** [kubernetes-sigs/service-catalog#2724]
# Bug Report 

**What happened**:
svcat provision cli does not allows to specify either:
* json file path to read the parameters for service creation
* configmap name to read the parameters for service creation

There was a related issue for the first item https://github.com/kubernetes-sigs/service-catalog/issues/2543 but it was closed without providing the promised enhancement.

**What you expected to happen**:

Enhance the API for https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/cli.md#provision-a-service to support to read configuration either from specified file location or kubernetes configmap

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
