### ISSUE TITLE
We are not able to release Service Catalog because of timeout

### ISSUE THREAD

**Issue by mszostok** [kubernetes-sigs/service-catalog#2726]
**Description**

Currently, the Service Catalog release is done by Travis CI. There is one job called [**Deploy**](https://github.com/kubernetes-sigs/service-catalog/blob/master/.travis.yml#L55-L64). In that stage, we are building and pushing:
- Service Catalog images for all arch (amd64 arm arm64 ppc64le s390x) 
- svcat CLI for all arch (win, linux, darwin)

Release history with time consumption:
- [Release version 0.1.43](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/521494911) -  41min9sec
- [Release version 0.2.0](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/532558622) 41min11sec
- [Release version 0.2.1](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/540981155) 40min34sec
- [Release version 0.2.2](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/540981155) 43min50sec
- [Release version v0.3.0-beta.0](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/590507379) 47min1sec
- [Release version v0.3.0-beta.1](https://travis-ci.org/kubernetes-sigs/service-catalog/builds/593559460) - 50min - **timeout** 

Travis builds are timeouted when a job on a public repository takes longer than 50 minutes.
_source: https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts_

**Problem**

As we can see we were always really close to job timeout. The build process also depends on network connection because we are downloading a docker image for each arch, then building our binaries and pushing result images to quey. 
In version 0.3.0 we are building additionally migration and cleaner binaries which also affected building time.

As a result, the new Service Catalog version cannot be released because we are hitting timeout:
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Solution**

The Travis job timeout cannot be customized. We are also limmited by the open-source global queue and sometimes we need to wait for jobs to be started. 

As "hot-fix" we should parallelize our deploy stage by arch type. In the long term, we should move our release pipeline to Prow infra where we have more control.

**Comment by mszostok** [comment]
Partially resolved by the: https://github.com/kubernetes-sigs/service-catalog/pull/2727

Still, we need to move our release pipeline under Prow infra.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
