### ISSUE TITLE
The healthcheck docker images was never pushed to registry during release

### ISSUE THREAD

**Issue by mszostok** [kubernetes-sigs/service-catalog#2745]
# Bug Report 

**What happened**:
We have the [healthcheck chart](https://github.com/kubernetes-sigs/service-catalog/tree/master/charts/healthcheck) which is based on the `quay.io/kubernetes-service-catalog/healthcheck:v0.3.0-beta.1`, but this image was never pushed to the remote docker registry.

The problem is that we do not specify it for the `release-push` target in Makefile: https://github.com/kubernetes-sigs/service-catalog/blob/433a8765b06dda36fa43126642ac6e568a52ff19/Makefile#L381-L414

**What you expected to happen**:
The healthcheck docker images is pushed to quay.io and healthcheck chart working properly with Service Catalog 0.3.x release.

**Comment by mszostok** [comment]
@jberkhahn you know maybe why the healthcheck was never pushed?

**Comment by jberkhahn** [comment]
whoever put it in forgot to edit the makefile, i guess?

**Comment by mszostok** [comment]
ok, so I will provide PR to include that in our pipelines

**Comment by mszostok** [comment]
/reopen
/remove-lifecycle rotten

still valid

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
