### ISSUE TITLE
Suggestion: use go module instead of dep

### ISSUE THREAD

**Issue by ydcool** [kubernetes-sigs/service-catalog#2756]
- Go module is easy to use, a lots of enhancements introduced since go 1.13
 - Go module and proxy  can be very helpful to those developers who are blocked from visiting google,k8s.io etc by the GFW
 - Most repositories under kubernetes use go module

**Comment by mszostok** [comment]
Fixed by https://github.com/kubernetes-sigs/service-catalog/pull/2795
