### ISSUE TITLE
Not able to create a ServiceInstance

### ISSUE THREAD

**Issue by morehendrix** [kubernetes-sigs/service-catalog#2772]
# Bug Report 

**What happened**: A service instance could not be created because a clusterserviceclass was not found. 

**What you expected to happen**: The clusterserviceclass is found and the service instance can be at least forwarded to the ClusterServiceBroker.

**How to reproduce it (as minimally and precisely as possible)**: Installed service-catalog 0.3.0beta2 (successfully). Installed open-service-broker-azure 1.8.4 (successfully). I can list the clusterservicebroker and it is in status READY. The catalog could be fetched and I can list the clusterserviceclasses and they are correctly shown.  

Then, when deploying a serviceinstance of one of the registered clusterserviceclass, it fails with status "ReferencesNonexistentServiceClass":

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql-dbms
spec:
  clusterServiceClassExternalName: azure-postgresql-9-6-dbms
  clusterServicePlanExternalName: general-purpose

**Anything else we need to know?**: If I try to deploy with kube-name, I go through clusterserviceclass and clusterserviceplan, but provision also fails with "The provision call failed and will be retried: Error communicating with broker for provisioning: instanceID is required"

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- service-catalog version: 0.3.0beta2
- Cloud provider or hardware configuration: Azure
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values? 
- Are you trying to use ALPHA features? Did you enable them?

**Comment by miguelaferreira** [comment]
I'm seeing a similar issue, also on `0.3.0beta2`. While trying to provision an AWS S3 bucket I get the following error on the controller manager
```
I0316 17:33:44.305885       1 request.go:947] Request Body: {
...
"reason":"ReferencesNonexistentServiceClass",
"message":"The instance references a ClusterServiceClass that does not exist. References a non-existent ClusterServiceClass {ClusterServiceClassExternalName:\"s3\"} or there is more than one (found: 0)"
...
}
```

However, I can see the service class with the `s3` external name in the list
```bash
$ kubectl get ClusterServiceClass                  
NAME                                   EXTERNAL-NAME      BROKER   AGE
101d23b2-6968-5227-9615-d9946aa93974   cognito            aws-sb   19m
1d5a76f2-15aa-5e1f-949b-502c4b4c88d0   lex                aws-sb   19m
2c36b050-d7cb-5291-9831-62edd6ba1d8f   redshift           aws-sb   19m
321f7537-b34a-58cd-a38d-6ce12581621d   translate          aws-sb   19m
3fb91311-c7a2-5eb1-be45-9f934d38dd0b   emr                aws-sb   19m
52b328f4-ba6c-5ba7-98be-09fbb56c8811   kinesis            aws-sb   19m
645fe0b4-f5d7-5205-a0b0-9f1e2c747e35   rdsmariadb         aws-sb   19m
66a2153f-87b5-55e5-a2d9-c2b30c7f84b7   sns                aws-sb   19m
7439b527-4721-5791-888b-34f5b43f5fc2   codecommit         aws-sb   19m
7cc0e9d7-01e7-5c0c-a32a-efff0a65ab27   athena             aws-sb   19m
7e9a2b0b-817e-5626-92e2-efb62fdf02c3   elasticache        aws-sb   19m
7ed93fee-4532-5261-8ef2-351d70d6d19a   s3                 aws-sb   19m
828cd5be-cb48-5f00-b798-160b8026e1a0   sqs                aws-sb   19m
84b30625-128e-5590-a8ea-0a53eca2e57d   elasticsearch      aws-sb   19m
87c0ab4f-e4ef-520d-b2f7-084f9cd63d34   polly              aws-sb   19m
90f0ef74-95e6-56bb-b50c-f81aea077ae6   aurorapostgresql   aws-sb   19m
96584d9f-6e04-5d70-8520-d8f9aab9cd26   rdsmysql           aws-sb   19m
9eacf223-6530-58ac-a6b7-ab78e4966be6   rdspostgresql      aws-sb   19m
a5b21648-360e-5207-947b-942cf5247425   rdsmssql           aws-sb   19m
bd0fa534-fce8-5381-bc7c-e0f04e2f758d   dynamodb           aws-sb   19m
d55b7cb9-378b-52f2-b4df-5616d869547f   kms                aws-sb   19m
d86d7b28-37bb-5d50-8be4-a1e696fca877   mq                 aws-sb   19m
e34bf19d-5170-5eac-affc-4b0bc326bd31   rekognition        aws-sb   19m
e5569092-189d-5e36-8fd3-dfa2dfe1396a   documentdb         aws-sb   19m
ea6a2b7f-2ef5-5e73-8670-5129d2936776   auroramysql        aws-sb   19m
fd0bcf24-01fc-51ec-9ca3-2d2c98849c5c   rdsoracle          aws-sb   19m
fdc58048-36f5-5697-bd38-eb01e232b6ac   route53            aws-sb   19m

**Comment by miguelaferreira** [comment]
This is still an issue, it would be great to have a maintainer at least comment on it.
