### ISSUE TITLE
in k8s v1.16 or 1.17 can't create broker

### ISSUE THREAD

**Issue by zeratullich** [kubernetes-sigs/service-catalog#2775]
# Bug Report 
`helm list`

NAME      	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE 

catalog   	1       	Thu Jan 16 17:44:51 2020	DEPLOYED	catalog-0.3.0-beta.2	           	catalog

when i  create minibroker 
`helm repo add minibroker https://minibroker.blob.core.windows.net/charts`
`helm install --name minibroker --namespace minibroker minibroker/minibroker`
**What happened**:
i get error messages:
`Error: release minibroker failed: Internal error occurred: failed calling webhook "mutating.clusterservicebrokers.servicecatalog.k8s.io": Post https://catalog-catalog-webhook.catalog.svc:443/mutating-clusterservicebrokers?timeout=30s: EOF`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):   v1.16 or v1.17
- service-catalog version:   catalog-0.3.0-beta.2 
- Cloud provider or hardware configuration: local k8s  cluster
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by daydrim** [comment]
Hello, the issue is still reproducable in 1.18

**Comment by clickatsachin** [comment]
was there any resolution to abovr ?

**Comment by jiayihu** [comment]
In my case I think I'm having this error because minibroker doesn't support ARM64. The pod is created but if you try to get the logs, you see `standard_init_linux.go:219: exec user process caused: exec format error` which means that the binary cannot be executed. I've opened an issue about it https://github.com/kubernetes-sigs/minibroker/issues/120
