### ISSUE TITLE
make verify-links has issues

### ISSUE THREAD

**Issue by Samze** [kubernetes-sigs/service-catalog#2782]
# Bug Report 

**What happened**

We tried the steps of cloning the repo and running `make` but it failed.
```
> git clone git@github.com:kubernetes-sigs/service-catalog.git
> cd service-catalog
> make
....
Running href checker (Checking external hrefs):
./docs/contribute/docs.md: Can't load url: http://localhost:4000 (tried 5 times)
./pkg/kubernetes/README.md: Can't load url: https://github.com/kubernetes/common (tried 5 times)
make: *** [verify-docs] Error 1
```

**Anything else we need to know?**:
This seems to be because `make verify-docs` checks that hrefs in markdown files are valid but it ONLY runs this check on when you have master checked out. CI is passing because it always checks out a non-master branch prior to running `make verify`.

When running on master this fails with some invalid links. So there are a couple issues here:
1. `make verify-docs` checking links is never run in CI
2. We should be able to run `make` against master locally and it pass. There are failures referencing deadlinks and localhost links.

Additionally, out of interest, what is the motivation for only running `make verify-docs` against master?

**Comment by jberkhahn** [comment]
This was before my time, so I'm not really sure. I believe @MHBauer was here when this was added. Any insight?

**Comment by MHBauer** [comment]
> This seems to be because `make verify-docs` checks that hrefs in markdown files are valid but it ONLY runs this check on when you have master checked out. CI is passing because it always checks out a non-master branch prior to running `make verify`.
>     1. `make verify-docs` checking links is never run in CI

Looks true. Checked a recent build: https://travis-ci.org/github/kubernetes-sigs/service-catalog/jobs/659169060#L432

>     2. We should be able to run `make` against master locally and it pass. There are failures referencing deadlinks and localhost links.

Agreed.

> Additionally, out of interest, what is the motivation for only running `make verify-docs` against master?

Branch should be `master` on release.

The change itself is not helpful https://github.com/kubernetes-sigs/service-catalog/pull/1652 https://github.com/kubernetes-sigs/service-catalog/pull/1652/commits/8950fbe11f92c18535c242168fb739c3321305ae

I don't have an exact answer, but I do recall complaints about the href checker failing spuriously when network connectivity was flakey. I do not see anything in the meeting notes for that time period.  @duglin 

Slack archive has the answer https://kubernetes.slack.com/archives/C232SF3TK/p1515084283000176

**Comment by duglin** [comment]
The latest version https://github.com/duglin/vlinker/blob/master/bin/verify-links.sh#L87 supports the option to retry if there are HTTP GET failures, helps with network burps.

If I'm remember correctly, they opted to only run it on master (instead of each PR) because they didn't think flagging href errors for PR was worth it. IOW, it wasn't a serious enough issue to block the merging of PR.  I didn't agree with the decision back then.
