### ISSUE TITLE
OSB API Version 

### ISSUE THREAD

**Issue by prary** [kubernetes-sigs/service-catalog#2784]
**Question**

What is OSB API implementation version in the latest version of service-catalog?

**Comment by jberkhahn** [comment]
I believe we're up to 2.14 at this time.

**Comment by Samze** [comment]
Service Catalog uses https://github.com/kubernetes-sigs/go-open-service-broker-client under the hood. You can see 2.14 support in this [issue](https://github.com/kubernetes-sigs/go-open-service-broker-client/issues/144).

**Comment by mszostok** [comment]
As was mentioned, Service Catalog supports 2.14. You can subscribe for issues created for 2.15: https://github.com/kubernetes-sigs/service-catalog/issues?q=is%3Aopen+is%3Aissue+label%3AOSBAPI-update-2.15

and we also encaurage anyone to support us and contribute 🙂  PRs are more than welcome 🚀
