### ISSUE TITLE
Register broker not working on kubernetes 1.18

### ISSUE THREAD

**Issue by georgifarashev** [kubernetes-sigs/service-catalog#2793]
# Bug Report 

When I try to register a broker:
`svcat register mybroker --url <broker_url> --basic-secret <secret_name>`
I get the following error:
*Error: register request failed (ServiceBroker.servicecatalog.k8s.io "mybroker" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1\`)*

**What you expected to happen**:
The broker to be registered successfully.

**How to reproduce it (as minimally and precisely as possible)**:
 1) create a k8s cluster with version 1.18.x
 2) install service catalog version 0.3.0-beta2
 3) register a broker using svcat

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.2
- service-catalog version: v0.3.0-beta.2
- Cloud provider or hardware configuration: aws
- Install tools:
  - Did you use helm? - **Yes**. What were the helm arguments? Did you `--set` any extra values? *helm install catalog svc-cat/catalog  --namespace catalog --version 0.3.0-beta.2*
- Are you trying to use ALPHA features? -  **No** . Did you enable them? - **No** .

**Comment by mszostok** [comment]
Hi @georgifarashev 

Yes, the service catalog does not support 1.18 yet. AFAIK there are some changes in client-go so we need to bump that dependency.

**Comment by alexwo** [comment]
Hi @mszostok ,

Thanks for your quick response!  and the rapid PR to update everything (https://github.com/kubernetes-sigs/service-catalog/pull/2796/commits)

Is the fix for supporting **k8s 1.18** version is planned to be released as part of the 0.3.0 milestone?  or perhaps implemented and released more early?  

Thanks,
Alex

**Comment by mszostok** [comment]
Hi @alexwo 

so the plan is as follow:
1. Switch service catalog to go 1.13 with go modules (https://github.com/kubernetes-sigs/service-catalog/pull/2795)
2. Remove unused code from api-server (https://github.com/kubernetes-sigs/service-catalog/pull/2720)
3. Bump to K8s version (https://github.com/kubernetes-sigs/service-catalog/pull/2796)

We hope to finish all that stuff this week and do the 0.3.0 release as beta does not make sense anymore as we are using the CRD already for half a year and we didn't have any problems with this implementation.

Rest issues from the 0.3.0 milestone will be addressed later and release with 0.3.x versions ;)

**Comment by mszostok** [comment]
Hi @alexwo & @georgifarashev 🙂 

The new release is now available https://github.com/kubernetes-sigs/service-catalog/releases/tag/v0.3.0 with support for k8s 1.18 🎉 

please let me know if you will encounter any problem with that release and sorry for the delayed release but we had a few problems (e.g. downtime of quey.io, switching from go dep to go mod etc.)
