### ISSUE TITLE
Missing struct tags for json

### ISSUE THREAD

**Issue by Fabian-K** [kubernetes-sigs/service-catalog#2798]
Hi,

I´m wondering if there is a reason why there are no struct tags for json in the source code.  
https://github.com/kubernetes-sigs/service-catalog/blob/bfead02508171e07cfe9bc486e2bc9099de17e09/pkg/apis/servicecatalog/types.go#L31-L37

For this example, the information that TypeMeta is embedded but ObjectMeta is wrapped with 'metadata' when serializing to/from json is missing. Many other projects include this which is really handy when generating a json schema from the go definition.

```go
 type ClusterServiceBroker struct { 
 	metav1.TypeMeta `json:",inline"`
 	metav1.ObjectMeta `json:"metadata"`
 } 
```

Thanks,
Fabian

**Comment by mszostok** [comment]
Hi @Fabian-K 

Unfortunately, you are referring to wrong `types.go`.

please use those from `v1beta1` package. 
https://github.com/kubernetes-sigs/service-catalog/blob/bfead02508171e07cfe9bc486e2bc9099de17e09/pkg/apis/servicecatalog/v1beta1/types.go

There all jsons tags are specified :)


The `pkg/apis/servicecatalog/types.go` was used by already deprecated and removed api-server implementation, this file will be removed via this pr: https://github.com/kubernetes-sigs/service-catalog/pull/2720

**Comment by mszostok** [comment]
Please reopen if sth will not work as expected 🙂

**Comment by Fabian-K** [comment]
🤦‍♂️ my apologies and thanks for pointing me to the right place!

**Comment by mszostok** [comment]
no problem 😄 At the beginning it was also confusing me, I'm happy that we are finally removing it.
