### ISSUE TITLE
Secret watcher can cause OOM failures

### ISSUE THREAD

**Issue by polskikiel** [kubernetes-sigs/service-catalog#2800]
# Bug Report 

**What happened**:

Because the `controller-manager` underneath uses a Secrets informer that caches secrets from the **whole** cluster on the application start, it may fall into `CrashLoopBackoff` state with the OOM reason.

**What you expected to happen**:

That creation of unrelated secrets won't affect the `controller-manager`.

**How to reproduce it (as minimally and precisely as possible)**:

Create secrets on the cluster and observe that `controller-manager` container has bigger memory consumption. 

**Anything else we need to know?**:

Ideas:
- Replace informer logic with k8s client which will request the apiserver without the cache.
- Provide a way to watch only related secrets. Maybe using some label or naming convention.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.37", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-10T21:17:01Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version: `quay.io/kubernetes-service-catalog/service-catalog:v0.3.0-beta.2-6-g4690fae`
- Are you trying to use ALPHA features? Did you enable them? Enabled:
    - OriginatingIdentity
    - ServicePlanDefaults
    - AsyncBindingOperations
    - CascadingDeletion

**Comment by mszostok** [comment]
resolved by: https://github.com/kubernetes-sigs/service-catalog/pull/2830
