### ISSUE TITLE
The restored service instance resource is not relinked to the same external service instance previously provisioned

### ISSUE THREAD

**Issue by phong2tran** [kubernetes-sigs/service-catalog#2801]
# Bug Report 

**What happened**:
Using Velero (https://velero.io/) for backup/restore of the service catalog resources for DR, the restored service instance resource from the service catalog backup is not automatically relinked to the existing external service instance (Postgres database in this case), but attempted to provision the same external database instance instead.  

**What you expected to happen**:
The restored service instance resource should be linked to the external service instance provisioned previously through the service broker. 

**How to reproduce it (as minimally and precisely as possible)**:
Creating Service Catalog Resources: 
---------------------------------------
1.	Registered Postgres service broker.
2.	Created a Postgres service instance.
3.	Created a service binding for this service instance

Taking a Backup of These Service Catalog Resources:
---------------------------------------------------------
Velero provides a few ways to select resources for backup such as namespaces, label selectors, and resource types. For this test, the resource type selection is used. 

$ velero backup create service-catalog  --include-resources "clusterservicebrokers.servicecatalog.k8s.io,clusterserviceclasses.servicecatalog.k8s.io,clusterserviceplans.servicecatalog.k8s.io,serviceinstances.servicecatalog.k8s.io,servicebindings.servicecatalog.k8s.io,secrets" –wait

Deleting Service Catalog Resources:
---------------------------------------
To simulate the data lost in the cluster and leave the external service instance (Postgres database) orphaned, we need to update the service broker resource to use the wrong port, so the service catalog controller could not connect to the Postgres service broker when forcibly deleting the service catalog resources. 
1.	Deleted the service binding for Postgres instance which also implicitly deleting the secret.
2.	Deleted the Postgres service instance. 
3.	Deregistered the Postgres service broker.

Checking the Postgres server and making sure that we still have the database created as part of the service instance provisioning. 

Restoring Service Catalog Resources from the Backup:
-----------------------------------------------------------
$ velero restore create --from-backup service-catalog --wait

Problem with Restored Service Instance Resource:
When checking on the service catalog resources after the restore process is finished, the service instance has failed status:

$ kubectl get serviceinstances
NAME             CLASS                            PLAN            STATUS                AGE
pg-instance-01   ClusterServiceClass/dev-pg-sid   dev-pg-devpid   ProvisionCallFailed   11h

And with the following error found in the event logs of the service instance, 

Events:
  Type     Reason               Age                From                                Message
  ----     ------               ----               ----                                -------
  Warning  RetryBackoff         47s (x2 over 47s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:35.267307237 +0000 UTC m=+9.164867324
  Warning  RetryBackoff         46s (x2 over 46s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:37.662463581 +0000 UTC m=+11.560023671
  Warning  RetryBackoff         44s (x2 over 44s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:41.867657212 +0000 UTC m=+15.765217309
  Warning  RetryBackoff         39s (x2 over 39s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:50.020582426 +0000 UTC m=+23.918142515
  Warning  RetryBackoff         31s (x2 over 31s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:28:06.174067452 +0000 UTC m=+40.071627550
  Warning  ProvisionCallFailed  15s (x6 over 48s)  service-catalog-controller-manager  Error provisioning ServiceInstance of ClusterServiceClass (K8S: "dev-pg-sid" ExternalName: "dev-pg") at ClusterServiceBroker "dev-postgres-broker": Status: 409; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
  Warning  RetryBackoff         15s (x2 over 15s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:28:38.352269746 +0000 UTC m=+72.249829834

It looked like when the service instance is restored back to the cluster, the service catalog controller detects the instance as a new resource to be added, and thus tried to call the Postgres service broker to provision the same service instance (database) which already existed.  

Service Catalog Controller Log:
I0409 09:27:32.450718       1 controller_instance.go:147] ServiceInstance "backing-services/pg-instance-01" v8370686: Received ADD event: {"kind":"ServiceInstance","apiVersion":"servicecatalog.k8s.io/v1beta1","metadata":{"name":"pg-instance-01","namespace":"backing-services","selfLink":"/apis/servicecatalog.k8s.io/v1beta1/namespaces/backing-services/serviceinstances/pg-instance-01","uid":"869f424d-7a43-11ea-b06a-1ed9bdd25d7a","resourceVersion":"8370686","generation":1,"creationTimestamp":"2020-04-09T09:21:42Z","labels":{"servicecatalog.k8s.io/spec.clusterServiceClassRef.name":"5b35f3e6aba00e259a808e4aa9aef33c4f6e1914049179faadb87b96","servicecatalog.k8s.io/spec.clusterServicePlanRef.name":"d11059f11f8149fe477a6d4bace1b2c69ad423c54cdf47c8a137f2d5","velero.io/backup-name":"service-catalog","velero.io/restore-name":"service-catalog-20200409022129"},"finalizers":["kubernetes-incubator/service-catalog"]},"spec":{"clusterServiceClassName":"dev-pg-sid","clusterServicePlanName":"dev-pg-devpid","parameters":{},"externalID":"20198954-1445-4600-ad3e-d083d3faadd6","userInfo":{"username":"system:serviceaccount:velero:velero","uid":"83b3507e-72de-11ea-8e09-7e6ebe78e9a7","groups":["system:serviceaccounts","system:serviceaccounts:velero","system:authenticated"]},"updateRequests":0},"status":{"conditions":null,"asyncOpInProgress":false,"orphanMitigationInProgress":false,"reconciledGeneration":0,"observedGeneration":0,"provisionStatus":"","deprovisionStatus":"","lastConditionState":"","userSpecifiedPlanName":"","userSpecifiedClassName":""}}

Note: We also tried to scale down the service catalog controller deployment to 0 before the restore and then scale it back up again after the restore. It did not help!

**Anything else we need to know?**:
For DR, we're running external data services like Postgres on VMs which have its own data protection (replication) done outside of K8S cluster. In case of DR event, we need to restore the service catalog resources from the backup using Velero and want the service instance and service bindings to point to the same external Postgres database instance provisioned previously before the DR event. The problem we are running into right now is when the service instance resource is restored, it triggers the creation of the same service instance again which caused "409 conflict" error. 

We just stumbled on this doc (https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/migration-apiserver-to-crds.md) for the service catalog version migration. Based on the steps described, it looked like there is a way to backup and then restore the service catalog instances and link them to externally existing service instances instead of reprovisioning through the service broker. If this is true, we need to know this "magic sauce" used by the service catalog migration tool :)

Could you please help to guide us on what can be done on performing the backup and restore of the service catalog resources by linking the service instance resource to the same external data instance (Postgres servers on VMs) for this DR scenario?

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.15.7
- service-catalog version:
v0.3.0-beta.2
- Cloud provider or hardware configuration:
vSphere 6.5
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
  yes Helm 3
- Are you trying to use ALPHA features? Did you enable them?

**Comment by mszostok** [comment]
Hi @phong2tran 

first please check if the restored Service Catalog CRDs have restored also `Status` entry. The controller manager saves all information under status entry. In case that you described I suppose that you do not have that and because of it it's treated by service catalog as a newly created resource and just trigger provisioning 🙂 

In the case of our migration, 
1. Scale down the Controller Manager to avoid any resource processing while applying resources.
2. and restore objects together with status entry e.g. https://github.com/kubernetes-sigs/service-catalog/blob/9c42d6be38254476b35198c861216a2f9e1d8dfb/pkg/migration/migration.go#L764 
3. Scale up the Controller Manager, and when controller is processing restored objects check the status and know that it was already provisioned and skip that step.

so please check if Velero restores also the Status entry.


btw. I was not in charge of this task but in our platform, we also used Velero and had problems with not allowed fields on ServiceInstance so we had such plugin: https://github.com/kyma-project/kyma/blob/release-1.11/components/backup-plugins/internal/plugins/service_instance.go

and the second problem was that the Secrets created by ServiceBinding were deleted because of wrong ownerReference (K8s triggered GC logic): https://github.com/kyma-project/kyma/blob/release-1.11/components/backup-plugins/internal/plugins/owner_reference.go


Tomorrow I will also try to get in touch with people responsible for that backup/restore and get more information on how we achieved that 🙂

**Comment by mszostok** [comment]
Ok, got information from our team. We just relied on the OSB API behavior that I described in above response. 

Which broker do you use to create Postgres instance?

**Comment by phong2tran** [comment]
Thanks a lot for the reponses @mszostok! 

We're using the internal Postgres service broker which is created in-house. This service broker is little out-of-date and not kept up to the open service broker API spec (v2.14). We will need to check  our service broker to see if it's conforming to OSB API behavior as pointed out in the link.  Also we will need to go through the service catalog backup/restore with Velero again to check for the Status entry.

We have a few pointers to follow and work on now and will update this thread shortly.  

Thanks,
Phong
