### ISSUE TITLE
Switch to apiextensions.k8s.io/v1 for CRD apiVersion

### ISSUE THREAD

**Issue by edwardecook** [kubernetes-sigs/service-catalog#2809]
Currently `apiextensions.k8s.io/v1beta1` is being used for all the CRDs within service catalog, e.g. https://github.com/kubernetes-sigs/service-catalog/blob/13e369797900d9b9d4e21be88e8e0016ec5d594f/charts/catalog/templates/crds/clusterservicebroker.yaml#L1

As of k8s v1.16.0 this is deprecated and the new `apiVersion` is `apiextensions.k8s.io/v1` and as of k8s v1.19.0 `apiextensions.k8s.io/v1beta1` will be removed. See https://v1-16.docs.kubernetes.io/docs/setup/release/notes/#api-changes for a (possibly non-exhaustive list) of changes. One of the main things we would get for free as part of this shift would be that we get structural schema: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

**Comment by mszostok** [comment]
When we started CRD the open api was not supported but now we can address that.

But we should also use some generators and have only one source of truth, so generate the CRDs YAML from the go struct: https://github.com/kubernetes-sigs/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/types.go

we can achieve that using https://github.com/kubernetes-sigs/controller-tools

As a result we will maintain only the Go structs

**Comment by hzliangbin** [comment]
Any progress?

**Comment by jhvhs** [comment]
The removal of `CustomResourceDefinition/v1beta1` has been [postponed until 1.22](https://github.com/kubernetes/kubernetes/issues/82022#issuecomment-636872808), so this issue is still significant
/lifecycle frozen

**Comment by gberche-orange** [comment]
A side effect of the use of the deprecated is that `helm install` or `helm upgrade` issue warning messages such as `apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

Also, while Helm is not supporting CRD uninstallation natively anymore as documented into 
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.

upon execution of the `helm uninstall` command, the helm client tries to delete all previously installed resources excluding CRDs but apparently not `apiextensions.k8s.io/v1 CustomResourceDefinition`.

As a result, the `helm uninstall --debug` output shows failed attempts to delete the service catalog crds

```
client.go:282: [debug] Starting delete for "serviceclasses.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "serviceinstances.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "serviceplans.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "clusterservicebrokers.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "clusterserviceclasses.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "clusterserviceplans.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "servicebindings.servicecatalog.k8s.io" CustomResourceDefinition
client.go:282: [debug] Starting delete for "servicebrokers.servicecatalog.k8s.io" CustomResourceDefinition
W0520 10:26:10.043282   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "servicebrokers.servicecatalog.k8s.io" not found
W0520 10:26:10.043665   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "clusterservicebrokers.servicecatalog.k8s.io" not found
W0520 10:26:10.045991   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "serviceinstances.servicecatalog.k8s.io" not found
W0520 10:26:10.046795   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "serviceclasses.servicecatalog.k8s.io" not found
W0520 10:26:10.047565   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "clusterserviceclasses.servicecatalog.k8s.io" not found
W0520 10:26:10.048116   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "clusterserviceplans.servicecatalog.k8s.io" not found
W0520 10:26:10.048395   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "servicebindings.servicecatalog.k8s.io" not found
W0520 10:26:10.048905   21241 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
client.go:311: [debug] customresourcedefinitions.apiextensions.k8s.io "serviceplans.servicecatalog.k8s.io" not found
```

Related helm resource removal is at https://github.com/helm/helm/blob/3f283c7c35fffda567894b9bf6cede5e19d43ffa/pkg/kube/client.go#L284

The CRD removal failure is likely because the cleaner job has removed them previously in https://github.com/kubernetes-sigs/service-catalog/blob/2fe0ea3384d19e72548bab01c1344fe67a38a151/pkg/cleaner/cleaner.go#L60-L89

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
