### ISSUE TITLE
Make 2.14 OSB API alpha gates enabled by default

### ISSUE THREAD

**Issue by mszostok** [kubernetes-sigs/service-catalog#2813]
**Description**

In  https://github.com/kubernetes-sigs/go-open-service-broker-client/pull/146 the 2.14  OSB API Version will become a stable one. We need to remove all alpha gates related to 2.14 and make the enabled by default, e.g. https://github.com/kubernetes-sigs/service-catalog/blob/11c5b363ad9070284f6f45d13107020a8aeab82a/charts/catalog/values.yaml#L107-L108

**Comment by jhvhs** [comment]
#dibs

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
