### ISSUE TITLE
Question: Case of externalID of ServiceInstance

### ISSUE THREAD

**Issue by vivekzhere** [kubernetes-sigs/service-catalog#2845]
[OSB spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#url-properties) does not place much restrictions on `instance_id`. I am using the `instance_id` as name for kubernetes resource created as part of instance provisioning. [Kubernetes Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) must contain only lowercase alphanumeric characters, `-` or `.`. Our broker have always received `instance_id` in this format only and never faced any issue with this (both from service catalog and cloud foundry).

I want to confirm that service catalog will not be using mixed case for the `externalID`. We are planning to just add a `toLowerCase` conversion on the `instance_id` and use it as kubernetes resource names. Here my concern is, if service catalog uses mixed case, it could possibly result in uniqueness conflict for the Kubernetes resource created.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
