### ISSUE TITLE
Support of OpenServiceBroker feature "binding_rotatable" in the ServiceCatalog

### ISSUE THREAD

**Issue by freegroup** [kubernetes-sigs/service-catalog#2846]
in the OpenServiceBroker spec it is possible to rotate a binding as describe here:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#binding-rotation

This feature is mandatory if we want to rotate an secret without a new deployment and restart of existing pods.

As far as I understood the existing binding is updated with the new binding information. In this case k8s updates the mounted secret within existing pods without restart. This feature is requested in the past in the ticket: https://github.com/kubernetes-sigs/service-catalog/issues/1815

Is there any backlog or plans to support this OSB specification part as well?

**Comment by jhvhs** [comment]
Hi @freegroup,

The support for binding rotation hasn't been yet finalised, and may become a new feature as part of the upcoming OSBAPI release. We will implement it as part of the new OSBAPI version implementation if and when it does.

**Comment by freegroup** [comment]
thanks for your feedback. Unfortunately I'm unable get a schedule for this feature....

I think I write my own operator to rotate the credentials in the meanwhile.

**Comment by jhvhs** [comment]
@freegroup Can we close this issue?
