### ISSUE TITLE
When do you plan to do a new release ?

### ISSUE THREAD

**Issue by obeyler** [kubernetes-sigs/service-catalog#2849]
# Question
When do you plan to do a release ?
since june  my PR (https://github.com/kubernetes-sigs/service-catalog/pull/2818) has been merged  to solve pb on helm chart but no release have been done yet.

**Comment by gberche-orange** [comment]
@jhvhs we were wondering whether following your 92311def6ebfb71b4cf1ba1886a33e1734ef1f68 in #2847 helm chart tarballs should appear in https://github.com/kubernetes-sigs/service-catalog/tree/gh_pages/charts_archive/catalog but can't see one yet there

**Comment by jhvhs** [comment]
@obeyler We can make a new 0.3.1 build with the patches included sometime before next week.

**Comment by jhvhs** [comment]
@gberche-orange The charts are only built for new versions.The latest v0.3.0 is there.

**Comment by obeyler** [comment]
> @obeyler We can make a new 0.3.1 build with the patches included sometime before next week.

Thanks it world be great!

**Comment by obeyler** [comment]
> @obeyler We can make a new 0.3.1 build with the patches included sometime before next week.

@jhvhs Does it still plan for this week for a helm release ?

**Comment by jhvhs** [comment]
@obeyler Sorry, there has been a delay, I'll try to make the patch release this week. And, yes, this includes a new helm release.

**Comment by obeyler** [comment]
@jhvhs Thanks by advance

**Comment by jhvhs** [comment]
Done.
The new charts can be found at the GH pages repo https://kubernetes-sigs.github.io/service-catalog
