### ISSUE TITLE
Migrate the helm chart schema to v2 for helm3

### ISSUE THREAD

**Issue by jhvhs** [kubernetes-sigs/service-catalog#2855]
[On November 13, 2020, Helm v2 support has formally ended](https://github.com/helm/charts#status-of-the-project), so in line with this change, the helm chart has to be completely migrated to use the [`v2` apiVersion](https://helm.sh/docs/topics/charts/#the-apiversion-field) schema to clarify incompatibility with helm 2.

Other changes being made include [moving the CRD definitions](https://github.com/kubernetes-sigs/service-catalog/pull/2850) to the location [supported by helm3](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you).

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
