### ISSUE TITLE
Can't provision serviceinstance of api service.

### ISSUE THREAD

**Issue by dekiel** [kubernetes-sigs/service-catalog#2856]
# Bug Report 

**What happened**:

Did create application which had one api service defined which is sending traffic outside kyma. Application was created in kyma-slack namespace. In namespace gh-connector i had function which want to use api service exposed by application from kyma-slack namespace. Did create application mapping in gh-connector namespace to bind application to it. When trying to create service instance with following yaml file.
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kyma-slack
  namespace: gh-connector
spec:
  serviceClassExternalName: kyma-prow-dev-null-a12ce
```
I've got error message.
```
Error from server (could not find a single ServiceClass with "servicecatalog.k8s.io/spec.externalName" = "kyma-prow-dev-null-a12ce", found 2): error when creating "kymaSlackServiceInstanceForGhConnector.yaml": admission webhook "mutating.serviceinstances.servicecatalog.k8s.io" denied the request: could not find a single ServiceClass with "servicecatalog.k8s.io/spec.externalName" = "kyma-prow-dev-null-a12ce", found 2
```

**What you expected to happen**:
Successful creation of service instance which would allow me to bind it to function in gh-connector namespace.

**How to reproduce it (as minimally and precisely as possible)**:
Create application with api service and bind it to another namespace. Try to provision service instance with example serviceinstance yaml file provided earlier.

**Anything else we need to know?**:
No
**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.6
- service-catalog version:
image: eu.gcr.io/kyma-project/external/quay.io/kubernetes-service-catalog/service-catalog:v0.3.0-6-g8e85904-dirty
- Cloud provider or hardware configuration:
gke
- Do you have api aggregation enabled?
no
- Do you see the configmap in kube-system? 
- Does it have all the necessary fields?
- `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
Did install kyma with kymacli using release version 1.16.
- Did you use helm? What were the helm arguments? Did you `--set` any extra values?
Didn't use helm.
- Are you trying to use ALPHA features? Did you enable them?
Did not enable alpha features.

**Comment by mszostok** [comment]
Hi @dekiel 

The problem is that you created such manifests:
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kyma-slack
  namespace: gh-connector
spec:
  serviceClassExternalName: kyma-prow-dev-null-a12ce
```

as you can see you specified only `serviceClassExternalName` and no `servicePlanExternalName`. If you define only class name then the Service Catalog sets the default service plan if **only one plan exists**. In your case error says that  it found 2 and cannot decide which one to use, so you need to do it manually
```
could not find a single ServiceClass with "servicecatalog.k8s.io/spec.externalName" = "kyma-prow-dev-null-a12ce", found 2
```

What you need to do is to create a Service Instance with `servicePlanExternalName` parameters:
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kyma-slack
  namespace: gh-connector
spec:
  serviceClassExternalName: kyma-prow-dev-null-a12ce
  servicePlanExternalName: {specific_name}
```

to get the plan name you can execute the `kubectl get serviceplans -n {your_namespace}` command, e.g.:
```bash
$ kubectl get clusterserviceplans
NAME                       EXTERNAL-NAME      BROKER       CLASS        AGE                                                                                                                                                                                                    
mariadb-10-3-22            10-3-22            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-28            10-1-28            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-29            10-1-29            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-30            10-1-30            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-31            10-1-31            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-32            10-1-32            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-33            10-1-33            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-34            10-1-34            minibroker   mariadb      34m                                                                                                                                                                                                    
mariadb-10-1-34-debian-9   10-1-34-debian-9   minibroker   mariadb      34m
```
as you can see, there is the `EXTERNAL-NAME` column and information about the `CLASS` that this plan correlates to.


See the bellow comment for more possible configurations:
https://github.com/kubernetes-sigs/service-catalog/blob/f83ebf922fd676cf75b5541d9980737da9f91203/pkg/apis/servicecatalog/v1beta1/types.go#L782-L791

**Comment by jasiu001** [comment]
In case when plan is not set, SC (to be more specific mutation webhook for SI) tries to find "default" plan.
IMO there is a bug in the mutation webhook, in [list](https://github.com/kubernetes-sigs/service-catalog/blob/master/pkg/webhook/servicecatalog/serviceinstance/mutation/default_service_plan.go#L236) functionality. ServiceClasses should be searched within a namespace scope:
```go
err := d.client.List(ctx, serviceClassesList, client.MatchingLabels(map[string]string{
  filterLabel: util.GenerateSHA(filterValue),
}), client.InNamespace(instance.Namespace))
```
(I will test this solution and make PR)

**Comment by jhvhs** [comment]
@dekiel Can we close this issue?

**Comment by dekiel** [comment]
Thanks guys for explanation and help. Before fix, adding servicePlanExternalName did the trick.
