### ISSUE TITLE
Onboarding of the Service Binding Specification

### ISSUE THREAD

**Issue by arthurdm** [kubernetes-sigs/service-catalog#2857]
In a recent call with @jberkhahn and @jhvhs we have agreed to explore the donation of the [Service Binding Specification](https://github.com/k8s-service-bindings/spec) to the Service Catalog SIG.  

We have an [issue](https://github.com/k8s-service-bindings/spec/issues/138) on the spec side to track changes needed there, and this cross issue will track changes needed on the SIG side to onboard the spec.

CC @nebhale @scothis

**Comment by sbose78** [comment]
I'm curious, how does this align with the following :)  

> Service Catalog is a Kubernetes extension project that implements the Open Service Broker API (OSBAPI). It enables application developers to provision cloud services from within Kubernetes and integrates configuration and discovery of those services into Kubernetes resources

**Comment by arthurdm** [comment]
ya - the thought is that someone could adopt the Service Binding aspect from the SIG without needing to use or adopt OSBAPI.  There's some integration effort to make them work together nicely if both present, but each should be able to stand on their own.  

@jberkhahn and @jhvhs - would like to hear your thoughts on this approach.

**Comment by gorkem** [comment]
I am not sure if being associated with the Service Catalog SIG is actually for the benefit of the Service Binding Specification. Service Binding can be used in many other ways, for instance Operators and Operator Lifecycle Manager, helm charts etc. I am concerned if this association limits the perception of the specification for no good reason.

**Comment by jberkhahn** [comment]
Many sigs have many subprojects that are rather loosely related - if anything Service Catalog is unusual in how focused it is. I don't see a problem to existing as a subproject of Service Catalog, especially if you want to be part of the Kubernetes community.

**Comment by gorkem** [comment]
Sounds like you are saying just be part of a SIG no matter what the optics are .

**Comment by arthurdm** [comment]
hey everyone - thanks for the comments so far, good discussion.  

My 2 cents is that from the spec's perspective one of the main challenges we have is finding a suitable umbrella home - something that solves the "API domain / group" problem but most importantly a place where we can reach the larger k8s community and increase awareness / adoption.  

With that frame of mind, and being that the spec is focused solely on k8s, we started to look into the SIGs as matching our needs.  There are probably other "homes" we could look into, but this felt like the more neutral place that was closer to the community we want to target.

**Comment by jberkhahn** [comment]
per the discussion at the 2/22 meeting today, here's the process for contributing existing repositories to the sig:

1. A SIG chair has to open a "Repository creation/migration" issue at [kubernetes/org](https://github.com/kubernetes/org). They'll have to fill out who should have access to the repo and stuff like that, but it should be pretty straightforward
2. The donated repos have to satisfy [these requirements](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) from kubernetes/community
3. The kuberetes/org folks will go back and forth with the owners of the repo to make sure everything looks good and for the actual handoff

You can look at [this issue](https://github.com/kubernetes/org/issues/894) and [this issue](https://github.com/kubernetes/org/issues/893) to see the times we've done it before.

**Comment by jhvhs** [comment]
Please take a look at the proposed changes to the SIG charter. The purpose of the changes is to widen the scope to include projects that would not necessarily be OSBAPI specific, and might be specifications rather than implementations, but would still serve the same purpose.
Link: https://docs.google.com/document/d/1ElbThBA2sT2Q6PxoPcCX2k_grG9VHUSDeanrP7r9now/edit?usp=sharing
