### ISSUE TITLE
Migrating to travis-ci.com

### ISSUE THREAD

**Issue by shivaburade** [kubernetes-sigs/service-catalog#2892]
# Bug Report 

**What happened**:
The travis-ci.org site will not run any new builds after June 15th, 2021.
Do we have any plans to migrate the repository to travis-ci.com? This is important for architectures like s390x which have CI support through Travis only.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by jhvhs** [comment]
Thank you for bringing attention to the travis-ci.org. We do intend to move the builds in the near future. I'll keep this issue open until the migration is complete.

**Comment by shivaburade** [comment]
Thank you for your response. Is there any updates on this?

**Comment by jhvhs** [comment]
Other projects have been struggling with the new travis infrastructure, as well as their pricing model. We'll have to explore other options for running our tests on all supported platforms.

**Comment by shivaburade** [comment]
@jhvhs Could you please elaborate more on the issues/struggles faced by the projects due to the new Travis infrastructure?

As per the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis fully supports the OSS teams and allocates them more credits after they apply for the same.
Could you please open a request with Travis CI support stating that you'd like to be considered for the OSS allotment?

Please refer to the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) for more details on how to open a support request with Travis.

**Comment by shivaburade** [comment]
@jhvhs any updates?

**Comment by shivaburade** [comment]
@jhvhs any updates?

**Comment by shivaburade** [comment]
@jhvhs any updates?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
