### ISSUE TITLE
Is this project no longer maintained？

### ISSUE THREAD

**Issue by duanhongyi** [kubernetes-sigs/service-catalog#2901]
If the answer is yes, is there an alternative; My colleagues and I maintain the [drycc](https://github.com/drycc/workflow) project together. In the drycc project, we use service-catalog. 

If no one maintains the project, my colleagues and I can consider taking over it.

**Comment by jberkhahn** [comment]
Hey there,

Not much active development. Really the only still active person is @jhvhs. If you're interested in contributing to the project, I'd message them about it.

**Comment by duanhongyi** [comment]
Please help us convey, that our GitHub ID is:

@duanhongyi
@jianxiaoguo
