### ISSUE TITLE
make a kubectl image in k8s core builds

### ISSUE THREAD

**Issue by duglin** [kubernetes-sigs/service-catalog#315]
See https://github.com/kubernetes-incubator/service-catalog/pull/312#discussion_r98359630

a nightly one and official (based on releases) would be good.

**Comment by MHBauer** [comment]
@duglin can we use the hyperkube image?

**Comment by duglin** [comment]
is kubectl part of hyperkube?  
Even if it is, that seems like a really large image just to get the client. But, if we have it on our system for other reasons (like testing) then it might not be that bad.

**Comment by MHBauer** [comment]
It is!
```
# docker run -i -t gcr.io/google_containers/hyperkube:v1.5.3 /kubectl
kubectl controls the Kubernetes cluster manager.

Find more information at https://github.com/kubernetes/kubernetes.

Basic Commands (Beginner):
  create         Create a resource by filename or stdin
...
```

We have docker on travis, so I suppose we can try running the dockerized kube.

**Comment by pmorie** [comment]
@duglin Will you go ahead and create in issue in kubernetes/kubernetes for this and link it here?

**Comment by duglin** [comment]
@brahmaroutu is doing some investigation on this and if needed then yes he'll open an issue upstream.

**Comment by pmorie** [comment]
@duglin @brahmaroutu I think this can be closed, correct?

**Comment by brahmaroutu** [comment]
#dibs
Even if I build kubectl and make a image using examples/kubectl-container/Dockerfile, I need to figure out how CI can push this image on  release basis to the repo(gcr).

**Comment by arschles** [comment]
@brahmaroutu what is the status of this issue? I have scheduled it for `0.0.3`, which is scheduled for 4/14/2017

**Comment by pmorie** [comment]
We should not need this. We should just use the hyperkube image from
upstream.

**Comment by duglin** [comment]
if someone wants to talk to a remote kube asking them to download a 500 meg image vs a 50 meg image is a bit much. I see no reason not to allow both.

**Comment by brahmaroutu** [comment]
@arschles @pmorie I still think containerized kubectl is useful but CI also needs changes to push the image to the repo on which I do not clarity.

**Comment by arschles** [comment]
I am moving this into the beta cycle (0.1.0), as it doesn't appear crucial for integration or e2e test integration

**Comment by arschles** [comment]
Moving this out of beta, as it doesn't require any api surface changes.

**Comment by MHBauer** [comment]
upstream issue https://github.com/kubernetes/kubernetes/issues/16437

**Comment by MHBauer** [comment]
since it's CI can we use something like https://github.com/lachie83/k8s-kubectl ?
