### ISSUE TITLE
Standalone k8s broker?

### ISSUE THREAD

**Issue by jmcarp** [kubernetes-sigs/service-catalog#316]
I'm wondering if the helm-powered k8s broker in https://github.com/kubernetes-incubator/service-catalog/tree/master/contrib/pkg/broker is or might become a replacement for https://github.com/18f/kubernetes-broker, which my team is currently using to broker k8s resources to cloud foundry applications. I had a few questions about this:

* Could this package be broken out into a separate repository to make it easier to find? I only stumbled across it by chance.
* It looks like I'd need to run both the broker and the service registry, with the broker querying the registry to figure out which services it offers. I'm wondering why these are separate applications--in my experience with service brokers in cf-land, the catalog often lives in the broker app and is configured by passing a file that can be checked into source control, [like this](https://github.com/alphagov/paas-rds-broker/blob/master/config-sample.json).
* WDYT about getting bind credentials using configmaps or similar, as in https://github.com/deis/steward/blob/master/doc/HELM_MODE.md#bind-and-unbind-operations ? I assume you're familiar, since it looks like both packages come from deis 😄. It looks like the current logic requires the chart notes to be valid yaml and nothing else.

Also, if the broker package is far enough along that you're accepting outside contributions, I'd be happy to give it a try and potentially start contributing--let me know!

**Comment by vaikas-google** [comment]
#1 : it could, our thinking was that at least for now it would be nice for everything to 'just come up' so you could build, push and get things up and running without different repos.
#2 : The thinking behind this is that a single broker [helm broker  in this case], could dynamically support different kinds of ServiceClasses simply by you adding a schema / templates and then that broker would be able to instantiate them. So, there's kind of two catalogs there, broker / registry catalog, and the Service Catalog, which in turn exposes what brokers support. Hope that makes sense.
#3 : are you thinking about how to get bindings from the broker [they come in a form of an API] or how the Controller manifests them for consumption? If latter, then yes, the creds get stuffed into secrets [and/or later into configmaps is the plan]

**Comment by pmorie** [comment]
@jmcarp We can definitely discuss splitting out some of the brokers under contrib into separate repositories once we get our MVP into shape.  I would prefer to have folks remain focused on MVP for the moment.  Does that work for you?  Thanks a lot for your interest and apologies for the latency responding.
