### ISSUE TITLE
OpenAPI docs should be hosted somewhere

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#453]
Forked from #78; it would be awesome to have the OpenAPI docs in master hosted somewhere.

**Comment by jwforres** [comment]
Would love to see this, will make it easier to keep up with the current state of the API

**Comment by krancour** [comment]
@pmorie should it really be incumbent upon our project to host another project's documentation? I submit, no.

**Comment by pmorie** [comment]
No, but we should our own openapi for the svc cat k8s api

**Comment by arschles** [comment]
@pmorie @jwforres has anyone started on this? I am removing it from a milestone, but happy to re-add if someone is planning on doing the work.

**Comment by duglin** [comment]
As much as I dislike us checking in our generated code, it seems to me that if we're already doing that, then we could just check-in the openapi docs too and host it via our github repo, no?

I believe that are talks about removing generated code/docs from the main kube repo too and one idea was to remove it from the main repo but still host it some place else - once (if?) they do that we could leverage the same thing.  @spzala what's the status of that work?

If it doesn't look like this will happen soon in the main repo, we could give it a try in ours as a testbed to see how it works.

**Comment by spzala** [comment]
@duglin hi, I touch based on it little over a week back but didn't hear feed back. I have just added a reminder and mentioned this issue/discussion. Here is the issue that's in discussion in k8s https://github.com/kubernetes/kubernetes/issues/47361 Thanks!

**Comment by IvanJosipovic** [comment]
+1

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632

/close
