### ISSUE TITLE
Policy for handling broker deletion and deprovision

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#481]
At our last face-to-face meeting in late January 2017, we discussed what the system should do on a broker deletion and deprovision operation.

__On a deprovision operation__, we decided that the default case is to fail the deprovision if there are bindings against the instance being deprovisioned. A "force" or "cascade" flag can be explicitly set on the call to make all bindings be unbound, and then the deprovision be done.

We decided on a similar strategy for broker deletion.

This issue is for discussing how we are going to achieve this functionality in `kubectl`. The CLI provides a `--cascade` and `--force` flag that we should consider utilizing for this purpose.

**Comment by pmorie** [comment]
Not going to be in 0.0.2

**Comment by arschles** [comment]
Moving out of a milestone until we decide what to do here.

**Comment by duglin** [comment]
Added 1.0.0 since we need to decide before v1.

**Comment by mszostok** [comment]
we started working on that, see: https://github.com/kyma-project/kyma/issues/5180

more details will be presented soon
