### ISSUE TITLE
How should we treat OSB tags?

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#497]
The OSB API provides tags, a list of strings, to do the type of filtering that kubernetes uses labels for.  This issue is to determine if we should:

1.  Just use tags to do the type of search that CF does using tags
2.  Translate tags into label selectors somehow and use label selection
3.  Something else TBD

cc @jwforres

**Comment by pmorie** [comment]
Moving to 0.0.3 because we will not get to it before then.

**Comment by arschles** [comment]
Moving this into 0.1.0 since we will need to decide on OSB tags before we provide backward-compatibility guarantees by then

**Comment by duglin** [comment]
Since labels and annotations are name/value pairs, but tags are just strings it doesn't seem like there's a good spot put them on the kueb core resource model.  This would seem to then imply that we're probably going to have to keep this info in our own property - like we have now. Its just too bad that we can't easily search over it with some native kube search facility. We should have a brief chat about this but I'd suggest we close this issue.

**Comment by pmorie** [comment]
We could also remove both 'tags' and 'requires' and figure out how to treat
them later.

**Comment by duglin** [comment]
true, that would be the super safe option for beta.

Haven't thought much about 'requires' yet - does anyone think it would ever be more than just an array of strings to us?  I know at some point we'll need to look at it and perhaps do something (like reject a serviceClass if we don't support one of the "requires") but would we ever store it as something else?

**Comment by jwforres** [comment]
Please do not remove tags completely, if you want to change it to an alpha field until you decide what to do long term that's fine.

**Comment by pmorie** [comment]
I will open a PR to change the name of `Tags` to `AlphaTags` after https://github.com/kubernetes-incubator/service-catalog/pull/843 is merged

**Comment by arschles** [comment]
We're moving all `OSB*` tags to alpha. Moving to 1.0.0

**Comment by duglin** [comment]
to be clear, its just one property "OSBTags" we're moving, not all OSB properties

**Comment by MHBauer** [comment]
This isn't closed by #861 or #1180. We still don't handle tags, but they're described as alpha.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
