### ISSUE TITLE
Add easy deploy process for hackerz

### ISSUE THREAD

**Issue by krancour** [kubernetes-sigs/service-catalog#562]
This is a follow up to #546, which refactors the catalog chart.

As `helm install ...` (_without_ the need to build from source _first_) becomes the canonical way of getting service catalog up and running in a cluster-- even for contributors-- contributors need a seamless way to "slot" custom-built images into the running service catalog deployment in place of the official "canary" images that get pulled down from quay.io upon initial deployment.

From experience... everyone's first impulse where this is concerned is to modify (for instance) the value of `apiserver.image` to reference the custom-built image, then use normal Helm workflows like `helm upgrade` to facilitate the change. But imo, this is too high-touch. I want something as seamless as `make apiserver-hack-deploy`.

What I imagine this doing is rebuilding the apiserver image, pushing it to whatever registry the contributor has configured, and then automatically performing on-the-fly edits to the existing apiserver deployment to reference the new image. k8s takes care of reconciling the rest.

This strategy has already been used successfully in several Deis projects where we have this same problem of wanting to "slot" a hacked image in as a replacement for an official image. Here's one such example:

https://github.com/deis/router/blob/master/Makefile#L59-L66

__EDIT:__ To clarify, new developer documentation would go something like this:

- Deploy as normal
- Hack, hack, hack,
- `make <component>-hack-deploy`

**Comment by arschles** [comment]
I will share my dev/build/deploy process on a minikube cluster here in case it helps:

First, I build the images using my minikube docker daemon:

```console
eval $(minikube docker-env)
MUTABLE_TAG=devel make images
```

Then, I use the standard helm chart to install to the same cluster. Note that no images should be pulled, because they are already on the daemon.

```console
helm install --namespace=steward --set apiserver.image=apiserver:devel,apiserver.imagePullPolicy=Never,controllerManager.image=controller-manager:devel,controllerManager.imagePullPolicy=Never charts/catalog
```

When I want to rebuild, I just `kubectl delete` the pod.

**Comment by krancour** [comment]
> First, I build the images using my minikube docker daemon

How would your workflow be changed if you weren't doing that? I can think of a few reasons people might not want to do that.

**Comment by arschles** [comment]
I am purely explaining here what works for me, in case it helps the discussion here
