### ISSUE TITLE
Add auth to the fake broker server, and test it

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#571]
Make sure that the OSB client properly sends auth headers on all requests.

**Comment by MHBauer** [comment]
Currently it does not check the contents, but it does check for presence or absence. Absent headers will fail tests by returning 404.

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't done yet.

**Comment by arschles** [comment]
This looks related to https://github.com/kubernetes-incubator/service-catalog/pull/533

**Comment by arschles** [comment]
#533 is related to this, as that includes other improvements to the fake broker server

**Comment by pmorie** [comment]
Moving to next alpha release for now.  We probably need someone to own all of these related issues.

**Comment by arschles** [comment]
I am moving this to the beta cycle along with #533

**Comment by arschles** [comment]
I am removing a milestone from this issue

**Comment by duglin** [comment]
I'm tagging this a v1.0 because it seems to me that if we don't have a fake broker that supports checking auth then we're not fully testing the most comment flow.  We should test w/ and w/o auth BTW.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
