### ISSUE TITLE
Document how people can get various levels of access to our repository

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#634]

**Comment by arschles** [comment]
This requires discussion, which we aren't going to get to during this milestone. I will schedule that discussion and I'm moving this to 0.0.4

**Comment by arschles** [comment]
Moving to the beta cycle

**Comment by arschles** [comment]
Moving to 0.2.0 for further discussion.

**Comment by duglin** [comment]
@arschles can you elaborate a bit on this - I'm unclear on what the issue is.

**Comment by arschles** [comment]
Very specifically, I would like us to have a document that clearly specifies how a new contributor can become a maintainer to this repository. I believe that the steering committee is doing some work  to define the criteria across SIGs, so I think we should put this on hold for now. I'm going to remove from the 0.2.0 milestone.

**Comment by MHBauer** [comment]
Our SIG charter https://github.com/kubernetes/community/pull/2233
