### ISSUE TITLE
Store & report code coverage data

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#72]
After https://github.com/kubernetes-incubator/service-catalog/pull/63, we'll have tests running with code coverage, but we won't (yet) have a place to send that coverage data or surface it to developers. If we get that, it will allow developers to make measurable gains on test coverage in each PR.

We've used codecov.io successfully in the past. [Here](https://github.com/deis/steward/blob/master/.travis.yml#L21) is an example for how to send coverage data up to the service.

**Comment by MushuEE** [comment]
https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-coverage-unit k8s coverage dashboard example

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632

/close
