### ISSUE TITLE
Testing: helper methods shouldn't fail tests directly

### ISSUE THREAD

**Issue by krancour** [kubernetes-sigs/service-catalog#763]
There are numerous places where we use test "helper" functions that directly fail tests (e.g. `t.Fatalf(...)` when an assertion fails. This produces error reports where the source of such failures appears to be the helper function-- which is not the _real_ source of the failure. This necessitates careful reading of the resulting stack trace where it could, possibly, be avoided otherwise.

To whatever extent is possible, we should seek to identify and remediate any places in test code where this is occurring.

**Comment by duglin** [comment]
if we have control over the helper functions then it seems like we should be able to have that code walk back up the stack a few steps and print the non-helper-func's src/line-num.

**Comment by MHBauer** [comment]
@krancour @duglin is there anything specifically actionable here? Should we add this to a developer guide of some kind?

**Comment by duglin** [comment]
Are there any helper functions we use that we own?

**Comment by MHBauer** [comment]
/cc @jberkhahn 
this is probably taken care of by the test rewrites
