### ISSUE TITLE
Ensure 412 error code from broker is handled correctly

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#811]
per https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#api-version-header

**Comment by MHBauer** [comment]
This needs to be done upstream https://github.com/pmorie/go-open-service-broker-client/issues/126

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
