### ISSUE TITLE
Store dashboard SSO information for a service in a k8s secret

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#813]
The dashboard SSO information for a service contains secret information and should live in a k8s secret.

**Comment by pmorie** [comment]
I was thinking about this and there's a level of indirection we need to figure out.  Services are returned by the broker, so if we add a field to ServiceClass like so:

```go
type ServiceClass struct {
  // other fields omitted
  DashboardSSOSecret *v1.ObjectReference
}
```

... then we need to set that field somehow ourselves.  Breaking that down:

1.  We need to determine which namespace the secret should live in - perhaps by adding a `DashboardSSOSecretNamespace` field to the broker's spec
2.  We need to determine the name of the secret to create for each service - we could use something like `dashboard-sso-${service guid}`, since the ID is supposed to be stable

**Comment by duglin** [comment]
not sure we can add a namespace to the broker spec since isn't that basically generated by us upon reading the catalog from the broker?  Can't we just use the default namespace - like the default service account uses?

**Comment by pmorie** [comment]
We own the broker spec, so we can add fields to it.

**Comment by duglin** [comment]
ok - I misread what you were saying. I thought your first bullet was implying that someone was providing that info to us. Sorry

**Comment by pmorie** [comment]
Yeah, I was referring to the catalog entries (serviceclasses) - the broker
sends those to us, so we need to generate where the secret lives.  I was
saying we can put the knob on the broker spec, which we control

**Comment by pmorie** [comment]
I am moving this to the 1.0.0 milestone because I don't think it should be required to take the initial API beta.  I do think there is a question of whether we make these fields alpha in the API for now or remove them entirely.  I would be comfortable with removing the fields entirely and saying the the 0.1.0 release does not support dashboard SSO.

**Comment by duglin** [comment]
If there's a good chance of us dropping a field as a result of this then yea let's drop it for beta and add it back in later at the right spot

**Comment by pmorie** [comment]
Okay, I will do a PR for that now.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
