### ISSUE TITLE
Determine criteria for whether an alpha OSB feature is ready to release in the spec

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#901]
The process for making changes to the OSB API (see https://github.com/openservicebrokerapi/servicebroker/blob/master/CONTRIBUTING.md#design-change-proposals) has a phase where a feature is accepted in principle but where the API particulars are not fully solidified yet.  In our repo, we've decided that we will call these alpha features when we need to expose them in our API.  One thing we haven't decided yet is what our criteria for accepting a particular change to the spec and saying that we are ready for it to be released is.  We should figure that out now and record what we think the decision plane is in a doc in our repo.

**Comment by pmorie** [comment]
At this point, I think my personal idea of criteria for this is:

1.  Have we implemented the feature in the controller and feel that the proposed form accomplishes the goal while leaving room for future improvements that are backward compatible?
2.  Has the feature been implemented by brokers in our ecosystem and do broker authors feel that the proposed form accomplishes the goal while leaving room for future improvements that are backward compatible?

We can make the decision plane more detailed and formal for now, but I would like to get some rough agreement and make a decision on whether the context field can be released for v 2.12.

**Comment by vaikas-google** [comment]
I think these two criteria make sense. It would be interesting to figure
out how we can achieve #2. Seems like there are typically some broker
implementers who are requesting changes, so having some sort of method for
tracking these as well as validating that they meet the needs should
probably be thought of. Also is it enough if one broker implements it and
are happy with it? I understand you propose doing more details later, and
I'm fine with it for now, just thinking out loud :)

**Comment by arschles** [comment]
That list looks good @pmorie. I have a slightly off topic, but important request that we put support for larger OSB API changes behind a feature flag & admission controller until those criteria are met.

We can use our judgement RE what is a larger change

**Comment by pmorie** [comment]
@arschles IMO the version of the API a broker supports should be controllable, and whether that broker supports alpha features should also be controllable
