### ISSUE TITLE
On provision, service-catalog doesn't write the description or status code of an unexpected broker response 

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#914]
If a broker doesn't return an [expected response code](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-2), it writes nothing into the `status.conditions` field of the newly created `Instance`. It should at least write the status code returned by the broker server.

Repro steps:

1. Follow all steps in [this demo repository](https://github.com/arschles/meta-azure-service-broker-helm) through ["View Service Classes"](https://github.com/arschles/meta-azure-service-broker-helm#view-service-classes)
2. Follow steps in ["Provision a New Service"](https://github.com/arschles/meta-azure-service-broker-helm#provision-a-new-service)
3. Follow steps in ["Provision a New Service"](https://github.com/arschles/meta-azure-service-broker-helm#provision-a-new-service) again
4. Notice that the 2nd `Instance` has an empty `conditions` field, while the broker server failed and the controller logs showed an error response from the broker server

Note that service-catalog currently implements a proper client for the OSB API spec, but silently failing for brokers that are not 100% adherent to the spec presents a very difficult user experience. I'd like for at least the status code and the response body to be written into a condition in the failed `Instance`'s `status.conditions` field.

**Comment by MHBauer** [comment]
I read through #925 & #915 and I am missing some higher level understanding to get what is being addressed here.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
