### ISSUE TITLE
Determine whether controller should update secrets

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#921]
While adding support for PodPreset in #917, I noticed that the controller will update an existing secret if it already exists instead of trying (and failing) to create that secret.  I am not sure at all if that is the right behavior.  We should think about whether this is a valid use case; I'm inclined to say that it is not, since we do not currently have anything that would result in the binding being updated.

I would say that we should annotate objects that we create for Bindings with an owner reference to the Binding, so that if an object already exists before we create it, we can determine whether it was created by the catalog or not.  We definitely should not update a random secret not created by the catalog.

**Comment by nilebox** [comment]
@pmorie Agree with everything you said there.
Checked the OSB spec - looks like bindings are immutable, only instances can be updated.
My only concern is that we should probably distinguish two cases:
- secret is not owned by Service Catalog or owned by different Binding: change Binding status to error, and let the user resolve this issue.
- secret belongs to a Binding we are processing: what if we previously failed to update the status of binding after creating a secret? What is the correct behavior, and do we handle this situation correctly?
