### ISSUE TITLE
Add test to ensure the controller times out on long-running requests to brokers

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#984]
We need to ensure that the controller is resilient to poorly behaving broker servers that are extremely slow.

Ref #113, as that issue suggests a possible way to time out individual HTTP requests. We may or may not need that addition.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
