### ISSUE TITLE
Implement JWT for broker auth

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#990]
The Open Service Broker API has a [PR for additional auth schemes](https://github.com/openservicebrokerapi/servicebroker/pull/223) open that allows for platforms and brokers to agree on their own auth schemes outside of the spec. Since it's in the design phase, the API working group is looking for platforms to implement an auth scheme and report back on how it works. I propose that we implement one.

Here's specifically what I propose:

1. We use [JWT](https://jwt.io/) for authentication, and JWT claims (which are a part of standard JWT payloads) for authorization
2. The cluster operator gets the JWT from the broker outside of the service-catalog
    - This is no practical change from what we currently do with the basic auth credentials
    - We can explore using OAuth2 later to eliminate this manual, out-of-band exchange step
3. We add a `jwtSecret` field to the `Broker`'s `spec.authInfo` field. If both fields are present, the controller doesn't process the `Broker` and puts an error message in its conditions. If `jwtSecret` is present, it:
    1. Fetches the secret pointed to by the `jwtSecret` field
    2. Looks for the `token` key in that secret
    3. Sends the value of the `token` key in the `Authorization` header as `Authorization: Bearer $TOKEN`

The goals with this work are twofold:

1. Enable an authn/authz scheme that is digitally signed and can't be tampered with, even over HTTP (which is currently what we use). Note that TLS is out of the scope of this issue.
2. Prove another authn/authz scheme and drive it upstream to the OSB spec

Note that there is a [skeleton of a proposal for adding OAuth2 + JWT to the OSB API spec](https://docs.google.com/document/d/196-LCfWwObkF1upI2byIXgvMs8FZgYn7iB06dXDhAXE/edit).

**Comment by deads2k** [comment]
> Enable an authn/authz scheme that is digitally signed and can't be tampered with

I'm not clear on why a JWT is required.  Since the broker has to do verification of the token, it seems like the choice of token format should be up to the broker.  The service catalog should treat all tokens as opaque, so I don't think that a JWT is required.

> even over HTTP (which is currently what we use). Note that TLS is out of the scope of this issue

Sending a bearer token over HTTP is bad practice since the token can be observed and replayed.  I think that verifiable TLS should be required.  At the very least, it must be possible and strongly recommended.

**Comment by bmelville** [comment]
@rifung

**Comment by bmelville** [comment]
I see this has been given 1.0.0 milestone. We have some use-cases that really necessitate authenticating using OAuth tokens and would require something like this, so I'm wondering if there's any path that would allow us to execute on this sooner than that.

**Comment by duglin** [comment]
Feel free to move it up

**Comment by bmelville** [comment]
Started a more general issue in #1019 for supporting alternative auth, as JWT maybe is one of several.

**Comment by nilebox** [comment]
> We add a jwtSecret field to the Broker's spec.authInfo field. If both fields are present...

@arschles I think there is some typo in the sentence. You start with a single `jwtSecret` field and then continue with "if both fields..."

**Comment by nilebox** [comment]
> I'm not clear on why a JWT is required. Since the broker has to do verification of the token, it seems like the choice of token format should be up to the broker. 

There is some confusion about JWT which needs to be clarified in the original message of this issue.
Service Catalog (client side) has to be able to generate the token using `secret` (private key). JWT `token` could be short-lived, has request-specific attributes, and static token stored inside the `Broker` resource is not an option.  The secret should contain the `secret` for generating a signature, not a JWT `token`.

**Comment by liggitt** [comment]
> @arschles:
> Enable an authn/authz scheme that is digitally signed and can't be tampered with, even over HTTP (which is currently what we use). Note that TLS is out of the scope of this issue.

Bearer token use over http is insecure and should not be used. A JWT token may not be able to be tampered with, but the body certainly can be, or the token can be captured and replayed with a request body specified by the attacker.

> @nilebox:
> Service Catalog (client side) has to be able to generate the token using secret (private key).

That does not match the statement "The cluster operator gets the JWT from the broker outside of the service-catalog" in the description.

The ability to give an opaque bearer token to the service catalog, and have it use that to authenticate is far more flexible than embedding JWT generation into the service catalog. I'd prefer the token be opaque to the service catalog, enabling any bearer-token-based authentication integration.

**Comment by nilebox** [comment]
@liggitt I agree with you that static token is more flexible and algorithm-agnostic, but it doesn't cover the short-lived tokens, which should be generated on-the-fly by client.

That could be a valid limitation, I just wanted to explicitly mention it.

**Comment by liggitt** [comment]
> short-lived tokens, which should be generated on-the-fly by client

it is unusual even for short-lived tokens to be client-generated... typically they are obtained from a source the client and destination server both trust. client-generated tokens means the destination needs a unique shared secret (or registered public key) for every client.

**Comment by nilebox** [comment]
@liggitt you're right, and actually both options are viable depending on the use case.

Either way, it requires client to actively acquire/refresh the token, and static secret can't cover this.

Think about short-lived token as 10 minutes, for example. You can't expect the secret token to be updated every 10 minutes.

**Comment by liggitt** [comment]
> Think about short-lived token as 10 minutes, for example. You can't expect the secret token to be updated every 10 minutes.

Sure you can... that's actually a good example of separable processes... one process maintains the credential by requesting or generating the short-lived JWT, another process uses it as an opaque token.

**Comment by nilebox** [comment]
@liggitt fair enough, that could actually be an option, agreed.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
